DensityOut = Density;
VelocityOut = Velocity;
TemperatureOut = Temperature;
DivergenceOut = 0;
if( ! Enable ) return;
bool Valid;
int MaxNeighborsPerCell;
NeighborGrid.MaxNeighborsPerCell(MaxNeighborsPerCell);
int3 IndexToUse;
int NeighborLinearIndex;
int CurrIdx;
for (int i = 0; i < MaxNeighborsPerCell; ++i)
    NeighborGrid.UnitToIndex(UnitScalar, IndexToUse.x, IndexToUse.y, IndexToUse.z);
NeighborGrid.NeighborGridIndexToLinear(IndexToUse.x, IndexToUse.y, IndexToUse.z, i, NeighborLinearIndex);
NeighborGrid.GetParticleNeighbor(NeighborLinearIndex, CurrIdx);
    float3 ParticlePos = float3(0, 0, 0);
ParticleReader.GetVectorByIndex<Attribute = "Position">(CurrIdx, Valid, ParticlePos);
ParticlePos = mul(float4(ParticlePos, 1.), SimulationToLocal).xyz;
float Radius = 0.0;
ParticleReader.GetFloatByIndex<Attribute = "fluids_source_radius">(CurrIdx, Valid, Radius);
float Dist = length(CellPosScalarGrid - ParticlePos);
float ParticleRadius = Radius * RadiusScale;
    float ParticleDensity = 0;
    float ParticleTemperature = 0;
    float3 ParticleVel = float3(0, 0, 0);
    float ParticleDivergence = 0;
    float NoiseScalePP = 1.;
    ParticleReader.GetFloatByIndex<Attribute = "fluids_source_noiseScale">(CurrIdx, Valid, NoiseScalePP);
        NoiseScalePP = Valid  ? NoiseScalePP : 1;
    float NoiseIntensityPP = 1.;
    ParticleReader.GetFloatByIndex<Attribute = "fluids_source_noiseIntensity">(CurrIdx, Valid, NoiseIntensityPP);
        NoiseIntensityPP = Valid  ? NoiseIntensityPP : 1;
    NoiseScale *= NoiseScalePP;
    NoiseIntensity *= NoiseIntensityPP;
 float FalloffMult = 1. - smoothstep(ParticleRadius * Core, ParticleRadius, Dist);
        float noise = 1.0;
        float3 QueryPos = ParticlePos;
        if( ParticleSpaceNoise )
            uint id = 0;
            ParticleReader.GetIntByIndex<Attribute = "UniqueID">(CurrIdx, Valid, id);
            float offset  = Valid  ? float(id) : 0.0;
            QueryPos += float3(offset, 0, 0) - CellPosScalarGrid;
        else
            QueryPos += CellPosScalarGrid;
       noise = .5 * (FastGradientPerlinNoise3D_TEX(( QueryPos) * NoiseScale + Time * NoiseSpeed) + 1);
       noise = pow(noise, Falloff);
ParticleReader.GetFloatByIndex<Attribute = "fluids_source_density">(CurrIdx, Valid, ParticleDensity);
ParticleDensity *= DensityMult * FalloffMult;
       ParticleDensity  = lerp(ParticleDensity, ParticleDensity * noise, NoiseIntensity);
ParticleReader.GetFloatByIndex<Attribute = "fluids_source_temperature">(CurrIdx, Valid, ParticleTemperature);
ParticleTemperature *= TemperatureMult * FalloffMult;
       ParticleTemperature  = lerp(ParticleTemperature, ParticleTemperature * noise, NoiseIntensity);
    // velocity and divergence grid
    if (VelocityCurrCell < VelocityNumCells)
        NeighborGrid.UnitToIndex(UnitVelocity, IndexToUse.x, IndexToUse.y, IndexToUse.z);
    NeighborGrid.NeighborGridIndexToLinear(IndexToUse.x, IndexToUse.y, IndexToUse.z, i, NeighborLinearIndex);
    NeighborGrid.GetParticleNeighbor(NeighborLinearIndex, CurrIdx);
    ParticleReader.GetVectorByIndex<Attribute = "Position">(CurrIdx, Valid, ParticlePos);
    ParticlePos = mul(float4(ParticlePos, 1.), SimulationToLocal).xyz;
    ParticleReader.GetFloatByIndex<Attribute = "fluids_source_radius">(CurrIdx, Valid, Radius);
    Dist = length(CellPosVelocityGrid - ParticlePos);
    ParticleRadius = Radius * RadiusScale * VelocityRadiusMult;
        if (CurrIdx >= 0 && Dist <= ParticleRadius)
           ParticleReader.GetVectorByIndex<Attribute = "fluids_source_velocity">(CurrIdx, Valid, ParticleVel);
    ParticleVel = mul(float4(ParticleVel, 0.), SimulationToLocal).xyz * VelocityMult;
           ParticleReader.GetFloatByIndex<Attribute = "fluids_source_divergence">(CurrIdx, Valid, ParticleDivergence);      
           ParticleDivergence *= DivergenceMult;
    if (CompositingMethod == 0)
     DensityOut += ParticleDensity;
     TemperatureOut += ParticleTemperature;
   VelocityOut += ParticleVel;
            DivergenceOut += ParticleDivergence;
DensityOut = max(DensityOut, ParticleDensity);
TemperatureOut = max(TemperatureOut, ParticleTemperature);
if (dot(ParticleVel, ParticleVel) > dot(VelocityOut, VelocityOut)) VelocityOut = ParticleVel;
        DivergenceOut = max(DivergenceOut, ParticleDivergence);
#endif //GPU_SIMULATION
for (int CurrIdx = 0; CurrIdx < NumParticles; ++CurrIdx)
float3 ParticlePos = float3(0, 0, 0);
float DistVelocity = length(CellPosVelocityGrid - ParticlePos);
    if (DistVelocity <= ParticleRadius * VelocityRadiusMult)
       ParticleReader.GetVectorByIndex<Attribute = "fluids_source_velocity">(CurrIdx, Valid, ParticleVel);
ParticleVel = mul(float4(ParticleVel, 0.), SimulationToLocal).xyz * VelocityMult;
       ParticleReader.GetFloatByIndex<Attribute = "fluids_source_divergence">(CurrIdx, Valid, ParticleDivergence);      
       ParticleDivergence *= DivergenceMult;
IndexX < Width - 1 && IndexY < Height - 1 && IndexZ < Depth - 1;
DensityOut = 0;
VelocityOut = 0;
TemperatureOut = 0;
TextureCoordOut = 0;
DistanceOut = 1000000;
ColorOut = float4(0,0,0,0);
float TotalWeight = 0;
int NumOverlapParticles = 0;
float3 ParticlePos;
float3 ParticleGridLocalPos = mul(float4(ParticlePos, 1.), WorldToLocal).xyz;
float Dist = length(CellGridLocalPos - ParticleGridLocalPos);
    float4 ParticleColor = 0;
        float3 ParticleRestPos;
        ParticleReader.GetVectorByIndex<Attribute = "RestPosition">(CurrIdx, Valid, ParticleRestPos);
float3 ParticleGridLocalRestPos = mul(float4(ParticleRestPos, 1.), WorldToLocal).xyz;
        float4 MeshOrientation;
        ParticleReader.GetQuaternionByIndex<Attribute="MeshOrientation">(CurrIdx, Valid, MeshOrientation);
        ParticleReader.GetFloatByIndex<Attribute = "fluids_source_density">(CurrIdx, Valid, ParticleDensity);
        ParticleDensity *= DensityMult;
        ParticleReader.GetFloatByIndex<Attribute = "fluids_source_temperature">(CurrIdx, Valid, ParticleTemperature);
        ParticleTemperature *= TemperatureMult;
        ParticleReader.GetVectorByIndex<Attribute = "fluids_source_velocity">(CurrIdx, Valid, ParticleVel);
        ParticleVel = mul(float4(ParticleVel, 0.), WorldToLocal).xyz * VelocityMult;
        ParticleReader.GetColorByIndex<Attribute="fluids_source_color">(CurrIdx, Valid, ParticleColor);
        float3 TextureGridLocalPos = CellGridLocalPos - ParticleGridLocalPos - ParticleGridLocalRestPos;
        TextureGridLocalPos = NiagaraQuatRotateVector(MeshOrientation, TextureGridLocalPos);
        float Weight = 1. - smoothstep(0, ParticleRadius+3*dx, Dist);
        TextureCoordOut += mul(float4(TextureGridLocalPos, 1.), LocalToUnit).xyz * Weight;
        ColorOut += ParticleColor * Weight;
        TotalWeight += Weight;
        float CurrDist = clamp((Dist - ParticleRadius) / dx, -3, 3);
        DistanceOut = min(DistanceOut, CurrDist);
        NumOverlapParticles++;
        if (CompositingMethod == 0)
            DensityOut += ParticleDensity;
            TemperatureOut += ParticleTemperature;
            VelocityOut += ParticleVel;
        else if (CompositingMethod == 1)
            DensityOut = max(DensityOut, ParticleDensity);
            TemperatureOut = max(TemperatureOut, ParticleTemperature);
            if (dot(ParticleVel, ParticleVel) > dot(VelocityOut, VelocityOut))
                VelocityOut = ParticleVel;
//    TextureCoordOut = float3(0,0,0);
   // DistanceOut = 1000;
    TextureCoordOut /= TotalWeight;
    ColorOut /= TotalWeight;
 EdG{_
// Shader generated by Niagara HLSL Translator
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float4 RasterizedColor;
float RasterizedDensity;
float RasterizedDistance;
float RasterizedTemperature;
float3 RasterizedTextureCoord;
float3 RasterizedVelocity;
FParamMap0_OUTPUT_VAR_Module Module;
int CompositingMethod;
float DensityMult;
float dx;
bool IsLocalSpace;
float4x4 LocalToUnit;
float RadiusScale;
float TemperatureMult;
float4x4 UnitToLocal;
float VelocityMult;
float VelocityRadiusMult;
float4x4 WorldToLocal;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Module Module;
FParamMap0_OUTPUT_VAR OUTPUT_VAR;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void GetRenderTargetSize_Module_RT(int In_InstanceData, out int Out_Width, out int Out_Height, out int Out_Depth);
void ExecToIndex_Module_RT(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_(int In_Width, int In_Height, int In_Depth, int In_IndexX, int In_IndexY, int In_IndexZ, out bool Out_ret);
void ExecToUnit_Module_RT(int In_InstanceData, out float3 Out_Unit);
void GetNumParticles_Module_ParticleReader(int In_InstanceData, out int Out_NumParticles);
void GetVectorByIndex_Module_ParticleReader_AttributePosition(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetFloatByIndex_Module_ParticleReader_Attributefluids_source_radius(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Module_ParticleReader_AttributeRestPosition(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetQuaternionByIndex_Module_ParticleReader_AttributeMeshOrientation(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void GetFloatByIndex_Module_ParticleReader_Attributefluids_source_density(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetFloatByIndex_Module_ParticleReader_Attributefluids_source_temperature(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Module_ParticleReader_Attributefluids_source_velocity(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetColorByIndex_Module_ParticleReader_Attributefluids_source_color(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_(float3 In_CellGridLocalPos, float In_VelocityMult, float In_DensityMult, int In_NumParticles, float4x4 In_WorldToLocal, float In_RadiusScale, float In_TemperatureMult, float In_VelocityRadiusMult, int In_CompositingMethod, float4x4 In_LocalToUnit, float In_dx, float3 In_UnitCoord, out float Out_DensityOut, out float3 Out_VelocityOut, out float Out_TemperatureOut, out float3 Out_TextureCoordOut, out float Out_DistanceOut, out float4 Out_ColorOut);
float GetSpawnInterpolation();
// included from ../../Plugins/FX/Niagara/Shaders/Private/NiagaraCommon.ush
// Copyright Epic Games, Inc. All Rights Reserved.
float x2 = Q.x + Q.x;  float y2 = Q.y + Q.y;  float z2 = Q.z + Q.z;
float xx = Q.x * x2;   float xy = Q.x * y2;   float xz = Q.x * z2;
float yy = Q.y * y2;   float yz = Q.y * z2;   float zz = Q.z * z2;
float wx = Q.w * x2;   float wy = Q.w * y2;   float wz = Q.w * z2;
return Mat;
0.0f, 0.0f, S.z);
float3x3 ScaleRot = mul(ScaleMat, R);
T, 1.0f);
return MakeLWCMatrix(LWCGetTile(T), NiagaraComposeTransformMatrix(S, R, T.Offset));
0.0f, 0.0f, 1.0f / S.z);
float3x3 InvRotScale = mul(transpose(R), InvScaleMat);
-T, 1.0f);
return mul(InvTransMat, InvRotScale44);
return MakeLWCInverseMatrix(LWCGetTile(T), NiagaraComposeInvTransformMatrix(S, R, T.Offset));
float W = dot(A, B);
float4 Quat;
   A.z * B.x - A.x * B.z,
   A.x * B.y - A.y * B.x,
   W);
W = 0.f;
: float4(0.f, -A.z, A.y, W);
return NiagaraQuatTo3x3(Quat);
const float RawCosom = dot(Quat1, Quat2);
const float Cosom = abs(RawCosom);
float Scale0, Scale1;
const float Omega = acos(Cosom);
const float InvSin = 1.f / sin(Omega);
Scale0 = sin((1.f - Slerp) * Omega) * InvSin;
Scale1 = sin(Slerp * Omega) * InvSin;
Scale0 = 1.0f - Slerp;
Scale1 = Slerp;
Scale1 = RawCosom >= 0.0f ? Scale1 : -Scale1;
return (Scale0 * Quat1) + (Scale1 * Quat2);
float4 Rc = Quat * float4(-1, -1, -1, 1);
return NiagaraQuatMul(Quat, NiagaraQuatMul(float4(Vector, 0), Rc)).xyz;
In_IndexX < In_Width - 1 && In_IndexY < In_Height - 1 && In_IndexZ < In_Depth - 1;
Out_DensityOut = 0;
Out_VelocityOut = 0;
Out_TemperatureOut = 0;
Out_TextureCoordOut = 0;
Out_DistanceOut = 1000000;
Out_ColorOut = float4(0,0,0,0);
for (int CurrIdx = 0; CurrIdx < In_NumParticles; ++CurrIdx)
GetVectorByIndex_Module_ParticleReader_AttributePosition(2, CurrIdx, Valid, ParticlePos);
float3 ParticleGridLocalPos = mul(float4(ParticlePos, 1.), In_WorldToLocal).xyz;
GetFloatByIndex_Module_ParticleReader_Attributefluids_source_radius(2, CurrIdx, Valid, Radius);
float Dist = length(In_CellGridLocalPos - ParticleGridLocalPos);
float ParticleRadius = Radius * In_RadiusScale;
        GetVectorByIndex_Module_ParticleReader_AttributeRestPosition(2, CurrIdx, Valid, ParticleRestPos);
float3 ParticleGridLocalRestPos = mul(float4(ParticleRestPos, 1.), In_WorldToLocal).xyz;
        GetQuaternionByIndex_Module_ParticleReader_AttributeMeshOrientation(2, CurrIdx, Valid, MeshOrientation);
        GetFloatByIndex_Module_ParticleReader_Attributefluids_source_density(2, CurrIdx, Valid, ParticleDensity);
        ParticleDensity *= In_DensityMult;
        GetFloatByIndex_Module_ParticleReader_Attributefluids_source_temperature(2, CurrIdx, Valid, ParticleTemperature);
        ParticleTemperature *= In_TemperatureMult;
        GetVectorByIndex_Module_ParticleReader_Attributefluids_source_velocity(2, CurrIdx, Valid, ParticleVel);
        ParticleVel = mul(float4(ParticleVel, 0.), In_WorldToLocal).xyz * In_VelocityMult;
        GetColorByIndex_Module_ParticleReader_Attributefluids_source_color(2, CurrIdx, Valid, ParticleColor);
        float3 TextureGridLocalPos = In_CellGridLocalPos - ParticleGridLocalPos - ParticleGridLocalRestPos;
        float Weight = 1. - smoothstep(0, ParticleRadius+3*In_dx, Dist);
        Out_TextureCoordOut += mul(float4(TextureGridLocalPos, 1.), In_LocalToUnit).xyz * Weight;
        Out_ColorOut += ParticleColor * Weight;
        float CurrDist = clamp((Dist - ParticleRadius) / In_dx, -3, 3);
        Out_DistanceOut = min(Out_DistanceOut, CurrDist);
        if (In_CompositingMethod == 0)
            Out_DensityOut += ParticleDensity;
            Out_TemperatureOut += ParticleTemperature;
            Out_VelocityOut += ParticleVel;
        else if (In_CompositingMethod == 1)
            Out_DensityOut = max(Out_DensityOut, ParticleDensity);
            Out_TemperatureOut = max(Out_TemperatureOut, ParticleTemperature);
            if (dot(ParticleVel, ParticleVel) > dot(Out_VelocityOut, Out_VelocityOut))
                Out_VelocityOut = ParticleVel;
    Out_TextureCoordOut /= TotalWeight;
    Out_ColorOut /= TotalWeight;
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**Grid3D_Gas_GatherParticleSource*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
int GetRenderTargetSize_Module_RTOutput_Width;
int GetRenderTargetSize_Module_RTOutput_Height;
int GetRenderTargetSize_Module_RTOutput_Depth;
GetRenderTargetSize_Module_RT(0, GetRenderTargetSize_Module_RTOutput_Width, GetRenderTargetSize_Module_RTOutput_Height, GetRenderTargetSize_Module_RTOutput_Depth);
int ExecToIndex_Module_RTOutput_IndexX;
int ExecToIndex_Module_RTOutput_IndexY;
int ExecToIndex_Module_RTOutput_IndexZ;
ExecToIndex_Module_RT(0, ExecToIndex_Module_RTOutput_IndexX, ExecToIndex_Module_RTOutput_IndexY, ExecToIndex_Module_RTOutput_IndexZ);
bool CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_Output_ret;
CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_(GetRenderTargetSize_Module_RTOutput_Width, GetRenderTargetSize_Module_RTOutput_Height, GetRenderTargetSize_Module_RTOutput_Depth, ExecToIndex_Module_RTOutput_IndexX, ExecToIndex_Module_RTOutput_IndexY, ExecToIndex_Module_RTOutput_IndexZ, CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_Output_ret);
float3 ExecToUnit_Module_RTOutput_Unit;
ExecToUnit_Module_RT(0, ExecToUnit_Module_RTOutput_Unit);
float3 Result = mul(float4(ExecToUnit_Module_RTOutput_Unit,1.0),Context.Map.Module.UnitToLocal).xyz;
int GetNumParticles_Module_ParticleReaderOutput_NumParticles;
GetNumParticles_Module_ParticleReader(2, GetNumParticles_Module_ParticleReaderOutput_NumParticles);
float4 Constant = float4(1,0,0,0);
float4 Constant1 = float4(0,1,0,0);
float4 Constant2 = float4(0,0,1,0);
float4 Constant3 = float4(0,0,0,1);
float4x4 Output1;
Output1[0] = Constant;
Output1[1] = Constant1;
Output1[2] = Constant2;
Output1[3] = Constant3;
float4x4 Constant4 = (float4x4)0;
float4x4 NiagaraMatrix_SelectResult = Constant4;
NiagaraMatrix_SelectResult = Output1;
NiagaraMatrix_SelectResult = Context.Map.Module.WorldToLocal;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_DensityOut;
float3 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_VelocityOut;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_TemperatureOut;
float3 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_TextureCoordOut;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_DistanceOut;
float4 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_ColorOut;
CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_(Result, Context.Map.Module.VelocityMult, Context.Map.Module.DensityMult, GetNumParticles_Module_ParticleReaderOutput_NumParticles, NiagaraMatrix_SelectResult, Context.Map.Module.RadiusScale, Context.Map.Module.TemperatureMult, Context.Map.Module.VelocityRadiusMult, Context.Map.Module.CompositingMethod, Context.Map.Module.LocalToUnit, Context.Map.Module.dx, ExecToUnit_Module_RTOutput_Unit, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_DensityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_VelocityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_TemperatureOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_TextureCoordOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_DistanceOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_ColorOut);
float Constant5 = 0;
float3 Constant6 = float3(0,0,0);
float Constant7 = 0;
float3 Constant8 = float3(0,0,0);
float Constant9 = 10000;
float4 Constant10 = float4(1,1,1,1);
float Constant11 = (0.0);
float NiagaraFloat_SelectResult1 = Constant11;
float3 Constant12 = float3(0.0, 0.0, 0.0);
float3 Vector3f_SelectResult1 = Constant12;
float Constant13 = (0.0);
float NiagaraFloat001_SelectResult1 = Constant13;
float3 Constant14 = float3(0.0, 0.0, 0.0);
float3 Vector3f001_SelectResult1 = Constant14;
float Constant15 = (0.0);
float NiagaraFloat002_SelectResult1 = Constant15;
float4 Constant16 = float4(1.0, 1.0, 1.0, 1.0);
float4 LinearColor_SelectResult1 = Constant16;
NiagaraFloat_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_DensityOut;
Vector3f_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_VelocityOut;
NiagaraFloat001_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_TemperatureOut;
Vector3f001_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_TextureCoordOut;
NiagaraFloat002_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_DistanceOut;
LinearColor_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Module_ParticleReader_Func_Output_ColorOut;
NiagaraFloat_SelectResult1 = Constant5;
Vector3f_SelectResult1 = Constant6;
NiagaraFloat001_SelectResult1 = Constant7;
Vector3f001_SelectResult1 = Constant8;
NiagaraFloat002_SelectResult1 = Constant9;
LinearColor_SelectResult1 = Constant10;
Context.Map.OUTPUT_VAR.Module.RasterizedDensity = NiagaraFloat_SelectResult1;
Context.Map.OUTPUT_VAR.Module.RasterizedVelocity = Vector3f_SelectResult1;
Context.Map.OUTPUT_VAR.Module.RasterizedTemperature = NiagaraFloat001_SelectResult1;
Context.Map.OUTPUT_VAR.Module.RasterizedTextureCoord = Vector3f001_SelectResult1;
Context.Map.OUTPUT_VAR.Module.RasterizedDistance = NiagaraFloat002_SelectResult1;
Context.Map.OUTPUT_VAR.Module.RasterizedColor = LinearColor_SelectResult1;
ExitStatScope(/**Grid3D_Gas_GatherParticleSource*/);
EnterStatScope(1 /**Grid3D_Gas_GatherParticleSource_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = -1;
EnterStatScope(2 /**Grid3D_Gas_GatherParticleSource_MapMain*/);
Simulate(Context);
ExitStatScope(/**Grid3D_Gas_GatherParticleSource_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Module.CompositingMethod);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Module.DensityMult);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Module.dx);
OutputDataBool(0, 1, TmpWriteIndex, Context.Map.Module.IsLocalSpace);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Module.LocalToUnit[0][0]);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Module.LocalToUnit[0][1]);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Module.LocalToUnit[0][2]);
OutputDataFloat(0, 5, TmpWriteIndex, Context.Map.Module.LocalToUnit[0][3]);
OutputDataFloat(0, 6, TmpWriteIndex, Context.Map.Module.LocalToUnit[1][0]);
OutputDataFloat(0, 7, TmpWriteIndex, Context.Map.Module.LocalToUnit[1][1]);
OutputDataFloat(0, 8, TmpWriteIndex, Context.Map.Module.LocalToUnit[1][2]);
OutputDataFloat(0, 9, TmpWriteIndex, Context.Map.Module.LocalToUnit[1][3]);
OutputDataFloat(0, 10, TmpWriteIndex, Context.Map.Module.LocalToUnit[2][0]);
OutputDataFloat(0, 11, TmpWriteIndex, Context.Map.Module.LocalToUnit[2][1]);
OutputDataFloat(0, 12, TmpWriteIndex, Context.Map.Module.LocalToUnit[2][2]);
OutputDataFloat(0, 13, TmpWriteIndex, Context.Map.Module.LocalToUnit[2][3]);
OutputDataFloat(0, 14, TmpWriteIndex, Context.Map.Module.LocalToUnit[3][0]);
OutputDataFloat(0, 15, TmpWriteIndex, Context.Map.Module.LocalToUnit[3][1]);
OutputDataFloat(0, 16, TmpWriteIndex, Context.Map.Module.LocalToUnit[3][2]);
OutputDataFloat(0, 17, TmpWriteIndex, Context.Map.Module.LocalToUnit[3][3]);
OutputDataFloat(0, 18, TmpWriteIndex, Context.Map.Module.RadiusScale);
OutputDataFloat(0, 19, TmpWriteIndex, Context.Map.Module.TemperatureMult);
OutputDataFloat(0, 20, TmpWriteIndex, Context.Map.Module.UnitToLocal[0][0]);
OutputDataFloat(0, 21, TmpWriteIndex, Context.Map.Module.UnitToLocal[0][1]);
OutputDataFloat(0, 22, TmpWriteIndex, Context.Map.Module.UnitToLocal[0][2]);
OutputDataFloat(0, 23, TmpWriteIndex, Context.Map.Module.UnitToLocal[0][3]);
OutputDataFloat(0, 24, TmpWriteIndex, Context.Map.Module.UnitToLocal[1][0]);
OutputDataFloat(0, 25, TmpWriteIndex, Context.Map.Module.UnitToLocal[1][1]);
OutputDataFloat(0, 26, TmpWriteIndex, Context.Map.Module.UnitToLocal[1][2]);
OutputDataFloat(0, 27, TmpWriteIndex, Context.Map.Module.UnitToLocal[1][3]);
OutputDataFloat(0, 28, TmpWriteIndex, Context.Map.Module.UnitToLocal[2][0]);
OutputDataFloat(0, 29, TmpWriteIndex, Context.Map.Module.UnitToLocal[2][1]);
OutputDataFloat(0, 30, TmpWriteIndex, Context.Map.Module.UnitToLocal[2][2]);
OutputDataFloat(0, 31, TmpWriteIndex, Context.Map.Module.UnitToLocal[2][3]);
OutputDataFloat(0, 32, TmpWriteIndex, Context.Map.Module.UnitToLocal[3][0]);
OutputDataFloat(0, 33, TmpWriteIndex, Context.Map.Module.UnitToLocal[3][1]);
OutputDataFloat(0, 34, TmpWriteIndex, Context.Map.Module.UnitToLocal[3][2]);
OutputDataFloat(0, 35, TmpWriteIndex, Context.Map.Module.UnitToLocal[3][3]);
OutputDataFloat(0, 36, TmpWriteIndex, Context.Map.Module.VelocityMult);
OutputDataFloat(0, 37, TmpWriteIndex, Context.Map.Module.VelocityRadiusMult);
OutputDataFloat(0, 38, TmpWriteIndex, Context.Map.Module.WorldToLocal[0][0]);
OutputDataFloat(0, 39, TmpWriteIndex, Context.Map.Module.WorldToLocal[0][1]);
OutputDataFloat(0, 40, TmpWriteIndex, Context.Map.Module.WorldToLocal[0][2]);
OutputDataFloat(0, 41, TmpWriteIndex, Context.Map.Module.WorldToLocal[0][3]);
OutputDataFloat(0, 42, TmpWriteIndex, Context.Map.Module.WorldToLocal[1][0]);
OutputDataFloat(0, 43, TmpWriteIndex, Context.Map.Module.WorldToLocal[1][1]);
OutputDataFloat(0, 44, TmpWriteIndex, Context.Map.Module.WorldToLocal[1][2]);
OutputDataFloat(0, 45, TmpWriteIndex, Context.Map.Module.WorldToLocal[1][3]);
OutputDataFloat(0, 46, TmpWriteIndex, Context.Map.Module.WorldToLocal[2][0]);
OutputDataFloat(0, 47, TmpWriteIndex, Context.Map.Module.WorldToLocal[2][1]);
OutputDataFloat(0, 48, TmpWriteIndex, Context.Map.Module.WorldToLocal[2][2]);
OutputDataFloat(0, 49, TmpWriteIndex, Context.Map.Module.WorldToLocal[2][3]);
OutputDataFloat(0, 50, TmpWriteIndex, Context.Map.Module.WorldToLocal[3][0]);
OutputDataFloat(0, 51, TmpWriteIndex, Context.Map.Module.WorldToLocal[3][1]);
OutputDataFloat(0, 52, TmpWriteIndex, Context.Map.Module.WorldToLocal[3][2]);
OutputDataFloat(0, 53, TmpWriteIndex, Context.Map.Module.WorldToLocal[3][3]);
ExitStatScope(/**Grid3D_Gas_GatherParticleSource_Main*/);

