:na^;Z
float BoundingSphereRadius = length(.5 * Scale);
SpriteWidth = 2. * BoundingSphereRadius;
float3 CameraToGridCenter = GridCenterPos - CameraPos;
float DistToGridCenter = length(CameraToGridCenter);
    SpritePos = GridCenterPos;
    float3 RayDir = CameraToGridCenter / DistToGridCenter;
    //SpritePos = GridCenterPos - BoundingSphereRadius * RayDir;
 Zz^X!tH
 Zz^X!t
#Nf;uN
// Shader generated by Niagara HLSL Translator
// SimStage[0] = ParticleSpawnUpdate
// SimStage[1] = Post Sim
// Compile Data> Static Variables Input: 
// Compile Data> PinToConstantValues Input: 
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float4x4 Emitter_UnitToLocal;
float4x4 Emitter_WorldToLocal;
bool Emitter_IsLocalSpace;
float4x4 Emitter_LocalToUnit;
float Emitter_dx;
int UniqueID;
float4 RasterizedColor;
float RasterizedDensity;
float RasterizedDistance;
float RasterizedTemperature;
float3 RasterizedTextureCoord;
float3 RasterizedVelocity;
FParamMap0_OUTPUT_VAR_Grid3D_Gas_GatherParticleSource Grid3D_Gas_GatherParticleSource;
int Channel;
float3 VECTOR_VAR;
float4 LinearColor;
float4 Value;
FParamMap0_Local_Grid3D_SetRTValues Grid3D_SetRTValues;
FParamMap0_Local_Grid3D_SetRTValues001 Grid3D_SetRTValues001;
float Alpha;
float Blue;
float Green;
float Red;
int CompositingMethod;
float dx;
bool IsLocalSpace;
float4x4 LocalToUnit;
float4x4 UnitToLocal;
float4x4 WorldToLocal;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
FParamMap0_Array Array;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Grid3D_Gas_GatherParticleSource Grid3D_Gas_GatherParticleSource;
FParamMap0_Grid3D_SetRTValues Grid3D_SetRTValues;
FParamMap0_Grid3D_SetRTValues001 Grid3D_SetRTValues001;
FParamMap0_Local Local;
FParamMap0_MakeFloatFromLinearColor MakeFloatFromLinearColor;
FParamMap0_MakeFloatFromLinearColor001 MakeFloatFromLinearColor001;
FParamMap0_MakeFloatFromLinearColor002 MakeFloatFromLinearColor002;
FParamMap0_MakeFloatFromLinearColor003 MakeFloatFromLinearColor003;
FParamMap0_MakeFloatFromVector MakeFloatFromVector;
FParamMap0_MakeFloatFromVector001 MakeFloatFromVector001;
FParamMap0_MakeFloatFromVector002 MakeFloatFromVector002;
FParamMap0_OUTPUT_VAR OUTPUT_VAR;
FParamMap0_Particles Particles;
#if ((SimulationStageIndex == 0)) // MapSpawn
FParamMap0 MapSpawn;
#endif // MapSpawn
#if ((SimulationStageIndex == 0)) // MapUpdate
FParamMap0 MapUpdate;
#endif // MapUpdate
#if ((SimulationStageIndex == 1)) // MapSimStage1_PostSim
FParamMap0 MapSimStage1_PostSim;
#endif // MapSimStage1_PostSim
static float HackSpawnInterp = 1.0;
void GetRenderTargetSize_Emitter_SimRT(out int Out_Width, out int Out_Height, out int Out_Depth);
void ExecToIndex_Emitter_SimRT(out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_(int In_Width, int In_Height, int In_Depth, int In_IndexX, int In_IndexY, int In_IndexZ, out bool Out_ret);
void ExecToUnit_Emitter_SimRT(out float3 Out_Unit);
void GetNumParticles_Emitter_Reader(out int Out_NumParticles);
void GetVectorByIndex_Emitter_Reader_AttributePosition(int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_radius(int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Emitter_Reader_AttributeRestPosition(int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetQuaternionByIndex_Emitter_Reader_AttributeMeshOrientation(int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_density(int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_temperature(int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Emitter_Reader_Attributefluids_source_velocity(int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetColorByIndex_Emitter_Reader_Attributefluids_source_color(int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_(float3 In_CellGridLocalPos, float In_VelocityMult, float In_DensityMult, int In_NumParticles, float4x4 In_WorldToLocal, float In_RadiusScale, float In_TemperatureMult, float In_VelocityRadiusMult, int In_CompositingMethod, float4x4 In_LocalToUnit, float In_dx, out float Out_DensityOut, out float3 Out_VelocityOut, out float Out_TemperatureOut, out float3 Out_TextureCoordOut, out float Out_DistanceOut, out float4 Out_ColorOut);
void Grid3D_Gas_GatherParticleSource_Emitter_Func_(inout FSimulationContext Context);
void NiagaraScript_510_Particle_Func_(float3 In_VECTOR_VAR, int In_TargetChannel, out float Out_Float, inout FSimulationContext Context);
void MakeFloatFromVector_Emitter_Func_(out float Out_Float, inout FSimulationContext Context);
void MakeFloatFromVector001_Emitter_Func_(out float Out_Float, inout FSimulationContext Context);
void MakeFloatFromVector002_Emitter_Func_(out float Out_Float, inout FSimulationContext Context);
void SetRenderTargetValue_Emitter_SimRT_UEImpureCall(bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
void Grid3D_SetRTValues_Emitter_Func_(inout FSimulationContext Context);
void NiagaraScript_512_Particle_Func_(float4 In_FLOAT4_VAR, int In_TargetChannel, out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor001_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor002_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor003_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void ExecToIndex_Emitter_AttrRT(out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void SetRenderTargetValue_Emitter_AttrRT_UEImpureCall(bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
void Grid3D_SetRTValues001_Emitter_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
// included from ../../Plugins/FX/Niagara/Shaders/Private/NiagaraCommon.ush
// Copyright Epic Games, Inc. All Rights Reserved.
float x2 = Q.x + Q.x;  float y2 = Q.y + Q.y;  float z2 = Q.z + Q.z;
float xx = Q.x * x2;   float xy = Q.x * y2;   float xz = Q.x * z2;
float yy = Q.y * y2;   float yz = Q.y * z2;   float zz = Q.z * z2;
float wx = Q.w * x2;   float wy = Q.w * y2;   float wz = Q.w * z2;
return Mat;
0.0f, 0.0f, S.z);
float3x3 ScaleRot = mul(ScaleMat, R);
T, 1.0f);
return MakeLWCMatrix(LWCGetTile(T), NiagaraComposeTransformMatrix(S, R, T.Offset));
0.0f, 0.0f, 1.0f / S.z);
float3x3 InvRotScale = mul(transpose(R), InvScaleMat);
-T, 1.0f);
return mul(InvTransMat, InvRotScale44);
return MakeLWCInverseMatrix(LWCGetTile(T), NiagaraComposeInvTransformMatrix(S, R, T.Offset));
float W = dot(A, B);
float4 Quat;
   A.z * B.x - A.x * B.z,
   A.x * B.y - A.y * B.x,
   W);
W = 0.f;
: float4(0.f, -A.z, A.y, W);
return NiagaraQuatTo3x3(Quat);
const float RawCosom = dot(Quat1, Quat2);
const float Cosom = abs(RawCosom);
float Scale0, Scale1;
const float Omega = acos(Cosom);
const float InvSin = 1.f / sin(Omega);
Scale0 = sin((1.f - Slerp) * Omega) * InvSin;
Scale1 = sin(Slerp * Omega) * InvSin;
Scale0 = 1.0f - Slerp;
Scale1 = Slerp;
Scale1 = RawCosom >= 0.0f ? Scale1 : -Scale1;
return (Scale0 * Quat1) + (Scale1 * Quat2);
float4 Rc = Quat * float4(-1, -1, -1, 1);
return NiagaraQuatMul(Quat, NiagaraQuatMul(float4(Vector, 0), Rc)).xyz;
In_IndexX < In_Width - 1 && In_IndexY < In_Height - 1 && In_IndexZ < In_Depth - 1;
Out_DensityOut = 0;
Out_VelocityOut = 0;
Out_TemperatureOut = 0;
Out_TextureCoordOut = 0;
Out_DistanceOut = 1000000;
Out_ColorOut = float4(0,0,0,0);
float TextureWeight = 0;
bool Valid;
for (int CurrIdx = 0; CurrIdx < In_NumParticles; ++CurrIdx)
float3 ParticlePos;
GetVectorByIndex_Emitter_Reader_AttributePosition(CurrIdx, Valid, ParticlePos);
float3 ParticleGridLocalPos = mul(float4(ParticlePos, 1.), In_WorldToLocal).xyz;
float Radius = 0.0;
GetFloatByIndex_Emitter_Reader_Attributefluids_source_radius(CurrIdx, Valid, Radius);
float Dist = length(In_CellGridLocalPos - ParticleGridLocalPos);
float ParticleRadius = Radius * In_RadiusScale;
    float ParticleDensity = 0;
    float ParticleTemperature = 0;
    float3 ParticleVel = float3(0, 0, 0);
    float ParticleDivergence = 0;
    float4 ParticleColor = 0;
        float3 ParticleRestPos;
        GetVectorByIndex_Emitter_Reader_AttributeRestPosition(CurrIdx, Valid, ParticleRestPos);
float3 ParticleGridLocalRestPos = mul(float4(ParticleRestPos, 1.), In_WorldToLocal).xyz;
        float4 MeshOrientation;
        GetQuaternionByIndex_Emitter_Reader_AttributeMeshOrientation(CurrIdx, Valid, MeshOrientation);
        GetFloatByIndex_Emitter_Reader_Attributefluids_source_density(CurrIdx, Valid, ParticleDensity);
        ParticleDensity *= In_DensityMult;
        GetFloatByIndex_Emitter_Reader_Attributefluids_source_temperature(CurrIdx, Valid, ParticleTemperature);
        ParticleTemperature *= In_TemperatureMult;
        GetVectorByIndex_Emitter_Reader_Attributefluids_source_velocity(CurrIdx, Valid, ParticleVel);
        ParticleVel = mul(float4(ParticleVel, 0.), In_WorldToLocal).xyz * In_VelocityMult;
        GetColorByIndex_Emitter_Reader_Attributefluids_source_color(CurrIdx, Valid, ParticleColor);
        float3 TextureGridLocalPos = In_CellGridLocalPos - ParticleGridLocalPos - ParticleGridLocalRestPos;
        TextureGridLocalPos = NiagaraQuatRotateVector(MeshOrientation, TextureGridLocalPos);
        float Weight = 1. - smoothstep(0, ParticleRadius+1.5*In_dx, Dist);
        Out_TextureCoordOut += mul(float4(TextureGridLocalPos, 1.), In_LocalToUnit).xyz * Weight;
        TextureWeight += Weight;
        Out_DistanceOut = min(Out_DistanceOut, Dist - ParticleRadius) / In_dx;
        if (In_CompositingMethod == 0)
            Out_DensityOut += ParticleDensity;
            Out_TemperatureOut += ParticleTemperature;
            Out_VelocityOut += ParticleVel;
            Out_ColorOut += ParticleColor;
        else if (In_CompositingMethod == 1)
            Out_DensityOut = max(Out_DensityOut, ParticleDensity);
            Out_TemperatureOut = max(Out_TemperatureOut, ParticleTemperature);
            if (dot(ParticleVel, ParticleVel) > dot(Out_VelocityOut, Out_VelocityOut))
                Out_VelocityOut = ParticleVel;
            Out_ColorOut = max(Out_ColorOut, ParticleColor);
    Out_TextureCoordOut /= TextureWeight;
#endif //GPU_SIMULATION
float Constant6 = 1;
float Constant7 = 1;
float Constant8 = 1;
float Constant9 = 1;
float Constant10 = 1;
int GetRenderTargetSize_Emitter_SimRTOutput_Width;
int GetRenderTargetSize_Emitter_SimRTOutput_Height;
int GetRenderTargetSize_Emitter_SimRTOutput_Depth;
GetRenderTargetSize_Emitter_SimRT(GetRenderTargetSize_Emitter_SimRTOutput_Width, GetRenderTargetSize_Emitter_SimRTOutput_Height, GetRenderTargetSize_Emitter_SimRTOutput_Depth);
int ExecToIndex_Emitter_SimRTOutput_IndexX;
int ExecToIndex_Emitter_SimRTOutput_IndexY;
int ExecToIndex_Emitter_SimRTOutput_IndexZ;
ExecToIndex_Emitter_SimRT(ExecToIndex_Emitter_SimRTOutput_IndexX, ExecToIndex_Emitter_SimRTOutput_IndexY, ExecToIndex_Emitter_SimRTOutput_IndexZ);
bool CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_Output_ret;
CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_(GetRenderTargetSize_Emitter_SimRTOutput_Width, GetRenderTargetSize_Emitter_SimRTOutput_Height, GetRenderTargetSize_Emitter_SimRTOutput_Depth, ExecToIndex_Emitter_SimRTOutput_IndexX, ExecToIndex_Emitter_SimRTOutput_IndexY, ExecToIndex_Emitter_SimRTOutput_IndexZ, CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_Output_ret);
float3 ExecToUnit_Emitter_SimRTOutput_Unit;
ExecToUnit_Emitter_SimRT(ExecToUnit_Emitter_SimRTOutput_Unit);
float3 Result = mul(float4(ExecToUnit_Emitter_SimRTOutput_Unit,1.0),Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.UnitToLocal).xyz;
int GetNumParticles_Emitter_ReaderOutput_NumParticles;
GetNumParticles_Emitter_Reader(GetNumParticles_Emitter_ReaderOutput_NumParticles);
float4 Constant11 = float4(1,0,0,0);
float4 Constant12 = float4(0,1,0,0);
float4 Constant13 = float4(0,0,1,0);
float4 Constant14 = float4(0,0,0,1);
float4x4 Output1;
Output1[0] = Constant11;
Output1[1] = Constant12;
Output1[2] = Constant13;
Output1[3] = Constant14;
float4x4 Constant15 = (float4x4)0;
float4x4 NiagaraMatrix_SelectResult = Constant15;
NiagaraMatrix_SelectResult = Output1;
NiagaraMatrix_SelectResult = Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.WorldToLocal;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DensityOut;
float3 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_VelocityOut;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TemperatureOut;
float3 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TextureCoordOut;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DistanceOut;
float4 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_ColorOut;
CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_(Result, Constant6, Constant7, GetNumParticles_Emitter_ReaderOutput_NumParticles, NiagaraMatrix_SelectResult, Constant8, Constant9, Constant10, Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.CompositingMethod, Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.LocalToUnit, Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.dx, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DensityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_VelocityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TemperatureOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TextureCoordOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DistanceOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_ColorOut);
float Constant16 = 0;
float3 Constant17 = float3(0,0,0);
float Constant18 = 0;
float3 Constant19 = float3(0,0,0);
float Constant20 = 10000;
float4 Constant21 = float4(1,1,1,1);
float Constant22 = (0.0);
float NiagaraFloat_SelectResult1 = Constant22;
float3 Constant23 = float3(0.0, 0.0, 0.0);
float3 Vector3f_SelectResult1 = Constant23;
float Constant24 = (0.0);
float NiagaraFloat001_SelectResult1 = Constant24;
float3 Constant25 = float3(0.0, 0.0, 0.0);
float3 Vector3f001_SelectResult1 = Constant25;
float Constant26 = (0.0);
float NiagaraFloat002_SelectResult1 = Constant26;
float4 Constant27 = float4(1.0, 1.0, 1.0, 1.0);
float4 LinearColor_SelectResult1 = Constant27;
NiagaraFloat_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DensityOut;
Vector3f_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_VelocityOut;
NiagaraFloat001_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TemperatureOut;
Vector3f001_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TextureCoordOut;
NiagaraFloat002_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DistanceOut;
LinearColor_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_ColorOut;
NiagaraFloat_SelectResult1 = Constant16;
Vector3f_SelectResult1 = Constant17;
NiagaraFloat001_SelectResult1 = Constant18;
Vector3f001_SelectResult1 = Constant19;
NiagaraFloat002_SelectResult1 = Constant20;
LinearColor_SelectResult1 = Constant21;
Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDensity = NiagaraFloat_SelectResult1;
Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedVelocity = Vector3f_SelectResult1;
Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTemperature = NiagaraFloat001_SelectResult1;
Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord = Vector3f001_SelectResult1;
Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDistance = NiagaraFloat002_SelectResult1;
Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor = LinearColor_SelectResult1;
float X;
float Y;
float Z;
X = In_VECTOR_VAR.x;
Y = In_VECTOR_VAR.y;
Z = In_VECTOR_VAR.z;
float Constant31 = (0.0);
float NiagaraFloat_SelectResult2 = Constant31;
NiagaraFloat_SelectResult2 = X;
NiagaraFloat_SelectResult2 = Y;
NiagaraFloat_SelectResult2 = Z;
Out_Float = NiagaraFloat_SelectResult2;
float NiagaraScript_510_Particle_Func_Output_Float;
NiagaraScript_510_Particle_Func_(Context.MapSimStage1_PostSim.MakeFloatFromVector.VECTOR_VAR, Context.MapSimStage1_PostSim.MakeFloatFromVector.Channel, NiagaraScript_510_Particle_Func_Output_Float, Context);
Out_Float = NiagaraScript_510_Particle_Func_Output_Float;
float NiagaraScript_510_Particle_Func_Output_Float1;
NiagaraScript_510_Particle_Func_(Context.MapSimStage1_PostSim.MakeFloatFromVector001.VECTOR_VAR, Context.MapSimStage1_PostSim.MakeFloatFromVector001.Channel, NiagaraScript_510_Particle_Func_Output_Float1, Context);
Out_Float = NiagaraScript_510_Particle_Func_Output_Float1;
float NiagaraScript_510_Particle_Func_Output_Float2;
NiagaraScript_510_Particle_Func_(Context.MapSimStage1_PostSim.MakeFloatFromVector002.VECTOR_VAR, Context.MapSimStage1_PostSim.MakeFloatFromVector002.Channel, NiagaraScript_510_Particle_Func_Output_Float2, Context);
Out_Float = NiagaraScript_510_Particle_Func_Output_Float2;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.Enable"
int Constant32 = 1;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.SetFromVector"
int Constant33 = 0;
float4 Output11;
Output11.r = Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Red;
Output11.g = Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Green;
Output11.b = Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Blue;
Output11.a = Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Alpha;
Context.MapSimStage1_PostSim.Local.Grid3D_SetRTValues.Value = Output11;
bool Constant34 = true;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.UseIterationGrid"
int Constant35 = 0;
int ExecToIndex_Emitter_SimRTOutput_IndexX1;
int ExecToIndex_Emitter_SimRTOutput_IndexY1;
int ExecToIndex_Emitter_SimRTOutput_IndexZ1;
ExecToIndex_Emitter_SimRT(ExecToIndex_Emitter_SimRTOutput_IndexX1, ExecToIndex_Emitter_SimRTOutput_IndexY1, ExecToIndex_Emitter_SimRTOutput_IndexZ1);
SetRenderTargetValue_Emitter_SimRT_UEImpureCall(Constant34, ExecToIndex_Emitter_SimRTOutput_IndexX1, ExecToIndex_Emitter_SimRTOutput_IndexY1, ExecToIndex_Emitter_SimRTOutput_IndexZ1, Context.MapSimStage1_PostSim.Local.Grid3D_SetRTValues.Value);
float X1;
float Y1;
float Z1;
float W;
X1 = In_FLOAT4_VAR.x;
Y1 = In_FLOAT4_VAR.y;
Z1 = In_FLOAT4_VAR.z;
W = In_FLOAT4_VAR.w;
float Constant40 = (0.0);
float NiagaraFloat_SelectResult3 = Constant40;
NiagaraFloat_SelectResult3 = X1;
NiagaraFloat_SelectResult3 = Y1;
NiagaraFloat_SelectResult3 = Z1;
NiagaraFloat_SelectResult3 = W;
Out_NewOutput = NiagaraFloat_SelectResult3;
int ENiagaraVector4_Channels;
ENiagaraVector4_Channels = Context.MapSimStage1_PostSim.MakeFloatFromLinearColor.Channel;
float NiagaraScript_512_Particle_Func_Output_NewOutput;
NiagaraScript_512_Particle_Func_(Context.MapSimStage1_PostSim.MakeFloatFromLinearColor.LinearColor, ENiagaraVector4_Channels, NiagaraScript_512_Particle_Func_Output_NewOutput, Context);
Out_NewOutput = NiagaraScript_512_Particle_Func_Output_NewOutput;
int ENiagaraVector4_Channels1;
ENiagaraVector4_Channels1 = Context.MapSimStage1_PostSim.MakeFloatFromLinearColor001.Channel;
float NiagaraScript_512_Particle_Func_Output_NewOutput1;
NiagaraScript_512_Particle_Func_(Context.MapSimStage1_PostSim.MakeFloatFromLinearColor001.LinearColor, ENiagaraVector4_Channels1, NiagaraScript_512_Particle_Func_Output_NewOutput1, Context);
Out_NewOutput = NiagaraScript_512_Particle_Func_Output_NewOutput1;
int ENiagaraVector4_Channels2;
ENiagaraVector4_Channels2 = Context.MapSimStage1_PostSim.MakeFloatFromLinearColor002.Channel;
float NiagaraScript_512_Particle_Func_Output_NewOutput2;
NiagaraScript_512_Particle_Func_(Context.MapSimStage1_PostSim.MakeFloatFromLinearColor002.LinearColor, ENiagaraVector4_Channels2, NiagaraScript_512_Particle_Func_Output_NewOutput2, Context);
Out_NewOutput = NiagaraScript_512_Particle_Func_Output_NewOutput2;
int ENiagaraVector4_Channels3;
ENiagaraVector4_Channels3 = Context.MapSimStage1_PostSim.MakeFloatFromLinearColor003.Channel;
float NiagaraScript_512_Particle_Func_Output_NewOutput3;
NiagaraScript_512_Particle_Func_(Context.MapSimStage1_PostSim.MakeFloatFromLinearColor003.LinearColor, ENiagaraVector4_Channels3, NiagaraScript_512_Particle_Func_Output_NewOutput3, Context);
Out_NewOutput = NiagaraScript_512_Particle_Func_Output_NewOutput3;
//SetConstantByStaticVariable "/Grid 3D Set RTValues 001/Map Get/Map Get->Module.Enable"
int Constant41 = 1;
//SetConstantByStaticVariable "/Grid 3D Set RTValues 001/Map Get/Map Get->Module.SetFromVector"
int Constant42 = 0;
float4 Output12;
Output12.r = Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Red;
Output12.g = Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Green;
Output12.b = Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Blue;
Output12.a = Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Alpha;
Context.MapSimStage1_PostSim.Local.Grid3D_SetRTValues001.Value = Output12;
bool Constant43 = true;
//SetConstantByStaticVariable "/Grid 3D Set RTValues 001/Map Get/Map Get->Module.UseIterationGrid"
int Constant44 = 0;
int ExecToIndex_Emitter_AttrRTOutput_IndexX;
int ExecToIndex_Emitter_AttrRTOutput_IndexY;
int ExecToIndex_Emitter_AttrRTOutput_IndexZ;
ExecToIndex_Emitter_AttrRT(ExecToIndex_Emitter_AttrRTOutput_IndexX, ExecToIndex_Emitter_AttrRTOutput_IndexY, ExecToIndex_Emitter_AttrRTOutput_IndexZ);
SetRenderTargetValue_Emitter_AttrRT_UEImpureCall(Constant43, ExecToIndex_Emitter_AttrRTOutput_IndexX, ExecToIndex_Emitter_AttrRTOutput_IndexY, ExecToIndex_Emitter_AttrRTOutput_IndexZ, Context.MapSimStage1_PostSim.Local.Grid3D_SetRTValues001.Value);
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
//Begin Spawn Script!
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
//End Spawn Script!
//Handle resetting previous values at the end of spawn so that they match outputs! (Needed for motion blur/etc)
HandlePreviousValuesForSpawn(Context);
// Begin HandleMissingDefaultValues
// End HandleMissingDefaultValues
//Begin Update Script!
RandomCounterDeterministic = 0;
//End Update Script!
//Begin Stage Script: MapSimStage1_PostSim!
int Constant = 1;
Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.UnitToLocal = Context.MapSimStage1_PostSim.Emitter.UnitToLocal;
Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.WorldToLocal = Context.MapSimStage1_PostSim.Emitter.WorldToLocal;
Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.IsLocalSpace = Context.MapSimStage1_PostSim.Emitter.IsLocalSpace;
Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.LocalToUnit = Context.MapSimStage1_PostSim.Emitter.LocalToUnit;
Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.dx = Context.MapSimStage1_PostSim.Emitter.dx;
Context.MapSimStage1_PostSim.Grid3D_Gas_GatherParticleSource.CompositingMethod = Constant;
float Constant1 = 1;
float Constant2 = 1;
float Constant3 = 1;
float Constant4 = 1;
float Constant5 = 1;
EnterStatScope(1 /**Grid3D_Gas_GatherParticleSource_Emitter_Func_*/);
Grid3D_Gas_GatherParticleSource_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_Gas_GatherParticleSource_Emitter_Func_*/);
int Constant28 = 1;
int Constant29 = 2;
Context.MapSimStage1_PostSim.MakeFloatFromVector.VECTOR_VAR = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.MapSimStage1_PostSim.MakeFloatFromVector001.VECTOR_VAR = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.MapSimStage1_PostSim.MakeFloatFromVector002.VECTOR_VAR = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.MapSimStage1_PostSim.MakeFloatFromVector001.Channel = Constant28;
Context.MapSimStage1_PostSim.MakeFloatFromVector002.Channel = Constant29;
int Constant30 = 0;
Context.MapSimStage1_PostSim.MakeFloatFromVector.Channel = Constant30;
float MakeFloatFromVector_Emitter_Func_Output_Float;
MakeFloatFromVector_Emitter_Func_(MakeFloatFromVector_Emitter_Func_Output_Float, Context);
float MakeFloatFromVector001_Emitter_Func_Output_Float;
MakeFloatFromVector001_Emitter_Func_(MakeFloatFromVector001_Emitter_Func_Output_Float, Context);
float MakeFloatFromVector002_Emitter_Func_Output_Float;
MakeFloatFromVector002_Emitter_Func_(MakeFloatFromVector002_Emitter_Func_Output_Float, Context);
Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Red = MakeFloatFromVector_Emitter_Func_Output_Float;
Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Green = MakeFloatFromVector001_Emitter_Func_Output_Float;
Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Blue = MakeFloatFromVector002_Emitter_Func_Output_Float;
Context.MapSimStage1_PostSim.Grid3D_SetRTValues.Alpha = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDistance;
EnterStatScope(2 /**Grid3D_SetRTValues_Emitter_Func_*/);
Grid3D_SetRTValues_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_SetRTValues_Emitter_Func_*/);
int Constant36 = 1;
int Constant37 = 2;
int Constant38 = 3;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor.LinearColor = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor001.LinearColor = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor002.LinearColor = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor003.LinearColor = Context.MapSimStage1_PostSim.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor001.Channel = Constant36;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor002.Channel = Constant37;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor003.Channel = Constant38;
int Constant39 = 0;
Context.MapSimStage1_PostSim.MakeFloatFromLinearColor.Channel = Constant39;
float MakeFloatFromLinearColor_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor_Emitter_Func_(MakeFloatFromLinearColor_Emitter_Func_Output_NewOutput, Context);
float MakeFloatFromLinearColor001_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor001_Emitter_Func_(MakeFloatFromLinearColor001_Emitter_Func_Output_NewOutput, Context);
float MakeFloatFromLinearColor002_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor002_Emitter_Func_(MakeFloatFromLinearColor002_Emitter_Func_Output_NewOutput, Context);
float MakeFloatFromLinearColor003_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor003_Emitter_Func_(MakeFloatFromLinearColor003_Emitter_Func_Output_NewOutput, Context);
Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Red = MakeFloatFromLinearColor_Emitter_Func_Output_NewOutput;
Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Green = MakeFloatFromLinearColor001_Emitter_Func_Output_NewOutput;
Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Blue = MakeFloatFromLinearColor002_Emitter_Func_Output_NewOutput;
Context.MapSimStage1_PostSim.Grid3D_SetRTValues001.Alpha = MakeFloatFromLinearColor003_Emitter_Func_Output_NewOutput;
EnterStatScope(3 /**Grid3D_SetRTValues001_Emitter_Func_*/);
Grid3D_SetRTValues001_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_SetRTValues001_Emitter_Func_*/);
//End Simulation Stage Script: MapSimStage1_PostSim
Emitter_SimRT_TextureSize;
Emitter_SimRT_MipLevels;
Emitter_SimRT_RWTexture;
Emitter_SimRT_Texture;
Emitter_SimRT_TextureSampler;
Emitter_SimRT_RWTexture[int3(IndexX, IndexY, IndexZ)] = Value;
Value = Emitter_SimRT_Texture.Load(int4(IndexX, IndexY, IndexZ, 0));
Value = Emitter_SimRT_Texture.Load(int4(IndexX, IndexY, IndexZ, MipLevel));
Value = Emitter_SimRT_Texture.SampleLevel(Emitter_SimRT_TextureSampler, UVW, MipLevel);
Width = Emitter_SimRT_TextureSize.x;
Height = Emitter_SimRT_TextureSize.y;
Slices = Emitter_SimRT_TextureSize.z;
OutMipLevels = Emitter_SimRT_MipLevels;
IndexX = Linear % Emitter_SimRT_TextureSize.x;
IndexY = (Linear / Emitter_SimRT_TextureSize.x) % Emitter_SimRT_TextureSize.y;
IndexZ = Linear / (Emitter_SimRT_TextureSize.x * Emitter_SimRT_TextureSize.y);
LinearToIndex_Emitter_SimRT(ExecIndex(), IndexX, IndexY, IndexZ);
int3 Texel;
ExecToIndex_Emitter_SimRT(Texel.x, Texel.y, Texel.z);
Unit.x = (float(Texel.x) + 0.5f) / float(Emitter_SimRT_TextureSize.x);
Unit.y = (float(Texel.y) + 0.5f) / float(Emitter_SimRT_TextureSize.y);
Unit.z = (float(Texel.z) + 0.5f) / float(Emitter_SimRT_TextureSize.z);
Emitter_Reader_NumSpawnedParticles;int
Emitter_Reader_SpawnedParticlesAcquireTag;uint
Emitter_Reader_InstanceCountOffset;uint
Emitter_Reader_ParticleStrideFloat;uint
Emitter_Reader_ParticleStrideInt;uint
Emitter_Reader_ParticleStrideHalf;int
Emitter_Reader_AcquireTagRegisterIndex;Buffer<int>
Emitter_Reader_SpawnedIDsBuffer;Buffer<int>
Emitter_Reader_IDToIndexTable;Buffer<float>
Emitter_Reader_InputFloatBuffer;Buffer<int>
Emitter_Reader_InputIntBuffer;Buffer<half>
Emitter_Reader_InputHalfBuffer;int4
Emitter_Reader_AttributeIndices[3];int4
Emitter_Reader_AttributeCompressed[3];
int3 Emitter_SimGrid_NumCells;
float3 Emitter_SimGrid_UnitToUV;
float3 Emitter_SimGrid_CellSize;
float3 Emitter_SimGrid_WorldBBoxSize;
Texture3D<float> Emitter_SimGrid_Grid;
RWTexture3D<float> Emitter_SimGrid_OutputGrid;
int3 Emitter_SimGrid_NumTiles;
float3 Emitter_SimGrid_OneOverNumTiles;
float3 Emitter_SimGrid_UnitClampMin;
float3 Emitter_SimGrid_UnitClampMax;
SamplerState Emitter_SimGrid_GridSampler;
int4 Emitter_SimGrid_AttributeIndices[1];
Buffer<float4> Emitter_SimGrid_PerAttributeData;
int Emitter_SimGrid_NumAttributes;
int Emitter_SimGrid_NumNamedAttributes;
int3 TotalDim = Emitter_SimGrid_NumCells * Emitter_SimGrid_NumTiles;
float3 GridPos = float3(TotalDim[0] * UVW[0] - 0.5,  TotalDim[1] * UVW[1] - 0.5, TotalDim[2] * UVW[2] - 0.5f);
int3 GridCell = floor(GridPos);
float3 delta = float3( GridPos[0] - GridCell[0], GridPos[1] - GridCell[1], GridPos[2] - GridCell[2]);
// local values
float4 F; 
// bottom face
F[0] = Emitter_SimGrid_Grid.Load( int4( GridCell[0],     GridCell[1], GridCell[2], MipLevel) );
F[1] = Emitter_SimGrid_Grid.Load( int4( GridCell[0] + 1, GridCell[1], GridCell[2], MipLevel) );
F[2] = Emitter_SimGrid_Grid.Load( int4( GridCell[0] + 1, GridCell[1] +1 , GridCell[2], MipLevel) );
F[3] = Emitter_SimGrid_Grid.Load( int4( GridCell[0],     GridCell[1] +1 , GridCell[2], MipLevel) );
// bottom value
float BV = (1.-delta.y) * (F[0] *(1.-delta.x) + F[1]*(delta.x)) + delta.y * (F[3]*(1.-delta.x) + F[2]*delta.x);
// top face
F[0] = Emitter_SimGrid_Grid.Load( int4( GridCell[0],     GridCell[1],     GridCell[2] + 1, MipLevel) );
F[1] = Emitter_SimGrid_Grid.Load( int4( GridCell[0] + 1, GridCell[1],     GridCell[2] + 1, MipLevel) );
F[2] = Emitter_SimGrid_Grid.Load( int4( GridCell[0] + 1, GridCell[1] +1 , GridCell[2] + 1, MipLevel) );
F[3] = Emitter_SimGrid_Grid.Load( int4( GridCell[0],     GridCell[1] +1 , GridCell[2] + 1, MipLevel) );
// top value
float TV = (1.-delta.y) * (F[0] *(1.-delta.x) + F[1]*(delta.x)) + delta.y * (F[3]*(1.-delta.x) + F[2]*delta.x);
// interp between bottom and top
return TV * delta.z + BV * (1.-delta.z);
// identify the lower-left-hand corner of the cell
int3 LocalCell = GridCell % Emitter_SimGrid_NumCells;
const int3 MaxCell = Emitter_SimGrid_NumCells - int3(2,2,2);
// revert to trilinear hardware sampling at the boundary cells.
return Emitter_SimGrid_Grid.SampleLevel(Sampler, UVW, MipLevel);
// sample point offset from lower left
float t = 1. + delta.x;
float u = 1. + delta.y;
float v = 1. + delta.z;
float4x1 DataInZ;
float1 minv = 3.402823466e+38;
float1 maxv = -3.402823466e+38;
for (int zk = 0; zk < 4; zk++)
int plane = GridCell[2] + zk -1;
float4x1  DataInY;
for (int yj = 0; yj < 4; yj++)
float4x1 DataInX;
int row = GridCell[1] + yj - 1;
for(int xi = 0; xi < 4; xi++)
int col = GridCell[0] + xi - 1;
DataInX[xi] = Emitter_SimGrid_Grid.Load(int4(col, row, plane, MipLevel)); 
minv = min(DataInX[xi], minv);
maxv = max(DataInX[xi], maxv);
// coefficients
float1 Cx0 =   6.f * DataInX[0];
float1 Cx1 = -11.f * DataInX[0] + 18.f * DataInX[1] - 9.f * DataInX[2] + 2.f * DataInX[3];
float1 Cx2 =   6.f * DataInX[0] - 15.f * DataInX[1] +12.f * DataInX[2] - 3.f * DataInX[3];
float1 Cx3 =        -DataInX[0] +  3.f * DataInX[1] - 3.f * DataInX[2] +       DataInX[3];
DataInY[yj] = (1.f/6.f) * (Cx0 + t * ( Cx1 +  t * ( Cx2 + t * Cx3 ) ));
float1 Cy0 =   6.f * DataInY[0];
float1 Cy1 = -11.f * DataInY[0] + 18.f * DataInY[1] - 9.f * DataInY[2] + 2.f * DataInY[3];
float1 Cy2 =   6.f * DataInY[0] - 15.f * DataInY[1] +12.f * DataInY[2] - 3.f * DataInY[3];
float1 Cy3 =        -DataInY[0] +  3.f * DataInY[1] - 3.f * DataInY[2] +       DataInY[3];
DataInZ[zk] = (1.f/6.f) * (Cy0 + u * ( Cy1 +  u * ( Cy2 + u * Cy3 ) ));
float1 Cz0 =   6.f * DataInZ[0];
float1 Cz1 = -11.f * DataInZ[0] + 18.f * DataInZ[1] - 9.f * DataInZ[2] + 2.f * DataInZ[3];
float1 Cz2 =   6.f * DataInZ[0] - 15.f * DataInZ[1] +12.f * DataInZ[2] - 3.f * DataInZ[3];
float1 Cz3 =        -DataInZ[0] +  3.f * DataInZ[1] - 3.f * DataInZ[2] +       DataInZ[3];
float1 TriCubicValue = (1.f/6.f) * (Cz0 + v * ( Cz1 +  v * ( Cz2 + v * Cz3 ) ));
// for the fluid sims, a nice look can be achieved with BlendAmount = 0.25f;
// float BlendAmount = 0.0f;
// return lerp(TriCubicValue, TriLinearValue, BlendAmount);
return  min(max(TriCubicValue, minv), maxv);
Emitter_AttrRT_TextureSize;
Emitter_AttrRT_MipLevels;
Emitter_AttrRT_RWTexture;
Emitter_AttrRT_Texture;
Emitter_AttrRT_TextureSampler;
Emitter_AttrRT_RWTexture[int3(IndexX, IndexY, IndexZ)] = Value;
Value = Emitter_AttrRT_Texture.Load(int4(IndexX, IndexY, IndexZ, 0));
Value = Emitter_AttrRT_Texture.Load(int4(IndexX, IndexY, IndexZ, MipLevel));
Value = Emitter_AttrRT_Texture.SampleLevel(Emitter_AttrRT_TextureSampler, UVW, MipLevel);
Width = Emitter_AttrRT_TextureSize.x;
Height = Emitter_AttrRT_TextureSize.y;
Slices = Emitter_AttrRT_TextureSize.z;
OutMipLevels = Emitter_AttrRT_MipLevels;
IndexX = Linear % Emitter_AttrRT_TextureSize.x;
IndexY = (Linear / Emitter_AttrRT_TextureSize.x) % Emitter_AttrRT_TextureSize.y;
IndexZ = Linear / (Emitter_AttrRT_TextureSize.x * Emitter_AttrRT_TextureSize.y);
LinearToIndex_Emitter_AttrRT(ExecIndex(), IndexX, IndexY, IndexZ);
ExecToIndex_Emitter_AttrRT(Texel.x, Texel.y, Texel.z);
Unit.x = (float(Texel.x) + 0.5f) / float(Emitter_AttrRT_TextureSize.x);
Unit.y = (float(Texel.y) + 0.5f) / float(Emitter_AttrRT_TextureSize.y);
Unit.z = (float(Texel.z) + 0.5f) / float(Emitter_AttrRT_TextureSize.z);
    if(Emitter_Reader_InstanceCountOffset != 0xffffffff)
        Out_NumParticles = RWInstanceCounts[Emitter_Reader_InstanceCountOffset];
    else
        Out_NumParticles = 0;
    int RegisterIndex = Emitter_Reader_AttributeIndices[0].y;
    int NumParticles = Emitter_Reader_InstanceCountOffset != 0xffffffff ? RWInstanceCounts[Emitter_Reader_InstanceCountOffset] : 0;
    if(RegisterIndex != -1 && ParticleIndex >= 0 && ParticleIndex < NumParticles)
        Out_Valid = true;
        BRANCH
        if (Emitter_Reader_AttributeCompressed[0].y)
                Out_Value.x = float(Emitter_Reader_InputHalfBuffer[(RegisterIndex + 0)*Emitter_Reader_ParticleStrideHalf + ParticleIndex]);
                Out_Value.y = float(Emitter_Reader_InputHalfBuffer[(RegisterIndex + 1)*Emitter_Reader_ParticleStrideHalf + ParticleIndex]);
                Out_Value.z = float(Emitter_Reader_InputHalfBuffer[(RegisterIndex + 2)*Emitter_Reader_ParticleStrideHalf + ParticleIndex]);
        else
#endif //NIAGARA_COMPRESSED_ATTRIBUTES_ENABLED
                Out_Value.x = float(Emitter_Reader_InputFloatBuffer[(RegisterIndex + 0)*Emitter_Reader_ParticleStrideFloat + ParticleIndex]);
                Out_Value.y = float(Emitter_Reader_InputFloatBuffer[(RegisterIndex + 1)*Emitter_Reader_ParticleStrideFloat + ParticleIndex]);
                Out_Value.z = float(Emitter_Reader_InputFloatBuffer[(RegisterIndex + 2)*Emitter_Reader_ParticleStrideFloat + ParticleIndex]);
        Out_Valid = false;
        Out_Value = (float3)0;
    int RegisterIndex = Emitter_Reader_AttributeIndices[0].z;
        if (Emitter_Reader_AttributeCompressed[0].z)
                Out_Value = float(Emitter_Reader_InputHalfBuffer[(RegisterIndex + 0)*Emitter_Reader_ParticleStrideHalf + ParticleIndex]);
                Out_Value = float(Emitter_Reader_InputFloatBuffer[(RegisterIndex + 0)*Emitter_Reader_ParticleStrideFloat + ParticleIndex]);
        Out_Value = (float)0;
    int RegisterIndex = Emitter_Reader_AttributeIndices[0].w;
        if (Emitter_Reader_AttributeCompressed[0].w)
    int RegisterIndex = Emitter_Reader_AttributeIndices[1].x;
        if (Emitter_Reader_AttributeCompressed[1].x)
                Out_Value.w = float(Emitter_Reader_InputHalfBuffer[(RegisterIndex + 3)*Emitter_Reader_ParticleStrideHalf + ParticleIndex]);
                Out_Value.w = float(Emitter_Reader_InputFloatBuffer[(RegisterIndex + 3)*Emitter_Reader_ParticleStrideFloat + ParticleIndex]);
        Out_Value = (float4)0;
    int RegisterIndex = Emitter_Reader_AttributeIndices[1].y;
        if (Emitter_Reader_AttributeCompressed[1].y)
    int RegisterIndex = Emitter_Reader_AttributeIndices[1].z;
        if (Emitter_Reader_AttributeCompressed[1].z)
    int RegisterIndex = Emitter_Reader_AttributeIndices[1].w;
        if (Emitter_Reader_AttributeCompressed[1].w)
    int RegisterIndex = Emitter_Reader_AttributeIndices[2].x;
        if (Emitter_Reader_AttributeCompressed[2].x)
Context.MapSimStage1_PostSim.Emitter.UnitToLocal = Emitter_UnitToLocal;
Context.MapSimStage1_PostSim.Emitter.WorldToLocal = Emitter_WorldToLocal;
Context.MapSimStage1_PostSim.Emitter.IsLocalSpace = Emitter_IsLocalSpace;
Context.MapSimStage1_PostSim.Emitter.LocalToUnit = Emitter_LocalToUnit;
Context.MapSimStage1_PostSim.Emitter.dx = Emitter_dx;
Context.MapSimStage1_PostSim.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.MapSimStage1_PostSim.Emitter.RandomSeed = Emitter_RandomSeed;
Context.MapSimStage1_PostSim.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.MapSimStage1_PostSim.Engine.System.RandomSeed = Engine_System_RandomSeed;
Context.MapSpawn.Particles.UniqueID = 0;
Context.MapUpdate.Array.UniqueID = 0;
Context.MapUpdate.Particles.UniqueID = InputDataInt(0, 0, InstanceIdx);
Context.MapUpdate.Particles = Context.MapSpawn.Particles;
#elif ((SimulationStageIndex == 1)) // MapSimStage1_PostSim
const bool bValid = bIsValidInstance;
const int WriteIndex = OutputIndex(0, false, bValid);
OutputDataInt(0, 0, WriteIndex, Context.MapUpdate.Particles.UniqueID);
// If a stage doesn't kill particles, StoreUpdateVariables() never calls AcquireIndex(), so the
// count isn't updated. In that case we must manually copy the original count here.
RWInstanceCounts[WriteInstanceCountOffset] = GSpawnStartInstance + NumSpawnedInstances; 
// TODO!
CS wrapper for our generated code; calls spawn and update functions on the corresponding instances in the buffer
= InDispatchThreadId;
= InGroupId;
= InGroupThreadId;
= InGroupIndex;
GEmitterTickCounter = EmitterTickCounter;
GRandomSeedOffset = 0;
#if SimulationStageIndex == 0 // MapUpdate
DispatchThreadIdBounds = IndirectDispatchArgs[IndirectDispatchArgsOffset].xyz;
GLinearThreadId = GDispatchThreadId.x;
GLinearThreadId += GDispatchThreadId.y * DispatchThreadIdBounds.x;
GLinearThreadId += GDispatchThreadId.z * DispatchThreadIdBounds.x * DispatchThreadIdBounds.y;
#else //NIAGARA_DISPATCH_INDIRECT
= GDispatchThreadId.x + (GDispatchThreadId.y * DispatchThreadIdToLinear.y);
GLinearThreadId += GDispatchThreadId.z * DispatchThreadIdToLinear.z;
#endif //NIAGARA_DISPATCH_INDIRECT
bool bRunSpawnUpdateLogic = true;
GSpawnStartInstance = 0;
GSpawnStartInstance = RWInstanceCounts[ReadInstanceCountOffset];
const uint MaxInstances = GSpawnStartInstance + NumSpawnedInstances;
const bool bRunUpdateLogic = bRunSpawnUpdateLogic && GLinearThreadId < GSpawnStartInstance && GLinearThreadId < MaxInstances;
const bool bRunSpawnLogic = bRunSpawnUpdateLogic && GLinearThreadId >= GSpawnStartInstance && GLinearThreadId < MaxInstances;
const float RandomSeedInitialisation = NiagaraInternalNoise(GLinearThreadId * 16384, 0 * 8196, (bRunUpdateLogic ? 4096 : 0) + EmitterTickCounter);
// initialise the random state seed
FSimulationContext Context = (FSimulationContext)0;
SetupExecIndexForGPU();
InitConstants(Context);
LoadUpdateVariables(Context, GLinearThreadId);
ReadDataSets(Context);
SetupExecIndexAndSpawnInfoForGPU();
InitSpawnVariables(Context);
Context.MapSpawn.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + GLinearThreadId - GSpawnStartInstance;
ConditionalInterpolateParameters(Context);
SimulateMapSpawn(Context);
TransferAttributes(Context);
SimulateMapUpdate(Context);
WriteDataSets(Context);
StoreUpdateVariables(Context, bRunUpdateLogic || bRunSpawnLogic);
#elif SimulationStageIndex == 1 // MapSimStage1_PostSim
const uint MaxInstances = SimulationStage_GetInstanceCount();
GLinearThreadId = all(GDispatchThreadId < DispatchThreadIdBounds) ? GLinearThreadId : MaxInstances;
GSpawnStartInstance = MaxInstances;
const bool bRunUpdateLogic = (GLinearThreadId < GSpawnStartInstance) && (SimStart != 1);
const bool bRunSpawnLogic = (GLinearThreadId < GSpawnStartInstance) && (SimStart == 1);
SimulateMapSimStage1_PostSim(Context);
FParamMap0 Map;
void GetRenderTargetSize_Emitter_SimRT(int In_InstanceData, out int Out_Width, out int Out_Height, out int Out_Depth);
void ExecToIndex_Emitter_SimRT(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void ExecToUnit_Emitter_SimRT(int In_InstanceData, out float3 Out_Unit);
void GetNumParticles_Emitter_Reader(int In_InstanceData, out int Out_NumParticles);
void GetVectorByIndex_Emitter_Reader_AttributePosition(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_radius(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Emitter_Reader_AttributeRestPosition(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetQuaternionByIndex_Emitter_Reader_AttributeMeshOrientation(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_density(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_temperature(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Emitter_Reader_Attributefluids_source_velocity(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetColorByIndex_Emitter_Reader_Attributefluids_source_color(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void SetRenderTargetValue_Emitter_SimRT_UEImpureCall(int In_InstanceData, bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
void ExecToIndex_Emitter_AttrRT(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void SetRenderTargetValue_Emitter_AttrRT_UEImpureCall(int In_InstanceData, bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
GetVectorByIndex_Emitter_Reader_AttributePosition(1, CurrIdx, Valid, ParticlePos);
GetFloatByIndex_Emitter_Reader_Attributefluids_source_radius(1, CurrIdx, Valid, Radius);
        GetVectorByIndex_Emitter_Reader_AttributeRestPosition(1, CurrIdx, Valid, ParticleRestPos);
        GetQuaternionByIndex_Emitter_Reader_AttributeMeshOrientation(1, CurrIdx, Valid, MeshOrientation);
        GetFloatByIndex_Emitter_Reader_Attributefluids_source_density(1, CurrIdx, Valid, ParticleDensity);
        GetFloatByIndex_Emitter_Reader_Attributefluids_source_temperature(1, CurrIdx, Valid, ParticleTemperature);
        GetVectorByIndex_Emitter_Reader_Attributefluids_source_velocity(1, CurrIdx, Valid, ParticleVel);
        GetColorByIndex_Emitter_Reader_Attributefluids_source_color(1, CurrIdx, Valid, ParticleColor);
GetRenderTargetSize_Emitter_SimRT(0, GetRenderTargetSize_Emitter_SimRTOutput_Width, GetRenderTargetSize_Emitter_SimRTOutput_Height, GetRenderTargetSize_Emitter_SimRTOutput_Depth);
ExecToIndex_Emitter_SimRT(0, ExecToIndex_Emitter_SimRTOutput_IndexX, ExecToIndex_Emitter_SimRTOutput_IndexY, ExecToIndex_Emitter_SimRTOutput_IndexZ);
ExecToUnit_Emitter_SimRT(0, ExecToUnit_Emitter_SimRTOutput_Unit);
float3 Result = mul(float4(ExecToUnit_Emitter_SimRTOutput_Unit,1.0),Context.Map.Grid3D_Gas_GatherParticleSource.UnitToLocal).xyz;
GetNumParticles_Emitter_Reader(1, GetNumParticles_Emitter_ReaderOutput_NumParticles);
NiagaraMatrix_SelectResult = Context.Map.Grid3D_Gas_GatherParticleSource.WorldToLocal;
CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_(Result, Constant6, Constant7, GetNumParticles_Emitter_ReaderOutput_NumParticles, NiagaraMatrix_SelectResult, Constant8, Constant9, Constant10, Context.Map.Grid3D_Gas_GatherParticleSource.CompositingMethod, Context.Map.Grid3D_Gas_GatherParticleSource.LocalToUnit, Context.Map.Grid3D_Gas_GatherParticleSource.dx, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DensityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_VelocityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TemperatureOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TextureCoordOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DistanceOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_ColorOut);
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDensity = NiagaraFloat_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedVelocity = Vector3f_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTemperature = NiagaraFloat001_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord = Vector3f001_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDistance = NiagaraFloat002_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor = LinearColor_SelectResult1;
NiagaraScript_510_Particle_Func_(Context.Map.MakeFloatFromVector.VECTOR_VAR, Context.Map.MakeFloatFromVector.Channel, NiagaraScript_510_Particle_Func_Output_Float, Context);
NiagaraScript_510_Particle_Func_(Context.Map.MakeFloatFromVector001.VECTOR_VAR, Context.Map.MakeFloatFromVector001.Channel, NiagaraScript_510_Particle_Func_Output_Float1, Context);
NiagaraScript_510_Particle_Func_(Context.Map.MakeFloatFromVector002.VECTOR_VAR, Context.Map.MakeFloatFromVector002.Channel, NiagaraScript_510_Particle_Func_Output_Float2, Context);
Output11.r = Context.Map.Grid3D_SetRTValues.Red;
Output11.g = Context.Map.Grid3D_SetRTValues.Green;
Output11.b = Context.Map.Grid3D_SetRTValues.Blue;
Output11.a = Context.Map.Grid3D_SetRTValues.Alpha;
Context.Map.Local.Grid3D_SetRTValues.Value = Output11;
ExecToIndex_Emitter_SimRT(0, ExecToIndex_Emitter_SimRTOutput_IndexX1, ExecToIndex_Emitter_SimRTOutput_IndexY1, ExecToIndex_Emitter_SimRTOutput_IndexZ1);
SetRenderTargetValue_Emitter_SimRT_UEImpureCall(0, Constant34, ExecToIndex_Emitter_SimRTOutput_IndexX1, ExecToIndex_Emitter_SimRTOutput_IndexY1, ExecToIndex_Emitter_SimRTOutput_IndexZ1, Context.Map.Local.Grid3D_SetRTValues.Value);
ENiagaraVector4_Channels = Context.Map.MakeFloatFromLinearColor.Channel;
NiagaraScript_512_Particle_Func_(Context.Map.MakeFloatFromLinearColor.LinearColor, ENiagaraVector4_Channels, NiagaraScript_512_Particle_Func_Output_NewOutput, Context);
ENiagaraVector4_Channels1 = Context.Map.MakeFloatFromLinearColor001.Channel;
NiagaraScript_512_Particle_Func_(Context.Map.MakeFloatFromLinearColor001.LinearColor, ENiagaraVector4_Channels1, NiagaraScript_512_Particle_Func_Output_NewOutput1, Context);
ENiagaraVector4_Channels2 = Context.Map.MakeFloatFromLinearColor002.Channel;
NiagaraScript_512_Particle_Func_(Context.Map.MakeFloatFromLinearColor002.LinearColor, ENiagaraVector4_Channels2, NiagaraScript_512_Particle_Func_Output_NewOutput2, Context);
ENiagaraVector4_Channels3 = Context.Map.MakeFloatFromLinearColor003.Channel;
NiagaraScript_512_Particle_Func_(Context.Map.MakeFloatFromLinearColor003.LinearColor, ENiagaraVector4_Channels3, NiagaraScript_512_Particle_Func_Output_NewOutput3, Context);
Output12.r = Context.Map.Grid3D_SetRTValues001.Red;
Output12.g = Context.Map.Grid3D_SetRTValues001.Green;
Output12.b = Context.Map.Grid3D_SetRTValues001.Blue;
Output12.a = Context.Map.Grid3D_SetRTValues001.Alpha;
Context.Map.Local.Grid3D_SetRTValues001.Value = Output12;
ExecToIndex_Emitter_AttrRT(3, ExecToIndex_Emitter_AttrRTOutput_IndexX, ExecToIndex_Emitter_AttrRTOutput_IndexY, ExecToIndex_Emitter_AttrRTOutput_IndexZ);
SetRenderTargetValue_Emitter_AttrRT_UEImpureCall(3, Constant43, ExecToIndex_Emitter_AttrRTOutput_IndexX, ExecToIndex_Emitter_AttrRTOutput_IndexY, ExecToIndex_Emitter_AttrRTOutput_IndexZ, Context.Map.Local.Grid3D_SetRTValues001.Value);
EnterStatScope(0 /**SimulationStage_0*/);
Context.Map.Grid3D_Gas_GatherParticleSource.UnitToLocal = Context.Map.Emitter.UnitToLocal;
Context.Map.Grid3D_Gas_GatherParticleSource.WorldToLocal = Context.Map.Emitter.WorldToLocal;
Context.Map.Grid3D_Gas_GatherParticleSource.IsLocalSpace = Context.Map.Emitter.IsLocalSpace;
Context.Map.Grid3D_Gas_GatherParticleSource.LocalToUnit = Context.Map.Emitter.LocalToUnit;
Context.Map.Grid3D_Gas_GatherParticleSource.dx = Context.Map.Emitter.dx;
Context.Map.Grid3D_Gas_GatherParticleSource.CompositingMethod = Constant;
Context.Map.MakeFloatFromVector.VECTOR_VAR = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.Map.MakeFloatFromVector001.VECTOR_VAR = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.Map.MakeFloatFromVector002.VECTOR_VAR = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.Map.MakeFloatFromVector001.Channel = Constant28;
Context.Map.MakeFloatFromVector002.Channel = Constant29;
Context.Map.MakeFloatFromVector.Channel = Constant30;
Context.Map.Grid3D_SetRTValues.Red = MakeFloatFromVector_Emitter_Func_Output_Float;
Context.Map.Grid3D_SetRTValues.Green = MakeFloatFromVector001_Emitter_Func_Output_Float;
Context.Map.Grid3D_SetRTValues.Blue = MakeFloatFromVector002_Emitter_Func_Output_Float;
Context.Map.Grid3D_SetRTValues.Alpha = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDistance;
Context.Map.MakeFloatFromLinearColor.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor001.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor002.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor003.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor001.Channel = Constant36;
Context.Map.MakeFloatFromLinearColor002.Channel = Constant37;
Context.Map.MakeFloatFromLinearColor003.Channel = Constant38;
Context.Map.MakeFloatFromLinearColor.Channel = Constant39;
Context.Map.Grid3D_SetRTValues001.Red = MakeFloatFromLinearColor_Emitter_Func_Output_NewOutput;
Context.Map.Grid3D_SetRTValues001.Green = MakeFloatFromLinearColor001_Emitter_Func_Output_NewOutput;
Context.Map.Grid3D_SetRTValues001.Blue = MakeFloatFromLinearColor002_Emitter_Func_Output_NewOutput;
Context.Map.Grid3D_SetRTValues001.Alpha = MakeFloatFromLinearColor003_Emitter_Func_Output_NewOutput;
ExitStatScope(/**SimulationStage_0*/);
EnterStatScope(4 /**SimulationStage_0_Main*/);
Context.Map.Emitter.UnitToLocal = Emitter_UnitToLocal;
Context.Map.Emitter.WorldToLocal = Emitter_WorldToLocal;
Context.Map.Emitter.IsLocalSpace = Emitter_IsLocalSpace;
Context.Map.Emitter.LocalToUnit = Emitter_LocalToUnit;
Context.Map.Emitter.dx = Emitter_dx;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = 0;
EnterStatScope(5 /**SimulationStage_0_MapMain*/);
Simulate(Context);
ExitStatScope(/**SimulationStage_0_MapMain*/);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Particles.UniqueID);
ExitStatScope(/**SimulationStage_0_Main*/);
EnterStatScope(0 /**SpawnScript_0*/);
ExitStatScope(/**SpawnScript_0*/);
EnterStatScope(1 /**SpawnScript_0_Main*/);
Context.Map.Particles.UniqueID = 0;
Context.Map.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + ExecIndex();
EnterStatScope(2 /**SpawnScript_0_MapMain*/);
ExitStatScope(/**SpawnScript_0_MapMain*/);
ExitStatScope(/**SpawnScript_0_Main*/);
EnterStatScope(0 /**UpdateScript_1*/);
ExitStatScope(/**UpdateScript_1*/);
EnterStatScope(1 /**UpdateScript_1_Main*/);
Context.Map.Particles.UniqueID = InputDataInt(0, 0);
Context.Map.Array.UniqueID = 0;
EnterStatScope(2 /**UpdateScript_1_MapMain*/);
ExitStatScope(/**UpdateScript_1_MapMain*/);
ExitStatScope(/**UpdateScript_1_Main*/);

