// Shader generated by Niagara HLSL Translator
// SimStage[0] = ParticleSpawnUpdate
// SimStage[1] = Init
// SimStage[2] = Compute Profile Buffer
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float Emitter_ProfileBuffer_Height;
float Emitter_Gravity;
int UniqueID;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
float Height;
float Gravity;
FParamMap0_Emitter_ProfileBuffer ProfileBuffer;
FParamMap0_Array Array;
FParamMap0_ComputeProfileBuffer ComputeProfileBuffer;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Particles Particles;
#if ((SimulationStageIndex == 0)) // MapSpawn
FParamMap0 MapSpawn;
#endif // MapSpawn
#if ((SimulationStageIndex == 0)) // MapUpdate
FParamMap0 MapUpdate;
#endif // MapUpdate
#if ((SimulationStageIndex == 1)) // MapSimStage1_Init
FParamMap0 MapSimStage1_Init;
#endif // MapSimStage1_Init
#if ((SimulationStageIndex == 2)) // MapSimStage2_ComputeProfileBuffer
FParamMap0 MapSimStage2_ComputeProfileBuffer;
#endif // MapSimStage2_ComputeProfileBuffer
static float HackSpawnInterp = 1.0;
void SetVariables_FF0B3CD24665E22A75CAEEB5B8E7E902_Emitter_Func_(inout FSimulationContext Context);
void ExecutionIndexToGridIndex_Emitter_ProfileBuffer(out int Out_IndexX, out int Out_IndexY);
void SetFloatValue_Emitter_ProfileBuffer_UEImpureCall_AttributeHeight(int In_IndexX, int In_IndexY, float In_Value);
void IndexToUnit_Emitter_ProfileBuffer(float In_IndexX, float In_IndexY, out float3 Out_Unit);
void GetNumCells_Emitter_ProfileBuffer(out int Out_NumCellsX, out int Out_NumCellsY);
void SetGridValue_Emitter_ProfileBuffer(int In_IndexX, int In_IndexY, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
void CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_(int In_IndexX, int In_IndexY, float In_t, float3 In_Unit, int In_NumCellsX, float In_TileWidth, float In_AmplitudeMult, int In_NumWavelengthSamples, float In_g, float In_MinWavelengthMult, float In_MaxWavelengthMult, float In_Slosh, float In_Velocity, out float Out_Height);
void ComputeProfileBuffer_Emitter_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
float Constant1 = 0;
Context.MapSimStage1_Init.Emitter.ProfileBuffer.Height = Constant1;
int d = 0;
Out_Height = 0;
float p = (In_Unit.x - .5) * In_TileWidth - In_t * In_Velocity;
const float PI = 3.1415;
float dx = In_TileWidth / In_NumCellsX;
float MaxLambda = (In_TileWidth - dx) * In_MaxWavelengthMult;
// min wavelength roughly at the very smallest is 3 cells
float MinLambda = dx * In_MinWavelengthMult;
float MaxK = 2. * PI / MaxLambda;
float MinK = 2. * PI / MinLambda;
float DL = (MaxLambda - MinLambda) / In_NumWavelengthSamples;
float DK = (MaxK - MinK) / In_NumWavelengthSamples;
float Lambda = MinLambda + .5 * DL;
for (int j = 1; j <= In_NumWavelengthSamples; ++j) {
Lambda = (In_TileWidth - dx)/j;
  continue;
float k = 2. * PI / Lambda;
float freq = sqrt(In_g * k);
float a = .0081;
float b = .74;
float U = 200;
float w_0 = In_g / (1.026 * U);
//float A = a*g*g/(pow(freq,5)) * exp(-b * pow(w_0/freq,4));
//float A = (.001*a * 2 * PI * g*g) / pow(freq, 5);
float A = 1./k;
//float A = 1;//5./pow(freq,2);
float eps = rand(In_TileWidth, k, 0, 0);
float epsR = rand(In_TileWidth, k+123, 1230, 05);
// integral solution but looks bad...
// Height += AmplitudeMult * A * cos(k*(p+eps) - freq * t) * k * DK;
Out_Height += In_AmplitudeMult * A * cos(k*(p+eps) - freq * In_t);
// #todo(dmp): add in a wave in the opposite direction?
Out_Height += In_AmplitudeMult * A * cos(k*(p+epsR) + freq * In_t) * In_Slosh;
//Lambda += DL;
SetGridValue_Emitter_ProfileBuffer(In_IndexX, In_IndexY, 0, Out_Height, d);
float Constant10 = 0.05;
int Constant11 = 100;
float Constant12 = 1;
float Constant13 = 10;
float Constant14 = 0.5;
float Constant15 = 0;
float Constant16 = 0;
float2 Constant17 = float2(1000,0);
int ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexX;
int ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexY;
ExecutionIndexToGridIndex_Emitter_ProfileBuffer(ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexX, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexY);
float Result = Context.MapSimStage2_ComputeProfileBuffer.Engine.Time * Constant12;
float3 IndexToUnit_Emitter_ProfileBufferOutput_Unit;
IndexToUnit_Emitter_ProfileBuffer(ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexX, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexY, IndexToUnit_Emitter_ProfileBufferOutput_Unit);
int GetNumCells_Emitter_ProfileBufferOutput_NumCellsX;
int GetNumCells_Emitter_ProfileBufferOutput_NumCellsY;
GetNumCells_Emitter_ProfileBuffer(GetNumCells_Emitter_ProfileBufferOutput_NumCellsX, GetNumCells_Emitter_ProfileBufferOutput_NumCellsY);
float X;
float Y;
X = Constant17.x;
Y = Constant17.y;
float CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_Output_Height;
CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_(ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexX, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexY, Result, IndexToUnit_Emitter_ProfileBufferOutput_Unit, GetNumCells_Emitter_ProfileBufferOutput_NumCellsX, X, Constant10, Constant11, Context.MapSimStage2_ComputeProfileBuffer.ComputeProfileBuffer.Gravity, Constant13, Constant14, Constant15, Constant16, CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_Output_Height);
Context.MapSimStage2_ComputeProfileBuffer.Emitter.ProfileBuffer.Height = CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_Output_Height;
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
//Begin Spawn Script!
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
//End Spawn Script!
//Handle resetting previous values at the end of spawn so that they match outputs! (Needed for motion blur/etc)
HandlePreviousValuesForSpawn(Context);
// Begin HandleMissingDefaultValues
// End HandleMissingDefaultValues
//Begin Update Script!
RandomCounterDeterministic = 0;
//End Update Script!
//Begin Stage Script: MapSimStage1_Init!
float Constant = 0;
EnterStatScope(1 /**SetVariables_FF0B3CD24665E22A75CAEEB5B8E7E902_Emitter_Func_*/);
SetVariables_FF0B3CD24665E22A75CAEEB5B8E7E902_Emitter_Func_(Context);
ExitStatScope(/**SetVariables_FF0B3CD24665E22A75CAEEB5B8E7E902_Emitter_Func_*/);
//End Simulation Stage Script: MapSimStage1_Init
//Begin Stage Script: MapSimStage2_ComputeProfileBuffer!
Context.MapSimStage2_ComputeProfileBuffer.ComputeProfileBuffer.Gravity = Context.MapSimStage2_ComputeProfileBuffer.Emitter.Gravity;
float Constant2 = 0.05;
int Constant3 = 100;
float Constant4 = 1;
float Constant5 = 10;
float Constant6 = 0.5;
float Constant7 = 0;
float Constant8 = 0;
float2 Constant9 = float2(1000,0);
EnterStatScope(2 /**ComputeProfileBuffer_Emitter_Func_*/);
ComputeProfileBuffer_Emitter_Func_(Context);
ExitStatScope(/**ComputeProfileBuffer_Emitter_Func_*/);
//End Simulation Stage Script: MapSimStage2_ComputeProfileBuffer
int2 Emitter_ProfileBuffer_NumCells;
float2 Emitter_ProfileBuffer_UnitToUV;
float2 Emitter_ProfileBuffer_CellSize;
float2 Emitter_ProfileBuffer_WorldBBoxSize;
Texture2DArray<float> Emitter_ProfileBuffer_Grid;
RWTexture2DArray<float> Emitter_ProfileBuffer_OutputGrid;
SamplerState Emitter_ProfileBuffer_GridSampler;
int4 Emitter_ProfileBuffer_AttributeIndices[2];
int Emitter_ProfileBuffer_NumAttributes;
Out_IndexX = GDispatchThreadId.x;
Out_IndexY = GDispatchThreadId.y;
const uint Linear = GLinearThreadId;
Out_IndexX = Linear % Emitter_ProfileBuffer_NumCells.x;
Out_IndexY = Linear / Emitter_ProfileBuffer_NumCells.x;
int In_AttributeIndex = 0;
Emitter_ProfileBuffer_OutputGrid[int3(In_IndexX, In_IndexY, In_AttributeIndex)] = In_Value;
Out_Unit = float3((float2(In_IndexX, In_IndexY) + .5) * Emitter_ProfileBuffer_UnitToUV, 0);
Out_NumCellsX = Emitter_ProfileBuffer_NumCells.x;
Out_NumCellsY = Emitter_ProfileBuffer_NumCells.y;
val = 0;
//Generated by UNiagaraDataInterfaceGrid2DCollection::GenerateSetupHLSL
// Argument Name "Map" Type "NiagaraParameterMap"
// Argument Name "TargetDataInterface" Type "NiagaraDataInterfaceGrid2DCollection"
SetupFromIterationSource_MapSimStage1_Init_GeneratedSetup_Func_(Context);
//Generated by UNiagaraDataInterfaceGrid2DCollection::GenerateTeardownHLSL
//Generated by UNiagaraDataInterfaceGrid2DCollection::GenerateIterationSourceNamespaceWriteAttributesHLSL
int X, Y;
ExecutionIndexToGridIndex_Emitter_ProfileBuffer(X, Y);
// Name "Emitter.ProfileBuffer.Height" Type "NiagaraFloat" Var "Map.Emitter.ProfileBuffer.Height"
SetFloatValue_Emitter_ProfileBuffer_UEImpureCall_AttributeHeight(X, Y, Context.MapSimStage1_Init.Emitter.ProfileBuffer.Height);
TeardownFromIterationSource_MapSimStage1_Init_GeneratedTeardown_Func_(Context);
TeardownFromIterationSource_MapSimStage1_Init_GeneratedWriteAttributesEmitter_ProfileBuffer_Func_(Context);
SetupFromIterationSource_MapSimStage2_ComputeProfileBuffer_GeneratedSetup_Func_(Context);
SetFloatValue_Emitter_ProfileBuffer_UEImpureCall_AttributeHeight(X, Y, Context.MapSimStage2_ComputeProfileBuffer.Emitter.ProfileBuffer.Height);
TeardownFromIterationSource_MapSimStage2_ComputeProfileBuffer_GeneratedTeardown_Func_(Context);
TeardownFromIterationSource_MapSimStage2_ComputeProfileBuffer_GeneratedWriteAttributesEmitter_ProfileBuffer_Func_(Context);
Context.MapSimStage1_Init.Emitter.ProfileBuffer.Height = Emitter_ProfileBuffer_Height;
Context.MapSimStage2_ComputeProfileBuffer.Emitter.Gravity = Emitter_Gravity;
Context.MapSimStage2_ComputeProfileBuffer.Engine.Time = Engine_Time;
Context.MapSimStage2_ComputeProfileBuffer.Emitter.ProfileBuffer.Height = Emitter_ProfileBuffer_Height;
Context.MapSimStage2_ComputeProfileBuffer.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.MapSimStage2_ComputeProfileBuffer.Emitter.RandomSeed = Emitter_RandomSeed;
Context.MapSimStage2_ComputeProfileBuffer.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.MapSimStage2_ComputeProfileBuffer.Engine.System.RandomSeed = Engine_System_RandomSeed;
Context.MapSpawn.Particles.UniqueID = 0;
Context.MapUpdate.Array.UniqueID = 0;
Context.MapUpdate.Particles.UniqueID = InputDataInt(0, 0, InstanceIdx);
#elif ((SimulationStageIndex == 1)) // MapSimStage1_Init
SetupFromIterationSource_MapSimStage1_Init(Context);
#elif ((SimulationStageIndex == 2)) // MapSimStage2_ComputeProfileBuffer
SetupFromIterationSource_MapSimStage2_ComputeProfileBuffer(Context);
Context.MapUpdate.Particles = Context.MapSpawn.Particles;
const bool bValid = bIsValidInstance;
const int WriteIndex = OutputIndex(0, false, bValid);
OutputDataInt(0, 0, WriteIndex, Context.MapUpdate.Particles.UniqueID);
// If a stage doesn't kill particles, StoreUpdateVariables() never calls AcquireIndex(), so the
// count isn't updated. In that case we must manually copy the original count here.
RWInstanceCounts[WriteInstanceCountOffset] = GSpawnStartInstance + NumSpawnedInstances; 
TeardownFromIterationSource_MapSimStage1_Init(Context);
TeardownFromIterationSource_MapSimStage2_ComputeProfileBuffer(Context);
// TODO!
CS wrapper for our generated code; calls spawn and update functions on the corresponding instances in the buffer
= InDispatchThreadId;
= InGroupId;
= InGroupThreadId;
= InGroupIndex;
GEmitterTickCounter = EmitterTickCounter;
GRandomSeedOffset = 0;
#if SimulationStageIndex == 0 // MapUpdate
DispatchThreadIdBounds = IndirectDispatchArgs[IndirectDispatchArgsOffset].xyz;
GLinearThreadId = GDispatchThreadId.x;
GLinearThreadId += GDispatchThreadId.y * DispatchThreadIdBounds.x;
GLinearThreadId += GDispatchThreadId.z * DispatchThreadIdBounds.x * DispatchThreadIdBounds.y;
#else //NIAGARA_DISPATCH_INDIRECT
= GDispatchThreadId.x + (GDispatchThreadId.y * DispatchThreadIdToLinear.y);
GLinearThreadId += GDispatchThreadId.z * DispatchThreadIdToLinear.z;
#endif //NIAGARA_DISPATCH_INDIRECT
bool bRunSpawnUpdateLogic = true;
GSpawnStartInstance = 0;
GSpawnStartInstance = RWInstanceCounts[ReadInstanceCountOffset];
const uint MaxInstances = GSpawnStartInstance + NumSpawnedInstances;
const bool bRunUpdateLogic = bRunSpawnUpdateLogic && GLinearThreadId < GSpawnStartInstance && GLinearThreadId < MaxInstances;
const bool bRunSpawnLogic = bRunSpawnUpdateLogic && GLinearThreadId >= GSpawnStartInstance && GLinearThreadId < MaxInstances;
const float RandomSeedInitialisation = NiagaraInternalNoise(GLinearThreadId * 16384, 0 * 8196, (bRunUpdateLogic ? 4096 : 0) + EmitterTickCounter);
// initialise the random state seed
FSimulationContext Context = (FSimulationContext)0;
SetupExecIndexForGPU();
InitConstants(Context);
LoadUpdateVariables(Context, GLinearThreadId);
ReadDataSets(Context);
SetupExecIndexAndSpawnInfoForGPU();
InitSpawnVariables(Context);
Context.MapSpawn.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + ExecIndex();
ConditionalInterpolateParameters(Context);
SimulateMapSpawn(Context);
TransferAttributes(Context);
SimulateMapUpdate(Context);
WriteDataSets(Context);
StoreUpdateVariables(Context, bRunUpdateLogic || bRunSpawnLogic);
#elif SimulationStageIndex == 1 // MapSimStage1_Init
const uint MaxInstances = SimulationStage_GetInstanceCount();
GLinearThreadId = all(GDispatchThreadId < DispatchThreadIdBounds) ? GLinearThreadId : MaxInstances;
GSpawnStartInstance = MaxInstances;
const bool bRunUpdateLogic = (GLinearThreadId < GSpawnStartInstance) && (SimStart != 1);
const bool bRunSpawnLogic = (GLinearThreadId < GSpawnStartInstance) && (SimStart == 1);
SimulateMapSimStage1_Init(Context);
#elif SimulationStageIndex == 2 // MapSimStage2_ComputeProfileBuffer
SimulateMapSimStage2_ComputeProfileBuffer(Context);
FParamMap0 Map;
void ExecutionIndexToGridIndex_Emitter_ProfileBuffer(int In_InstanceData, out int Out_IndexX, out int Out_IndexY);
void IndexToUnit_Emitter_ProfileBuffer(int In_InstanceData, float In_IndexX, float In_IndexY, out float3 Out_Unit);
void GetNumCells_Emitter_ProfileBuffer(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY);
void SetGridValue_Emitter_ProfileBuffer(int In_InstanceData, int In_IndexX, int In_IndexY, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
SetGridValue_Emitter_ProfileBuffer(0, In_IndexX, In_IndexY, 0, Out_Height, d);
float Constant8 = 0.05;
int Constant9 = 100;
float Constant10 = 1;
float Constant11 = 10;
float Constant12 = 0.5;
float Constant13 = 0;
float Constant14 = 0;
float2 Constant15 = float2(1000,0);
ExecutionIndexToGridIndex_Emitter_ProfileBuffer(0, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexX, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexY);
float Result = Context.Map.Engine.Time * Constant10;
IndexToUnit_Emitter_ProfileBuffer(0, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexX, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexY, IndexToUnit_Emitter_ProfileBufferOutput_Unit);
GetNumCells_Emitter_ProfileBuffer(0, GetNumCells_Emitter_ProfileBufferOutput_NumCellsX, GetNumCells_Emitter_ProfileBufferOutput_NumCellsY);
X = Constant15.x;
Y = Constant15.y;
CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_(ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexX, ExecutionIndexToGridIndex_Emitter_ProfileBufferOutput_IndexY, Result, IndexToUnit_Emitter_ProfileBufferOutput_Unit, GetNumCells_Emitter_ProfileBufferOutput_NumCellsX, X, Constant8, Constant9, Context.Map.ComputeProfileBuffer.Gravity, Constant11, Constant12, Constant13, Constant14, CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_Output_Height);
Context.Map.Emitter.ProfileBuffer.Height = CustomHlslBEE357764B027BBD45B98B9B2A0AEBC6Emitter_ProfileBuffer_Func_Output_Height;
EnterStatScope(0 /**SimulationStage_0*/);
Context.Map.ComputeProfileBuffer.Gravity = Context.Map.Emitter.Gravity;
float Constant = 0.05;
int Constant1 = 100;
float Constant2 = 1;
float Constant3 = 10;
float Constant4 = 0.5;
float Constant5 = 0;
float Constant6 = 0;
float2 Constant7 = float2(1000,0);
EnterStatScope(1 /**ComputeProfileBuffer_Emitter_Func_*/);
ExitStatScope(/**SimulationStage_0*/);
EnterStatScope(2 /**SimulationStage_0_Main*/);
Context.Map.Emitter.Gravity = Emitter_Gravity;
Context.Map.Engine.Time = Engine_Time;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
EnterStatScope(3 /**SimulationStage_0_MapMain*/);
Simulate(Context);
ExitStatScope(/**SimulationStage_0_MapMain*/);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Particles.UniqueID);
ExitStatScope(/**SimulationStage_0_Main*/);
Context.Map.Emitter.ProfileBuffer.Height = Constant1;
EnterStatScope(0 /**SpawnScript*/);
ExitStatScope(/**SpawnScript*/);
EnterStatScope(1 /**SpawnScript_Main*/);
Context.Map.Particles.UniqueID = 0;
Context.Map.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + ExecIndex();
EnterStatScope(2 /**SpawnScript_MapMain*/);
ExitStatScope(/**SpawnScript_MapMain*/);
ExitStatScope(/**SpawnScript_Main*/);
EnterStatScope(0 /**UpdateScript*/);
ExitStatScope(/**UpdateScript*/);
EnterStatScope(1 /**UpdateScript_Main*/);
Context.Map.Particles.UniqueID = InputDataInt(0, 0);
Context.Map.Array.UniqueID = 0;
EnterStatScope(2 /**UpdateScript_MapMain*/);
ExitStatScope(/**UpdateScript_MapMain*/);
ExitStatScope(/**UpdateScript_Main*/);

