int IGNORE;
int NumStreakParticles = 1;
    NumStreakParticles = min(MaxStreakSamples, max(1, StreakDensity * IndexVelocityMagnitude / (2. * ParticleIndexRadius)));
const float ScalarValueToUse = ScalarValue / NumStreakParticles;
for (int ww = 0; ww < NumStreakParticles; ++ww)
    const float StreakPosition = 1.0 * ww / NumStreakParticles;
    const float3 FloatIndexToUse = FloatIndex - StreakPosition * IndexVelocity;
    const float ParticleIndexRadiusToUse = lerp(ParticleIndexRadius, PreviousParticleIndexRadius, StreakPosition);
    const int IntParticleRadius = ceil(ParticleIndexRadiusToUse);
    for (int xx = -IntParticleRadius; xx <= IntParticleRadius; ++xx) {
    for (int yy = -IntParticleRadius; yy <= IntParticleRadius; ++yy) {
    for (int zz = -IntParticleRadius; zz <= IntParticleRadius; ++zz) {
        const int3 Offset = int3(xx,yy,zz);
        const int3 CurrIndex = FloatIndexToUse + Offset;
        if (length(Offset) <= ParticleIndexRadiusToUse &&
            CurrIndex.x >= 0 && CurrIndex.x < NumCellsX && 
            CurrIndex.y >= 0 && CurrIndex.y < NumCellsY &&
            CurrIndex.z >= 0 && CurrIndex.z < NumCellsZ) 
            float Falloff = 1.0;
            if (UseFalloff)
                Falloff = 1. - smoothstep(max(0,ParticleIndexRadiusToUse-2.41421), ParticleIndexRadiusToUse, length(FloatIndexToUse - CurrIndex));
            Grid.SetGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex, Falloff * ScalarValueToUse, IGNORE);
ä¸h¥™–UH½;•¡
öw;5*u
ô2Ì;R¿ãM¹§
// Shader generated by Niagara HLSL Translator
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
int Module_AttributeIndex;
float3 Module_FloatIndex;
float Module_ParticleIndexRadius;
float Module_ScalarValue;
float3 Module_IndexVelocity;
float Module_IndexVelocityMagnitude;
float Module_StreakDensity;
float Module_PreviousParticleIndexRadius;
int Module_MaxStreakSamples;
int AttributeIndex;
float3 FloatIndex;
float3 IndexVelocity;
float IndexVelocityMagnitude;
int MaxStreakSamples;
float ParticleIndexRadius;
float PreviousParticleIndexRadius;
float ScalarValue;
float StreakDensity;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Module Module;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void GetNumCells_Emitter_DestinationGrid(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY, out int Out_NumCellsZ);
void SetGridValue_Emitter_DestinationGrid(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
void CustomHlslDE94F33049E504C87DE76B8358A8903AEmitter_DestinationGrid_Func_(int In_GridAttributeIndex, float3 In_FloatIndex, float In_ParticleIndexRadius, float In_ScalarValue, int In_NumCellsX, int In_NumCellsY, int In_NumCellsZ, float3 In_IndexVelocity, float In_IndexVelocityMagnitude, float In_StreakDensity, float In_PreviousParticleIndexRadius, int In_MaxStreakSamples, bool In_UseFalloff, bool In_UseStreaking, inout FSimulationContext Context);
float GetSpawnInterpolation();
    NumStreakParticles = min(In_MaxStreakSamples, max(1, In_StreakDensity * In_IndexVelocityMagnitude / (2. * In_ParticleIndexRadius)));
const float ScalarValueToUse = In_ScalarValue / NumStreakParticles;
    const float3 FloatIndexToUse = In_FloatIndex - StreakPosition * In_IndexVelocity;
    const float ParticleIndexRadiusToUse = lerp(In_ParticleIndexRadius, In_PreviousParticleIndexRadius, StreakPosition);
            CurrIndex.x >= 0 && CurrIndex.x < In_NumCellsX && 
            CurrIndex.y >= 0 && CurrIndex.y < In_NumCellsY &&
            CurrIndex.z >= 0 && CurrIndex.z < In_NumCellsZ) 
            if (In_UseFalloff)
            SetGridValue_Emitter_DestinationGrid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, In_GridAttributeIndex, Falloff * ScalarValueToUse, IGNORE);
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**Grid3D_Splat_Scalar*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
int GetNumCells_Emitter_DestinationGridOutput_NumCellsX;
int GetNumCells_Emitter_DestinationGridOutput_NumCellsY;
int GetNumCells_Emitter_DestinationGridOutput_NumCellsZ;
GetNumCells_Emitter_DestinationGrid(0, GetNumCells_Emitter_DestinationGridOutput_NumCellsX, GetNumCells_Emitter_DestinationGridOutput_NumCellsY, GetNumCells_Emitter_DestinationGridOutput_NumCellsZ);
bool Constant = false;
bool Constant1 = false;
CustomHlslDE94F33049E504C87DE76B8358A8903AEmitter_DestinationGrid_Func_(Context.Map.Module.AttributeIndex, Context.Map.Module.FloatIndex, Context.Map.Module.ParticleIndexRadius, Context.Map.Module.ScalarValue, GetNumCells_Emitter_DestinationGridOutput_NumCellsX, GetNumCells_Emitter_DestinationGridOutput_NumCellsY, GetNumCells_Emitter_DestinationGridOutput_NumCellsZ, Context.Map.Module.IndexVelocity, Context.Map.Module.IndexVelocityMagnitude, Context.Map.Module.StreakDensity, Context.Map.Module.PreviousParticleIndexRadius, Context.Map.Module.MaxStreakSamples, Constant, Constant1, Context);
ExitStatScope(/**Grid3D_Splat_Scalar*/);
EnterStatScope(1 /**Grid3D_Splat_Scalar_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Module.AttributeIndex = Module_AttributeIndex;
Context.Map.Module.FloatIndex = Module_FloatIndex;
Context.Map.Module.ParticleIndexRadius = Module_ParticleIndexRadius;
Context.Map.Module.ScalarValue = Module_ScalarValue;
Context.Map.Module.IndexVelocity = Module_IndexVelocity;
Context.Map.Module.IndexVelocityMagnitude = Module_IndexVelocityMagnitude;
Context.Map.Module.StreakDensity = Module_StreakDensity;
Context.Map.Module.PreviousParticleIndexRadius = Module_PreviousParticleIndexRadius;
Context.Map.Module.MaxStreakSamples = Module_MaxStreakSamples;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
EnterStatScope(2 /**Grid3D_Splat_Scalar_MapMain*/);
Simulate(Context);
ExitStatScope(/**Grid3D_Splat_Scalar_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Module.AttributeIndex);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Module.FloatIndex.x);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Module.FloatIndex.y);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Module.FloatIndex.z);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Module.IndexVelocity.x);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Module.IndexVelocity.y);
OutputDataFloat(0, 5, TmpWriteIndex, Context.Map.Module.IndexVelocity.z);
OutputDataFloat(0, 6, TmpWriteIndex, Context.Map.Module.IndexVelocityMagnitude);
OutputDataInt(0, 1, TmpWriteIndex, Context.Map.Module.MaxStreakSamples);
OutputDataFloat(0, 7, TmpWriteIndex, Context.Map.Module.ParticleIndexRadius);
OutputDataFloat(0, 8, TmpWriteIndex, Context.Map.Module.PreviousParticleIndexRadius);
OutputDataFloat(0, 9, TmpWriteIndex, Context.Map.Module.ScalarValue);
OutputDataFloat(0, 10, TmpWriteIndex, Context.Map.Module.StreakDensity);
ExitStatScope(/**Grid3D_Splat_Scalar_Main*/);
Áƒ*ž—ö¥€.;ÄÑ

