tQ>L¢»n;{.T*
=–Û4{ı=Bò;úﬁ@L˘—|
HêÎW;‡”8-
tQ>L¢»n;{.T*e
ÂCß;Â∏ÌÉ+n
;qù¶^Ö
7‘WÊÙOÆD™≥‹;ÓÁ+Ã
HdÓï;ÑÏÅz™z±«|
7‘WÊÙOÆD™≥‹;ÓÁ+Ã|
// Shader generated by Niagara HLSL Translator
int Index;
int AcquireTag;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
int Engine_PaddingInt32_2;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float3 DissipatedVector;
FParamMap0_OUTPUT_VAR_Module Module;
float DissipationRate;
float dt;
float3 VectorValue;
float Age;
int NumEmitters;
int NumEmittersAlive;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
int InstanceSeed;
int NumParticles;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Module Module;
FParamMap0_OUTPUT_VAR OUTPUT_VAR;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void NiagaraScript_2400_Func_(float In_dt, float In_DissipationRate, float3 In_VectorValue, out float3 Out_DissipatedVector, inout FSimulationContext Context);
float GetSpawnInterpolation();
float Result = In_dt * In_DissipationRate;
float Constant = 1;
float Result1 = Result + Constant;
float3 Result2 = In_VectorValue / Result1;
Out_DissipatedVector = Result2;
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**DissipateVector*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
float3 NiagaraScript_2400_Func_Output_DissipatedVector;
NiagaraScript_2400_Func_(Context.Map.Module.dt, Context.Map.Module.DissipationRate, Context.Map.Module.VectorValue, NiagaraScript_2400_Func_Output_DissipatedVector, Context);
Context.Map.OUTPUT_VAR.Module.DissipatedVector = NiagaraScript_2400_Func_Output_DissipatedVector;
ExitStatScope(/**DissipateVector*/);
EnterStatScope(1 /**DissipateVector_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
EnterStatScope(2 /**DissipateVector_MapMain*/);
Simulate(Context);
ExitStatScope(/**DissipateVector_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Module.DissipationRate);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Module.dt);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Module.VectorValue.x);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Module.VectorValue.y);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Module.VectorValue.z);
ExitStatScope(/**DissipateVector_Main*/);
| enter_stat_scope(C[624]);
| [R][0] = AcquireIndex(0, [C][628]);
| OutputDataFloat(0, 0, [R][0], [C][632]);
| OutputDataFloat(0, 1, [R][0], [C][632]);
| OutputDataFloat(0, 2, [R][0], [C][632]);
| OutputDataFloat(0, 3, [R][0], [C][632]);
| OutputDataFloat(0, 4, [R][0], [C][632]);
| exit_stat_scope();
¡É*ûóˆ•Ä.;ƒ—

