;(ÙSíö£oµ
ÃúÔéáû¡Øþué@GýÅü©@û‹ùT¹SþB”êwGž&ƒt;
    Texture3D VolumeTexture;
    SamplerState VolumeTextureSampler;
    float Albedo;
    float3 SunColor;
    float3 FillColor;
    float ConstantExtinction;
    float DensityOffset;
    float DensityRange;
    Texture2D DensityRamp;
    SamplerState DensityRampSampler;
    float DensityGain;
    float TemperatureOffset;
    float TemperatureRange;
    float UseTemperatureCurve;
    Texture2D TemperatureRamp;
    SamplerState TemperatureRampSampler;
    float TemperatureGain;
    float FireOpacityGain;
    float UseBlackbodyCurve;
    float UseDensityCurve;
    float UseColorTexture;
    Texture3D ColorTexture;
    SamplerState ColorTextureSampler;
    float3 LuminanceMult;
    // Computes volume extinction coefficient and luminance for a given point in the volume
    void ComputeStep(float3 Position, float3 RayDirection, out float OutExtinction, out float OutScattering, out float3 OutLuminance, out float OutEmissionExtinction , out float3 OutEmissionColor)
    float4 VolumeSample = VolumeTexture.SampleLevel(VolumeTextureSampler, Position, 0);
    float RemapDensity = DensityRange > 1e-8 ? saturate((VolumeSample.r - DensityOffset) / DensityRange) : 0.0;
    float DensityCurve = RemapDensity;
    if (UseDensityCurve)
        DensityCurve = DensityRamp.SampleLevel(DensityRampSampler, RemapDensity, 0 ).r;
    float SmokeExtinction = DensityCurve * DensityGain;
    OutExtinction = DensityCurve * DensityGain;
    OutExtinction += ConstantExtinction * (OutExtinction > 1e-5);
    OutLuminance = SunColor * VolumeSample.g;
    OutLuminance += FillColor * VolumeSample.a;    
    if (UseColorTexture)
        float3 ColorSample = ColorTexture.SampleLevel(ColorTextureSampler, Position, 0);
        OutLuminance *= ColorSample;
    OutLuminance *= LuminanceMult;
    OutScattering = OutExtinction * Albedo;
    float RemapTemperature = TemperatureRange > 1e-8 ? saturate((VolumeSample.b - TemperatureOffset) / TemperatureRange) : 0;
    float4 TemperatureCurve = RemapTemperature;
    if (UseTemperatureCurve)
        TemperatureCurve = TemperatureRamp.SampleLevel(TemperatureRampSampler, RemapTemperature, 0 );
    OutEmissionExtinction = TemperatureCurve.a * FireOpacityGain;
    if (UseBlackbodyCurve)
        const float MaxKelvin = 4500;
        OutEmissionColor = MaterialExpressionBlackBody(RemapTemperature * MaxKelvin) * TemperatureGain;
    else
        OutEmissionColor = TemperatureCurve.rgb * TemperatureGain;    
FireRampsRenderVolume Volume;
Volume.VolumeTexture = VolumeTexture;
Volume.VolumeTextureSampler = VolumeTextureSampler;
Volume.Albedo = Albedo;
Volume.SunColor = SunColor;
Volume.FillColor = FillColor;
Volume.ConstantExtinction = ConstantExtinction.r;
Volume.DensityOffset = DensityOffset;
Volume.DensityRange = DensityRange;
Volume.DensityRamp = DensityRamp;
Volume.DensityRampSampler = DensityRampSampler;
Volume.DensityGain = DensityGain;
Volume.TemperatureOffset = TemperatureOffset;
Volume.TemperatureRange = TemperatureRange;
Volume.UseTemperatureCurve = UseTemperatureCurve;
Volume.TemperatureRamp = TemperatureRamp;
Volume.TemperatureRampSampler = TemperatureRampSampler;
Volume.TemperatureGain = TemperatureGain;
Volume.FireOpacityGain = FireOpacityGain;
Volume.UseBlackbodyCurve = UseBlackbodyCurve;
Volume.UseDensityCurve = UseDensityCurve;
Volume.UseColorTexture = UseColorTexture;
Volume.ColorTexture = ColorTexture;
Volume.ColorTextureSampler = ColorTextureSampler;
Volume.LuminanceMult = LuminanceMult;
float4 ret;
MARCH_SINGLE_RAY_EMISSION(RayStart, RayDir, UnitStepSize, LocalStepSize, NumSteps, Volume, ret);
return ret;
    Texture3D NoiseTexture;
    SamplerState NoiseTextureSampler;
    Texture3D TexCoord1;
    SamplerState TexCoord1Sampler;
    Texture3D TexCoord2;
    SamplerState TexCoord2Sampler;
    float TexBlend;
    float TexScale;
    float TexFit_0;
    float TexFit_1;
    float TextureScale;
    float FitMin;
    float FitRange;
    float DebugTexture;
    float TextureSmoke;
    float TextureFire;
    float TextureSmokeColor;
    float TextureFireColor;
   OutLuminance *= LuminanceMult;
    float4 uvwa1 = TexCoord1.SampleLevel(TexCoord1Sampler, Position, 0);
    float3 uvw1  = frac(uvwa1.rgb * TextureScale);
    float Noise1 = NoiseTexture.SampleLevel(NoiseTextureSampler, uvw1, 0).r;
    float4 uvwa2 = TexCoord2.SampleLevel(TexCoord2Sampler, Position, 0);
    float3 uvw2  = frac(uvwa2.rgb * TextureScale);
    float Noise2 = Texture3DSample(NoiseTexture, NoiseTextureSampler, uvw2).r;
    float Noise = lerp(Noise1, Noise2, TexBlend);
    Noise = saturate((Noise - FitMin) / FitRange);
    Noise =  lerp(1.0, Noise, max(uvwa1.a, uvwa2.a));
    if (DebugTexture)
        OutLuminance = float3(1.0, 1.0, 1.0);
        OutExtinction += ConstantExtinction * (OutExtinction > 1e-5);
        OutScattering = OutExtinction * Noise;
        OutEmissionExtinction = 0.0;
        OutExtinction *= lerp(1.0, Noise, TextureSmoke);        
        OutScattering = OutExtinction * Albedo * lerp(1.0, Noise, TextureSmokeColor);
        OutEmissionExtinction *= lerp(1.0, Noise, TextureFire);
        OutEmissionColor *= lerp(1.0, Noise, TextureFireColor);
Volume.NoiseTexture = NoiseTexture;
Volume.NoiseTextureSampler = NoiseTextureSampler;
Volume.TexCoord1 = TexCoord1;
Volume.TexCoord1Sampler = TexCoord1Sampler;
Volume.TexCoord2 = TexCoord2;
Volume.TexCoord2Sampler = TexCoord2Sampler;
Volume.TexBlend = TexBlend;
Volume.TexScale = TexScale;
Volume.TexFit_0 = TexFit_0;
Volume.TexFit_1 = TexFit_1;
Volume.TextureScale = 1.0/TexScale;
Volume.FitMin   = TexFit_0;
Volume.FitRange = TexFit_1 - TexFit_0;
Volume.DebugTexture = DebugTexture;
Volume.TextureSmoke = TextureSmoke;
Volume.TextureFire = TextureFire;
Volume.TextureSmokeColor = TextureSmokeColor;
Volume.TextureFireColor = TextureFireColor;
Cû¼:MœaÞ4ˆ¤g(;
ìp±Yý;
š;Ÿ¡KK§˜ó>
Áƒ*ž—ö¥€.;ÄÑ

