 je˘AòàÀ
y;›{Gµê≤∫ty\
mÒmËëqG@Ö“‘0¨{ôπ;
ÖZ ;‰6
ÿ‰m%I∞(x;bç
ÿ‰m%I∞(x;bçÕ
BÜÌó;÷Ë˜Òˇ˚lhØ–lMüΩÄM∑”
BÜÌó;÷Ë˜Ò
J{;_ZèÊ
êF≠Ùx;*
ë;ìÊ¥Ê
JÑä†m¡;Bä¬tC
&°rL∂Hãú>6?¬;Ê
uoK≥Gïü;
R Måœ;t
;îäÊœÊ
3;Ñ5≥ì
3;Ñ5≥˛
// Shader generated by Niagara HLSL Translator
int Index;
int AcquireTag;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
int Engine_PaddingInt32_2;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
bool DrawBounds;
bool DrawResolutionGrid;
int NumCellsX;
int NumCellsY;
int NumCellsZ;
float ResolutionGridOffset;
float4 Rotation;
float4x4 UnitToWorld;
float3 Extents;
int GridCellsX;
int GridCellsY;
float3 GridCenter;
float2 GridExtents;
float4 GridRotation;
FParamMap0_Local_Module Module;
float Age;
int NumEmitters;
int NumEmittersAlive;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
int InstanceSeed;
int NumParticles;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Local Local;
FParamMap0_Module Module;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void NiagaraScript_216_Func_(float4x4 In_MATRIX_VAR, out float3 Out_Scale, inout FSimulationContext Context);
void DrawBox_Module_DebugDraw_UEImpureCall(int In_InstanceData, bool In_Execute, float3 In_Center, float4 In_Rotation, float3 In_Extents, float4 In_Color);
void NiagaraScript_217_Particle_Func_(float In_Value, out float Out_ClampedValue, inout FSimulationContext Context);
void DrawGrid2D_Module_DebugDraw_UEImpureCall(int In_InstanceData, bool In_Execute, float3 In_Center, float4 In_Rotation, float2 In_Extents, int In_NumCellsX, int In_NumCellsY, float4 In_Color);
float GetSpawnInterpolation();
float4 Row0;
float4 Row1;
float4 Row2;
float4 Row3;
Row0 = In_MATRIX_VAR[0];
Row1 = In_MATRIX_VAR[1];
Row2 = In_MATRIX_VAR[2];
Row3 = In_MATRIX_VAR[3];
float Result = length(Row0);
float Result1 = length(Row1);
float Result2 = length(Row2);
float3 Output1;
Output1.x = Result;
Output1.y = Result1;
Output1.z = Result2;
Out_Scale = Output1;
float Constant5 = 0;
float Constant6 = 1;
float Result5 = clamp(In_Value,Constant5,Constant6);
Out_ClampedValue = Result5;
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**Grid3D_DrawBoundsOverlay*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
float3 NiagaraScript_216_Func_Output_Scale;
NiagaraScript_216_Func_(Context.Map.Module.UnitToWorld, NiagaraScript_216_Func_Output_Scale, Context);
float3 Constant = float3(0.5,0.5,0.5);
float3 Result3 = NiagaraScript_216_Func_Output_Scale * Constant;
Context.Map.Local.Module.Rotation = Context.Map.Module.Rotation;
Context.Map.Local.Module.UnitToWorld = Context.Map.Module.UnitToWorld;
Context.Map.Local.Module.Extents = Result3;
float3 Constant1 = float3(0.5,0.5,0.5);
float3 Result4 = mul(float4(Constant1,1.0),Context.Map.Local.Module.UnitToWorld).xyz;
float4 Constant2 = float4(1,0,0,1);
DrawBox_Module_DebugDraw_UEImpureCall(0, Context.Map.Module.DrawBounds, Result4, Context.Map.Local.Module.Rotation, Context.Map.Local.Module.Extents, Constant2);
float Constant3 = 0.5;
float Constant4 = 0.5;
float NiagaraScript_217_Particle_Func_Output_ClampedValue;
NiagaraScript_217_Particle_Func_(Context.Map.Module.ResolutionGridOffset, NiagaraScript_217_Particle_Func_Output_ClampedValue, Context);
float3 Output11;
Output11.x = Constant3;
Output11.y = Constant4;
Output11.z = NiagaraScript_217_Particle_Func_Output_ClampedValue;
float3 Result6 = mul(float4(Output11,1.0),Context.Map.Local.Module.UnitToWorld).xyz;
Context.Map.Local.Module.GridCenter = Result6;
float X;
float Y;
float Z;
X = Context.Map.Local.Module.Extents.x;
Y = Context.Map.Local.Module.Extents.y;
Z = Context.Map.Local.Module.Extents.z;
float2 Output12;
Output12.x = X;
Output12.y = Y;
Context.Map.Local.Module.GridExtents = Output12;
Context.Map.Local.Module.GridRotation = Context.Map.Local.Module.Rotation;
Context.Map.Local.Module.GridCellsX = Context.Map.Module.NumCellsX;
Context.Map.Local.Module.GridCellsY = Context.Map.Module.NumCellsY;
float4 Constant7 = float4(0.5,0,0,1);
DrawGrid2D_Module_DebugDraw_UEImpureCall(0, Context.Map.Module.DrawResolutionGrid, Context.Map.Local.Module.GridCenter, Context.Map.Local.Module.GridRotation, Context.Map.Local.Module.GridExtents, Context.Map.Local.Module.GridCellsX, Context.Map.Local.Module.GridCellsY, Constant7);
ExitStatScope(/**Grid3D_DrawBoundsOverlay*/);
EnterStatScope(1 /**Grid3D_DrawBoundsOverlay_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
EnterStatScope(2 /**Grid3D_DrawBoundsOverlay_MapMain*/);
Simulate(Context);
ExitStatScope(/**Grid3D_DrawBoundsOverlay_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataBool(0, 0, TmpWriteIndex, Context.Map.Module.DrawBounds);
OutputDataBool(0, 1, TmpWriteIndex, Context.Map.Module.DrawResolutionGrid);
OutputDataInt(0, 2, TmpWriteIndex, Context.Map.Module.NumCellsX);
OutputDataInt(0, 3, TmpWriteIndex, Context.Map.Module.NumCellsY);
OutputDataInt(0, 4, TmpWriteIndex, Context.Map.Module.NumCellsZ);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Module.ResolutionGridOffset);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Module.Rotation.x);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Module.Rotation.y);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Module.Rotation.z);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Module.Rotation.w);
OutputDataFloat(0, 5, TmpWriteIndex, Context.Map.Module.UnitToWorld[0][0]);
OutputDataFloat(0, 6, TmpWriteIndex, Context.Map.Module.UnitToWorld[0][1]);
OutputDataFloat(0, 7, TmpWriteIndex, Context.Map.Module.UnitToWorld[0][2]);
OutputDataFloat(0, 8, TmpWriteIndex, Context.Map.Module.UnitToWorld[0][3]);
OutputDataFloat(0, 9, TmpWriteIndex, Context.Map.Module.UnitToWorld[1][0]);
OutputDataFloat(0, 10, TmpWriteIndex, Context.Map.Module.UnitToWorld[1][1]);
OutputDataFloat(0, 11, TmpWriteIndex, Context.Map.Module.UnitToWorld[1][2]);
OutputDataFloat(0, 12, TmpWriteIndex, Context.Map.Module.UnitToWorld[1][3]);
OutputDataFloat(0, 13, TmpWriteIndex, Context.Map.Module.UnitToWorld[2][0]);
OutputDataFloat(0, 14, TmpWriteIndex, Context.Map.Module.UnitToWorld[2][1]);
OutputDataFloat(0, 15, TmpWriteIndex, Context.Map.Module.UnitToWorld[2][2]);
OutputDataFloat(0, 16, TmpWriteIndex, Context.Map.Module.UnitToWorld[2][3]);
OutputDataFloat(0, 17, TmpWriteIndex, Context.Map.Module.UnitToWorld[3][0]);
OutputDataFloat(0, 18, TmpWriteIndex, Context.Map.Module.UnitToWorld[3][1]);
OutputDataFloat(0, 19, TmpWriteIndex, Context.Map.Module.UnitToWorld[3][2]);
OutputDataFloat(0, 20, TmpWriteIndex, Context.Map.Module.UnitToWorld[3][3]);
ExitStatScope(/**Grid3D_DrawBoundsOverlay_Main*/);
| enter_stat_scope(C[624]);
| enter_stat_scope(C[628]);
| enter_stat_scope(C[632]);
| DrawBox_Module_DebugDraw_UEImpureCall[func0](C[632], C[636], C[640], C[640], C[640], C[640], C[640], C[640], C[640], C[640], C[640], C[640], C[644], C[640], C[640], C[644]);
| DrawGrid2D_Module_DebugDraw_UEImpureCall[func1](C[632], C[636], C[640], C[640], C[640], C[640], C[640], C[640], C[640], C[640], C[640], C[632], C[632], C[648], C[640], C[640], C[644]);
| exit_stat_scope();
| [R][0] = AcquireIndex(0, [C][652]);
| OutputDataInt(0, 0, [R][0], [C][636]);
| OutputDataInt(0, 1, [R][0], [C][636]);
| OutputDataInt(0, 2, [R][0], [C][632]);
| OutputDataInt(0, 3, [R][0], [C][632]);
| OutputDataInt(0, 4, [R][0], [C][632]);
| OutputDataFloat(0, 0, [R][0], [C][640]);
| OutputDataFloat(0, 1, [R][0], [C][640]);
| OutputDataFloat(0, 2, [R][0], [C][640]);
| OutputDataFloat(0, 3, [R][0], [C][640]);
| OutputDataFloat(0, 4, [R][0], [C][640]);
| OutputDataFloat(0, 5, [R][0], [C][640]);
| OutputDataFloat(0, 6, [R][0], [C][640]);
| OutputDataFloat(0, 7, [R][0], [C][640]);
| OutputDataFloat(0, 8, [R][0], [C][640]);
| OutputDataFloat(0, 9, [R][0], [C][640]);
| OutputDataFloat(0, 10, [R][0], [C][640]);
| OutputDataFloat(0, 11, [R][0], [C][640]);
| OutputDataFloat(0, 12, [R][0], [C][640]);
| OutputDataFloat(0, 13, [R][0], [C][640]);
| OutputDataFloat(0, 14, [R][0], [C][640]);
| OutputDataFloat(0, 15, [R][0], [C][640]);
| OutputDataFloat(0, 16, [R][0], [C][640]);
| OutputDataFloat(0, 17, [R][0], [C][640]);
| OutputDataFloat(0, 18, [R][0], [C][640]);
| OutputDataFloat(0, 19, [R][0], [C][640]);
| OutputDataFloat(0, 20, [R][0], [C][640]);
¸ëØNµ‹P%Náw;Ê
V·R˜G;FNú¿Üo≤uÅòÊ
/;∂âä©´Kï
|WNé(xE£;E.O˙v
¡É*ûóˆ•Ä.;ƒ—

