qÒ‰0È9;A´t™Ë}µ»
ÿ;ºÉ5R
ôè¯ÏñO5©Çö;•n
wõ©∂Îâ-[ïÎ◊Ò;
;E˜9—‘
rU˘ë≥ª;π
µe°;˝L∫z"{˙
≠G∏;—O
ﬁ;®J´A]
Fû XØ4Ë_//
ëÖ;ü>=-N©
j@ëg—…Ÿ;
≤™cZ_Cí\;
;¬ÒÒEª
M;„uÓÎ»Må†e
wr»;z,mEãfˆ
¸¥gq‘ÚôOí;
;[]eL∏m¬u
àŸC¶œ;'q˚Ohã
àŸC¶œ;'q˚Ohí
∂ÙµO≥;3Yx‘(Ç
E¨Ñõ;ôGK2
[;w‹ÊC÷M´Wƒ;ÃQ√H
@;x§ù.DAàÔ«;–Ë
Z;Öj6sêO¢øÍky@‰»
\≤ﬂﬁ1;ıM°&´“ C…z
É;LßA^%Ÿ¸ª
6;G«XN¶ yΩ¥}√/õÌ—!ë}
6;G«XN¶ yΩ¥}√/
¨©8¢H3Iø nUGÎ&+‡h†qy;0I¢ù€ˆ≤lÜ\R[L<hKáGæÆÑ
‡h†qy;0I¢ù€ˆ≤lÜ\
™;MYÀD∫s·–
;ﬁoß/*ûOÑ
ÅµéLPl;¨ÖY…
TÕ;oËÌQMÉÛmàáXxD
l;¨ÖY…
˝‘WXÚ7äF•Wﬂ–;ow"«
˝‘WXÚ7äF•Wﬂ–;ow"
;ßÄ«\~@ûSØ}@üı«
âiFã/&Ø;™∑ˆ«
âiFã/&Ø;™∑ˆ
E¨Ñõ;ôGK2…
E¨Ñõ;ôGK2∫
[;w‹ÊC÷M´Wƒ;ÃQ√HÕ
[;w‹ÊC÷M´Wƒ;ÃQ√H∫
5\´Ô;O≠yÄç‚LÒ&Õ
5\´Ô;O≠yÄç‚LÒ&
˘FCüö‡Èz«;)Y
˘FCüö‡Èz«;)
'ªÙú¬Ù;Nê
åójÕVJØ;ueßä%€÷
åójÕVJØ;ueßä%€
·4∑„ë»-@ó´;['J
)Õ`ä;πmDÇ–
ej;æïDâã–Y
Nˇ¡ë7„mN∂ƒGñR;
¯éºÖ≤‚ìGºÍ˜‰^;~
Fë$;a’[
⁄;Æ_CD∞—Opwd
µ˜Œuº;nEâﬂj>R
˚C„[;aQBà&8∞
;◊X≤B∏N
Z;Öj6sêO¢øÍky@‰»«
TÕ;oËÌQMÉÛmàáXxDÙ
;ßÄ«\~@ûSØ}@üı«Ò
¯˚ç2;±§HæO}ê
‡Á¸Œ˙åBF∞π;/
ñ8~.Ô;
™Ø ;LCå5â©zÍMø
›;-ÒJ¢§S/¿
àŸC¶œ;'q˚Oh
Ôõ>÷;±
˛AqˇQ@–I±õ5;
Bà;r‚=µç¶x
ˇ†LœZ;Ár
öu˝i+;Î>£7ò
// Shader generated by Niagara HLSL Translator
// Compile Data> Static Variables Input: 
// Compile Data> PinToConstantValues Input: 
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
int Emitter_MaxSecondaryParticlesPerFrame;
float Emitter_DeltaTime;
int Emitter_SimGrid_VelocityIndex;
float Emitter_dx;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_EmissionMult;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_MinEmitVorticity;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_MaxEmitVorticity;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_MinEmitVelocityMagnitude;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_MaxEmitVelocityMagnitude;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_VorticityEmissionMult;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_VelocityEmissionMult;
float2 Constants_Emitter_Grid3D_Secondary_EmissionPoints_EmissionClamp;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_SDFMinValue;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_SDFMaxValue;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_MinEmitAccelMagnitude;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_MaxEmitAccelMagnitude;
float Constants_Emitter_Grid3D_Secondary_EmissionPoints_AccelEmissionMult;
float3 Position;
float2 SpriteSize;
float3 Velocity;
float Age;
float4 DynamicMaterialParameter;
NiagaraID ID;
float Lifetime;
float NormalizedAge;
FParamMap0_Particles_Previous Previous;
int State;
int UniqueID;
int MaxSecondaryParticlesPerFrame;
float SimDt;
float SimDx;
int VelocityIndex;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
float dx;
int SimGrid_VelocityIndex;
int Position;
int SpriteSize;
int Velocity;
int Age;
int DynamicMaterialParameter;
int Lifetime;
int NormalizedAge;
FParamMap0_Array_Previous Previous;
FParamMap0_Array Array;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Grid3D_Secondary_EmissionPoints Grid3D_Secondary_EmissionPoints;
FParamMap0_Particles Particles;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void ExecutionIndexToGridIndex_Emitter_SimGridReader(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void GetGridValue_Emitter_SimGridReader(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, out float Out_Value);
void CustomHlslC2451B4447760A1C39E5C78CDDE6210DEmitter_SimGridReader_Func_(float In_dx, int In_VectorIndex, int In_IndexX, int In_IndexY, int In_IndexZ, out float3 Out_curl);
void ExecutionIndexToUnit_Emitter_SimGridReader(int In_InstanceData, out float3 Out_Unit);
void SamplePreviousGridFloatValue_Emitter_SDFReader_AttributeSDF(int In_InstanceData, float3 In_Unit, out float Out_Value);
void GetPreviousVectorValue_Emitter_SimGridReader_AttributeVelocity(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, out float3 Out_Value);
void SetParticleNeighborCount_Emitter_EmissionCounter(int In_InstanceData, int In_LINEAR_VAR, int In_Increment, out int Out_PrevNeighborCount);
void GetNumCells_Emitter_EmissionPositions(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY);
void SetGridValue_Emitter_EmissionPositions(int In_InstanceData, int In_IndexX, int In_IndexY, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
void CustomHlslE90B28724F48FACA96FA8EBD8193338AEmitter_EmissionCounterEmitter_EmissionPositions_Func_(int In_IndexX, int In_IndexY, int In_IndexZ, float In_SimDt, float In_EmissionMult, float In_VorticityMagnitude, float In_MinEmitVorticity, float In_MaxEmitVorticity, int In_MaxSecondaryParticlesPerFrame, float3 In_CurrUnit, float In_SDFValue, float In_MinEmitVelocityMagnitude, float In_MaxEmitVelocityMagnitude, float In_VelocityMagnitude, float In_VorticityEmissionMult, float In_VelocityEmissionMult, float In_Random0To1, float2 In_EmissionClamp, float In_SDFMinValue, float In_SDFMaxValue, float In_AccelMagnitude, float In_MinEmitAccelMagnitude, float In_MaxEmitAccelMagnitude, float In_AccelEmissionMult, inout FSimulationContext Context);
void Grid3D_Secondary_EmissionPoints_Emitter_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
float Vz_up;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY+1, In_IndexZ, In_VectorIndex+2, Vz_up);
float Vz_down;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY-1, In_IndexZ, In_VectorIndex+2, Vz_down);
float Vy_front;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY, In_IndexZ+1, In_VectorIndex+1, Vy_front);
float Vy_back;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY, In_IndexZ-1, In_VectorIndex+1, Vy_back);
float Vx_front;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY, In_IndexZ+1, In_VectorIndex, Vx_front);
float Vx_back;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY, In_IndexZ-1, In_VectorIndex, Vx_back);
float Vz_right;
GetGridValue_Emitter_SimGridReader(2, In_IndexX+1, In_IndexY, In_IndexZ, In_VectorIndex+2, Vz_right);
float Vz_left;
GetGridValue_Emitter_SimGridReader(2, In_IndexX-1, In_IndexY, In_IndexZ, In_VectorIndex+2, Vz_left);
float Vy_right;
GetGridValue_Emitter_SimGridReader(2, In_IndexX+1, In_IndexY, In_IndexZ, In_VectorIndex+1, Vy_right);
float Vy_left;
GetGridValue_Emitter_SimGridReader(2, In_IndexX+1, In_IndexY, In_IndexZ, In_VectorIndex+1, Vy_left);
float Vx_up;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY+1, In_IndexZ, In_VectorIndex, Vx_up);
float Vx_down;
GetGridValue_Emitter_SimGridReader(2, In_IndexX, In_IndexY-1, In_IndexZ, In_VectorIndex, Vx_down);
) / (2. * In_dx);
// Emit
float EmitVal = 0;
EmitVal += In_VorticityEmissionMult * smoothstep(In_MinEmitVorticity, In_MaxEmitVorticity, In_VorticityMagnitude);
EmitVal += In_VelocityEmissionMult * smoothstep(In_MinEmitVelocityMagnitude, In_MaxEmitVelocityMagnitude, In_VelocityMagnitude);
EmitVal += In_AccelEmissionMult * smoothstep(In_MinEmitAccelMagnitude, In_MaxEmitAccelMagnitude, In_AccelMagnitude);
EmitVal = clamp(EmitVal * In_EmissionMult, In_EmissionClamp.x, In_EmissionClamp.y);
int NumEmitted = 0;
NumEmitted = floor(EmitVal) + (frac(EmitVal) >= In_Random0To1 ? 1 : 0);
// increment emission buffer by OutGridVal
int2 NumCells;
GetNumCells_Emitter_EmissionPositions(1, NumCells.x, NumCells.y);
  float PrevVal = 0;
  SetParticleNeighborCount_Emitter_EmissionCounter(0, 0, NumEmitted, PrevVal);
  // initialized to -1, so make sure it is 0 for the first time we add particles
  PrevVal = max(0, PrevVal);  
  for (int i = PrevVal; i < NumEmitted + PrevVal &&  i < In_MaxSecondaryParticlesPerFrame; ++i)
      int d = 0;
      int xx = i % NumCells.x;
      int yy = i / NumCells.x;
      SetGridValue_Emitter_EmissionPositions(1, xx, yy, 0, In_CurrUnit.x, d);
      SetGridValue_Emitter_EmissionPositions(1, xx, yy, 1, In_CurrUnit.y, d);
      SetGridValue_Emitter_EmissionPositions(1, xx, yy, 2, In_CurrUnit.z, d);
int ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexX;
int ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexY;
int ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexZ;
ExecutionIndexToGridIndex_Emitter_SimGridReader(2, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexX, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexY, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexZ);
//SetConstantByStaticVariable "/Grid 3D Secondary Emission Points/Map Get/Map Get->Module.Emit From Velocity"
int Constant = 1;
//SetConstantByStaticVariable "/Grid 3D Secondary Emission Points/Map Get/Map Get->Module.Emit From Acceleration"
int Constant1 = 0;
//SetConstantByStaticVariable "/Grid 3D Secondary Emission Points/Map Get/Map Get->Module.Emit From Vorticity"
int Constant2 = 1;
int ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexX1;
int ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexY1;
int ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexZ1;
ExecutionIndexToGridIndex_Emitter_SimGridReader(2, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexX1, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexY1, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexZ1);
float3 CustomHlslC2451B4447760A1C39E5C78CDDE6210DEmitter_SimGridReader_Func_Output_curl;
CustomHlslC2451B4447760A1C39E5C78CDDE6210DEmitter_SimGridReader_Func_(Context.Map.Grid3D_Secondary_EmissionPoints.SimDx, Context.Map.Grid3D_Secondary_EmissionPoints.VelocityIndex, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexX1, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexY1, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexZ1, CustomHlslC2451B4447760A1C39E5C78CDDE6210DEmitter_SimGridReader_Func_Output_curl);
float Result = length(CustomHlslC2451B4447760A1C39E5C78CDDE6210DEmitter_SimGridReader_Func_Output_curl);
float3 ExecutionIndexToUnit_Emitter_SimGridReaderOutput_Unit;
ExecutionIndexToUnit_Emitter_SimGridReader(2, ExecutionIndexToUnit_Emitter_SimGridReaderOutput_Unit);
float SamplePreviousGridFloatValue_Emitter_SDFReader_AttributeSDFOutput_Value;
SamplePreviousGridFloatValue_Emitter_SDFReader_AttributeSDF(3, ExecutionIndexToUnit_Emitter_SimGridReaderOutput_Unit, SamplePreviousGridFloatValue_Emitter_SDFReader_AttributeSDFOutput_Value);
float3 GetPreviousVectorValue_Emitter_SimGridReader_AttributeVelocityOutput_Value;
GetPreviousVectorValue_Emitter_SimGridReader_AttributeVelocity(2, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexX1, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexY1, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexZ1, GetPreviousVectorValue_Emitter_SimGridReader_AttributeVelocityOutput_Value);
float Result1 = length(GetPreviousVectorValue_Emitter_SimGridReader_AttributeVelocityOutput_Value);
float Constant3 = 1;
float Result2 = rand_float(Constant3);
float Constant4 = 0;
CustomHlslE90B28724F48FACA96FA8EBD8193338AEmitter_EmissionCounterEmitter_EmissionPositions_Func_(ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexX, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexY, ExecutionIndexToGridIndex_Emitter_SimGridReaderOutput_IndexZ, Context.Map.Grid3D_Secondary_EmissionPoints.SimDt, Constants_Emitter_Grid3D_Secondary_EmissionPoints_EmissionMult, Result, Constants_Emitter_Grid3D_Secondary_EmissionPoints_MinEmitVorticity, Constants_Emitter_Grid3D_Secondary_EmissionPoints_MaxEmitVorticity, Context.Map.Grid3D_Secondary_EmissionPoints.MaxSecondaryParticlesPerFrame, ExecutionIndexToUnit_Emitter_SimGridReaderOutput_Unit, SamplePreviousGridFloatValue_Emitter_SDFReader_AttributeSDFOutput_Value, Constants_Emitter_Grid3D_Secondary_EmissionPoints_MinEmitVelocityMagnitude, Constants_Emitter_Grid3D_Secondary_EmissionPoints_MaxEmitVelocityMagnitude, Result1, Constants_Emitter_Grid3D_Secondary_EmissionPoints_VorticityEmissionMult, Constants_Emitter_Grid3D_Secondary_EmissionPoints_VelocityEmissionMult, Result2, Constants_Emitter_Grid3D_Secondary_EmissionPoints_EmissionClamp, Constants_Emitter_Grid3D_Secondary_EmissionPoints_SDFMinValue, Constants_Emitter_Grid3D_Secondary_EmissionPoints_SDFMaxValue, Constant4, Constants_Emitter_Grid3D_Secondary_EmissionPoints_MinEmitAccelMagnitude, Constants_Emitter_Grid3D_Secondary_EmissionPoints_MaxEmitAccelMagnitude, Constants_Emitter_Grid3D_Secondary_EmissionPoints_AccelEmissionMult, Context);
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**SimulationStage_0*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
Context.Map.Grid3D_Secondary_EmissionPoints.MaxSecondaryParticlesPerFrame = Context.Map.Emitter.MaxSecondaryParticlesPerFrame;
Context.Map.Grid3D_Secondary_EmissionPoints.SimDt = Context.Map.Emitter.DeltaTime;
Context.Map.Grid3D_Secondary_EmissionPoints.VelocityIndex = Context.Map.Emitter.SimGrid_VelocityIndex;
Context.Map.Grid3D_Secondary_EmissionPoints.SimDx = Context.Map.Emitter.dx;
EnterStatScope(1 /**Grid3D_Secondary_EmissionPoints_Emitter_Func_*/);
Grid3D_Secondary_EmissionPoints_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_Secondary_EmissionPoints_Emitter_Func_*/);
ExitStatScope(/**SimulationStage_0*/);
EnterStatScope(2 /**SimulationStage_0_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Emitter.MaxSecondaryParticlesPerFrame = Emitter_MaxSecondaryParticlesPerFrame;
Context.Map.Emitter.DeltaTime = Emitter_DeltaTime;
Context.Map.Emitter.SimGrid_VelocityIndex = Emitter_SimGrid_VelocityIndex;
Context.Map.Emitter.dx = Emitter_dx;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = 0;
EnterStatScope(3 /**SimulationStage_0_MapMain*/);
Simulate(Context);
ExitStatScope(/**SimulationStage_0_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
UpdateID(0, Context.Map.Particles.ID.Index, TmpWriteIndex);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Particles.Age);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Particles.DynamicMaterialParameter.x);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Particles.DynamicMaterialParameter.y);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Particles.DynamicMaterialParameter.z);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Particles.DynamicMaterialParameter.w);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Particles.ID.Index);
OutputDataInt(0, 1, TmpWriteIndex, Context.Map.Particles.ID.AcquireTag);
OutputDataFloat(0, 5, TmpWriteIndex, Context.Map.Particles.Lifetime);
OutputDataFloat(0, 6, TmpWriteIndex, Context.Map.Particles.NormalizedAge);
OutputDataFloat(0, 7, TmpWriteIndex, Context.Map.Particles.Position.x);
OutputDataFloat(0, 8, TmpWriteIndex, Context.Map.Particles.Position.y);
OutputDataFloat(0, 9, TmpWriteIndex, Context.Map.Particles.Position.z);
OutputDataFloat(0, 10, TmpWriteIndex, Context.Map.Particles.Previous.Position.x);
OutputDataFloat(0, 11, TmpWriteIndex, Context.Map.Particles.Previous.Position.y);
OutputDataFloat(0, 12, TmpWriteIndex, Context.Map.Particles.Previous.Position.z);
OutputDataFloat(0, 13, TmpWriteIndex, Context.Map.Particles.Previous.SpriteSize.x);
OutputDataFloat(0, 14, TmpWriteIndex, Context.Map.Particles.Previous.SpriteSize.y);
OutputDataFloat(0, 15, TmpWriteIndex, Context.Map.Particles.Previous.Velocity.x);
OutputDataFloat(0, 16, TmpWriteIndex, Context.Map.Particles.Previous.Velocity.y);
OutputDataFloat(0, 17, TmpWriteIndex, Context.Map.Particles.Previous.Velocity.z);
OutputDataFloat(0, 18, TmpWriteIndex, Context.Map.Particles.SpriteSize.x);
OutputDataFloat(0, 19, TmpWriteIndex, Context.Map.Particles.SpriteSize.y);
OutputDataInt(0, 2, TmpWriteIndex, Context.Map.Particles.State);
OutputDataInt(0, 3, TmpWriteIndex, Context.Map.Particles.UniqueID);
OutputDataFloat(0, 20, TmpWriteIndex, Context.Map.Particles.Velocity.x);
OutputDataFloat(0, 21, TmpWriteIndex, Context.Map.Particles.Velocity.y);
OutputDataFloat(0, 22, TmpWriteIndex, Context.Map.Particles.Velocity.z);
ExitStatScope(/**SimulationStage_0_Main*/);
”ÿswKª;
 N´}`„à/;ê
6ZN∞&;˛Œ
ôMG∞Îçnó;…ı
 óé4;g˛Añ
t;–Lô˛g…
¡É*ûóˆ•Ä.;ƒ—

