wFª:na^;Zâ*
¸/®?;©*
§≠DìúÌ;˚´J,¶
§≠DìúÌ;˚´J,•
^ ›_ºäôÌ;Ë
™x—L≈;8Nìµ
AÉª3I‡¡;°*
Iï…O†;
ÅKé.p˝ß|Ùƒ;
n˙P‹ŸY;
;BKàÃÁñ
;Hö©I˝uÎx
float BoundingSphereRadius = length(.5 * Scale);
SpriteWidth = 2. * BoundingSphereRadius;
float3 CameraToGridCenter = GridCenterPos - CameraPos;
float DistToGridCenter = length(CameraToGridCenter);
    SpritePos = GridCenterPos;
    float3 RayDir = CameraToGridCenter / DistToGridCenter;
    //SpritePos = GridCenterPos - BoundingSphereRadius * RayDir;
;˝ó+/≥@à-\râS´wA
;˝ó+/≥@à-\râS´w_
+å;∑c0XGô
ˆ&óŸ ;ÛOä
ÁúwÿFeÚMåZ5;:ñQ˚D
ÁúwÿFeÚMåZ5;:ñQ˚õ
°;ÿ%t⁄RC±
∂⁄G;ÎÖN@®Ã
‰S∫Ì=M9O†<ù.Ü;mîÑ
ÿB†;[®d
 zI¶[§7‚e®=6
¸ëØNµ‹P%Náw;L
EÉ©N}í.;œ¡
é_;¿⁄ƒˆAôYøm$
‰S∫Ì=M9O†<ù.Ü;mî~
v„©«4≥∆DÆMÑ°Çó˚;'
wr»;z,mEãfˆ
¸¥gq‘ÚôOí;
E¯ˇà1$ôDÇ;
∂ÙµO≥;3Yx‘(Ç'
òµ$Mö;Å˘DTmi*
;<BBùp…˙jÜ§K&
∂gmZÁ; D¨™€W˜
ˇÏ#Nf;uN£⁄ıoï#Ÿg*
W©Mó;ÉÂ'7[õ
~æ£O;ˆ∑B∞ÿqvK≤âm'
˛ﬁx≠dAÜwﬁd_Ø;ø*
;∂ØFDüπ‚…E
;˝ó+/≥@à-\râS´w
ôñRÁÂ};L≠xá
&3rˇPT≈;»Cã¯
2©˚Qù°Ì;L∞®·Ïπ[^
©˚Qù°Ì;L∞®·Ïπ[^
+^%Q´;ã
+^%Q´;*
;êÒ6Fˇ F´ï7|
9P`ù@Ö;U
k¡™rJû;4xÛﬂs>*
¡;EJãﬂI≥î±<
¡;EJãﬂI≥î±<’*
W©Mó;ÉÂ'7[õ°
W©Mó;ÉÂ'7[õª
¬;‡◊AÖLÜmb%Wy*
@LX7ƒOÜ;ˆøÈÏÍÿH7yÌ
@LX7ƒOÜ;ˆøÈÏÍÿ
c…∆;`Î
®˛‘Q¢ÖªAú/]=˘$¢;Òky
®˛‘Q¢ÖªAú/]=˘$¢;
$;-≈‚*
XJ≤ø;¿
XJ≤ø;Õ
T;¢aœœ<HûMÖ†ø]ñS
ÁúwÿFeÚMåZ5;:ñQ˚
6;õ]àò2D§
T;¢aœœ<HûMÖ†ø]ñSÃ
T;¢aœœ<HûMÖ†ø]ñSª
˜;˜TI≠È
;ñq®¶-ÀAôâ
WÚ–eé›8Ißª¿;
Ôõ>÷;±*
Bà;r‚=µç¶f
;ihh¥p=Â˘›*
// Shader generated by Niagara HLSL Translator
// Compile Data> Static Variables Input: 
// Compile Data> PinToConstantValues Input: 
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float4x4 Emitter_UnitToLocal;
float4x4 Emitter_WorldToLocal;
bool Emitter_IsLocalSpace;
float4x4 Emitter_LocalToUnit;
float Emitter_dx;
int UniqueID;
float4 RasterizedColor;
float RasterizedDensity;
float RasterizedDistance;
float RasterizedTemperature;
float3 RasterizedTextureCoord;
float3 RasterizedVelocity;
FParamMap0_OUTPUT_VAR_Grid3D_Gas_GatherParticleSource Grid3D_Gas_GatherParticleSource;
int Channel;
float3 VECTOR_VAR;
float4 LinearColor;
float4 Value;
FParamMap0_Local_Grid3D_SetRTValues Grid3D_SetRTValues;
FParamMap0_Local_Grid3D_SetRTValues001 Grid3D_SetRTValues001;
float Alpha;
float Blue;
float Green;
float Red;
int CompositingMethod;
float dx;
bool IsLocalSpace;
float4x4 LocalToUnit;
float4x4 UnitToLocal;
float4x4 WorldToLocal;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
FParamMap0_Array Array;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Grid3D_Gas_GatherParticleSource Grid3D_Gas_GatherParticleSource;
FParamMap0_Grid3D_SetRTValues Grid3D_SetRTValues;
FParamMap0_Grid3D_SetRTValues001 Grid3D_SetRTValues001;
FParamMap0_Local Local;
FParamMap0_MakeFloatFromLinearColor MakeFloatFromLinearColor;
FParamMap0_MakeFloatFromLinearColor001 MakeFloatFromLinearColor001;
FParamMap0_MakeFloatFromLinearColor002 MakeFloatFromLinearColor002;
FParamMap0_MakeFloatFromLinearColor003 MakeFloatFromLinearColor003;
FParamMap0_MakeFloatFromVector MakeFloatFromVector;
FParamMap0_MakeFloatFromVector001 MakeFloatFromVector001;
FParamMap0_MakeFloatFromVector002 MakeFloatFromVector002;
FParamMap0_OUTPUT_VAR OUTPUT_VAR;
FParamMap0_Particles Particles;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void GetRenderTargetSize_Emitter_SimRT(int In_InstanceData, out int Out_Width, out int Out_Height, out int Out_Depth);
void ExecToIndex_Emitter_SimRT(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_(int In_Width, int In_Height, int In_Depth, int In_IndexX, int In_IndexY, int In_IndexZ, out bool Out_ret);
void ExecToUnit_Emitter_SimRT(int In_InstanceData, out float3 Out_Unit);
void GetNumParticles_Emitter_Reader(int In_InstanceData, out int Out_NumParticles);
void GetVectorByIndex_Emitter_Reader_AttributePosition(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_radius(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Emitter_Reader_AttributeRestPosition(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetQuaternionByIndex_Emitter_Reader_AttributeMeshOrientation(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_density(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetFloatByIndex_Emitter_Reader_Attributefluids_source_temperature(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float Out_Value);
void GetVectorByIndex_Emitter_Reader_Attributefluids_source_velocity(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void GetColorByIndex_Emitter_Reader_Attributefluids_source_color(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float4 Out_Value);
void CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_(float3 In_CellGridLocalPos, float In_VelocityMult, float In_DensityMult, int In_NumParticles, float4x4 In_WorldToLocal, float In_RadiusScale, float In_TemperatureMult, float In_VelocityRadiusMult, int In_CompositingMethod, float4x4 In_LocalToUnit, float In_dx, float3 In_UnitCoord, out float Out_DensityOut, out float3 Out_VelocityOut, out float Out_TemperatureOut, out float3 Out_TextureCoordOut, out float Out_DistanceOut, out float4 Out_ColorOut);
void Grid3D_Gas_GatherParticleSource_Emitter_Func_(inout FSimulationContext Context);
void NiagaraScript_2788_Particle_Func_(float3 In_VECTOR_VAR, int In_TargetChannel, out float Out_Float, inout FSimulationContext Context);
void MakeFloatFromVector_Emitter_Func_(out float Out_Float, inout FSimulationContext Context);
void MakeFloatFromVector001_Emitter_Func_(out float Out_Float, inout FSimulationContext Context);
void MakeFloatFromVector002_Emitter_Func_(out float Out_Float, inout FSimulationContext Context);
void SetRenderTargetValue_Emitter_SimRT_UEImpureCall(int In_InstanceData, bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
void Grid3D_SetRTValues_Emitter_Func_(inout FSimulationContext Context);
void NiagaraScript_2790_Particle_Func_(float4 In_FLOAT4_VAR, int In_TargetChannel, out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor001_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor002_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void MakeFloatFromLinearColor003_Emitter_Func_(out float Out_NewOutput, inout FSimulationContext Context);
void ExecToIndex_Emitter_AttrRT(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void SetRenderTargetValue_Emitter_AttrRT_UEImpureCall(int In_InstanceData, bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
void Grid3D_SetRTValues001_Emitter_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
// included from ../../Plugins/FX/Niagara/Shaders/Private/NiagaraCommon.ush
// Copyright Epic Games, Inc. All Rights Reserved.
float x2 = Q.x + Q.x;  float y2 = Q.y + Q.y;  float z2 = Q.z + Q.z;
float xx = Q.x * x2;   float xy = Q.x * y2;   float xz = Q.x * z2;
float yy = Q.y * y2;   float yz = Q.y * z2;   float zz = Q.z * z2;
float wx = Q.w * x2;   float wy = Q.w * y2;   float wz = Q.w * z2;
return Mat;
0.0f, 0.0f, S.z);
float3x3 ScaleRot = mul(ScaleMat, R);
T, 1.0f);
return MakeLWCMatrix(LWCGetTile(T), NiagaraComposeTransformMatrix(S, R, T.Offset));
0.0f, 0.0f, 1.0f / S.z);
float3x3 InvRotScale = mul(transpose(R), InvScaleMat);
-T, 1.0f);
return mul(InvTransMat, InvRotScale44);
return MakeLWCInverseMatrix(LWCGetTile(T), NiagaraComposeInvTransformMatrix(S, R, T.Offset));
float W = dot(A, B);
float4 Quat;
   A.z * B.x - A.x * B.z,
   A.x * B.y - A.y * B.x,
   W);
W = 0.f;
: float4(0.f, -A.z, A.y, W);
return NiagaraQuatTo3x3(Quat);
float4 Rc = Quat * float4(-1, -1, -1, 1);
return NiagaraQuatMul(Quat, NiagaraQuatMul(float4(Vector, 0), Rc)).xyz;
In_IndexX < In_Width - 1 && In_IndexY < In_Height - 1 && In_IndexZ < In_Depth - 1;
Out_DensityOut = 0;
Out_VelocityOut = 0;
Out_TemperatureOut = 0;
Out_TextureCoordOut = 0;
Out_DistanceOut = 1000000;
Out_ColorOut = float4(0,0,0,0);
float TotalWeight = 0;
int NumOverlapParticles = 0;
bool Valid;
for (int CurrIdx = 0; CurrIdx < In_NumParticles; ++CurrIdx)
float3 ParticlePos;
GetVectorByIndex_Emitter_Reader_AttributePosition(1, CurrIdx, Valid, ParticlePos);
float3 ParticleGridLocalPos = mul(float4(ParticlePos, 1.), In_WorldToLocal).xyz;
float Radius = 0.0;
GetFloatByIndex_Emitter_Reader_Attributefluids_source_radius(1, CurrIdx, Valid, Radius);
float Dist = length(In_CellGridLocalPos - ParticleGridLocalPos);
float ParticleRadius = Radius * In_RadiusScale;
    float ParticleDensity = 0;
    float ParticleTemperature = 0;
    float3 ParticleVel = float3(0, 0, 0);
    float ParticleDivergence = 0;
    float4 ParticleColor = 0;
        float3 ParticleRestPos;
        GetVectorByIndex_Emitter_Reader_AttributeRestPosition(1, CurrIdx, Valid, ParticleRestPos);
float3 ParticleGridLocalRestPos = mul(float4(ParticleRestPos, 1.), In_WorldToLocal).xyz;
        float4 MeshOrientation;
        GetQuaternionByIndex_Emitter_Reader_AttributeMeshOrientation(1, CurrIdx, Valid, MeshOrientation);
        GetFloatByIndex_Emitter_Reader_Attributefluids_source_density(1, CurrIdx, Valid, ParticleDensity);
        ParticleDensity *= In_DensityMult;
        GetFloatByIndex_Emitter_Reader_Attributefluids_source_temperature(1, CurrIdx, Valid, ParticleTemperature);
        ParticleTemperature *= In_TemperatureMult;
        GetVectorByIndex_Emitter_Reader_Attributefluids_source_velocity(1, CurrIdx, Valid, ParticleVel);
        ParticleVel = mul(float4(ParticleVel, 0.), In_WorldToLocal).xyz * In_VelocityMult;
        GetColorByIndex_Emitter_Reader_Attributefluids_source_color(1, CurrIdx, Valid, ParticleColor);
        float3 TextureGridLocalPos = In_CellGridLocalPos - ParticleGridLocalPos - ParticleGridLocalRestPos;
        TextureGridLocalPos = NiagaraQuatRotateVector(MeshOrientation, TextureGridLocalPos);
        float Weight = 1. - smoothstep(0, ParticleRadius+3*In_dx, Dist);
        Out_TextureCoordOut += mul(float4(TextureGridLocalPos, 1.), In_LocalToUnit).xyz * Weight;
        Out_ColorOut += ParticleColor * Weight;
        TotalWeight += Weight;
        float CurrDist = clamp((Dist - ParticleRadius) / In_dx, -3, 3);
        Out_DistanceOut = min(Out_DistanceOut, CurrDist);
        NumOverlapParticles++;
        if (In_CompositingMethod == 0)
            Out_DensityOut += ParticleDensity;
            Out_TemperatureOut += ParticleTemperature;
            Out_VelocityOut += ParticleVel;
        else if (In_CompositingMethod == 1)
            Out_DensityOut = max(Out_DensityOut, ParticleDensity);
            Out_TemperatureOut = max(Out_TemperatureOut, ParticleTemperature);
            if (dot(ParticleVel, ParticleVel) > dot(Out_VelocityOut, Out_VelocityOut))
                Out_VelocityOut = ParticleVel;
//    TextureCoordOut = float3(0,0,0);
   // DistanceOut = 1000;
    Out_TextureCoordOut /= TotalWeight;
    Out_ColorOut /= TotalWeight;
#endif //GPU_SIMULATION
float Constant6 = 1;
float Constant7 = 1;
float Constant8 = 1;
float Constant9 = 1;
float Constant10 = 1;
int GetRenderTargetSize_Emitter_SimRTOutput_Width;
int GetRenderTargetSize_Emitter_SimRTOutput_Height;
int GetRenderTargetSize_Emitter_SimRTOutput_Depth;
GetRenderTargetSize_Emitter_SimRT(0, GetRenderTargetSize_Emitter_SimRTOutput_Width, GetRenderTargetSize_Emitter_SimRTOutput_Height, GetRenderTargetSize_Emitter_SimRTOutput_Depth);
int ExecToIndex_Emitter_SimRTOutput_IndexX;
int ExecToIndex_Emitter_SimRTOutput_IndexY;
int ExecToIndex_Emitter_SimRTOutput_IndexZ;
ExecToIndex_Emitter_SimRT(0, ExecToIndex_Emitter_SimRTOutput_IndexX, ExecToIndex_Emitter_SimRTOutput_IndexY, ExecToIndex_Emitter_SimRTOutput_IndexZ);
bool CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_Output_ret;
CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_(GetRenderTargetSize_Emitter_SimRTOutput_Width, GetRenderTargetSize_Emitter_SimRTOutput_Height, GetRenderTargetSize_Emitter_SimRTOutput_Depth, ExecToIndex_Emitter_SimRTOutput_IndexX, ExecToIndex_Emitter_SimRTOutput_IndexY, ExecToIndex_Emitter_SimRTOutput_IndexZ, CustomHlsl06DFB86B4B5D1C86031F729E00CADD9D_Func_Output_ret);
float3 ExecToUnit_Emitter_SimRTOutput_Unit;
ExecToUnit_Emitter_SimRT(0, ExecToUnit_Emitter_SimRTOutput_Unit);
float3 Result = mul(float4(ExecToUnit_Emitter_SimRTOutput_Unit,1.0),Context.Map.Grid3D_Gas_GatherParticleSource.UnitToLocal).xyz;
int GetNumParticles_Emitter_ReaderOutput_NumParticles;
GetNumParticles_Emitter_Reader(1, GetNumParticles_Emitter_ReaderOutput_NumParticles);
float4 Constant11 = float4(1,0,0,0);
float4 Constant12 = float4(0,1,0,0);
float4 Constant13 = float4(0,0,1,0);
float4 Constant14 = float4(0,0,0,1);
float4x4 Output1;
Output1[0] = Constant11;
Output1[1] = Constant12;
Output1[2] = Constant13;
Output1[3] = Constant14;
float4x4 Constant15 = (float4x4)0;
float4x4 NiagaraMatrix_SelectResult = Constant15;
NiagaraMatrix_SelectResult = Output1;
NiagaraMatrix_SelectResult = Context.Map.Grid3D_Gas_GatherParticleSource.WorldToLocal;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DensityOut;
float3 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_VelocityOut;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TemperatureOut;
float3 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TextureCoordOut;
float CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DistanceOut;
float4 CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_ColorOut;
CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_(Result, Constant6, Constant7, GetNumParticles_Emitter_ReaderOutput_NumParticles, NiagaraMatrix_SelectResult, Constant8, Constant9, Constant10, Context.Map.Grid3D_Gas_GatherParticleSource.CompositingMethod, Context.Map.Grid3D_Gas_GatherParticleSource.LocalToUnit, Context.Map.Grid3D_Gas_GatherParticleSource.dx, ExecToUnit_Emitter_SimRTOutput_Unit, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DensityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_VelocityOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TemperatureOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TextureCoordOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DistanceOut, CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_ColorOut);
float Constant16 = 0;
float3 Constant17 = float3(0,0,0);
float Constant18 = 0;
float3 Constant19 = float3(0,0,0);
float Constant20 = 10000;
float4 Constant21 = float4(1,1,1,1);
float Constant22 = (0.0);
float NiagaraFloat_SelectResult1 = Constant22;
float3 Constant23 = float3(0.0, 0.0, 0.0);
float3 Vector3f_SelectResult1 = Constant23;
float Constant24 = (0.0);
float NiagaraFloat001_SelectResult1 = Constant24;
float3 Constant25 = float3(0.0, 0.0, 0.0);
float3 Vector3f001_SelectResult1 = Constant25;
float Constant26 = (0.0);
float NiagaraFloat002_SelectResult1 = Constant26;
float4 Constant27 = float4(1.0, 1.0, 1.0, 1.0);
float4 LinearColor_SelectResult1 = Constant27;
NiagaraFloat_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DensityOut;
Vector3f_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_VelocityOut;
NiagaraFloat001_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TemperatureOut;
Vector3f001_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_TextureCoordOut;
NiagaraFloat002_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_DistanceOut;
LinearColor_SelectResult1 = CustomHlsl1BAE7DF54A4BB78A269BB2995C6C72A8Emitter_Reader_Func_Output_ColorOut;
NiagaraFloat_SelectResult1 = Constant16;
Vector3f_SelectResult1 = Constant17;
NiagaraFloat001_SelectResult1 = Constant18;
Vector3f001_SelectResult1 = Constant19;
NiagaraFloat002_SelectResult1 = Constant20;
LinearColor_SelectResult1 = Constant21;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDensity = NiagaraFloat_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedVelocity = Vector3f_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTemperature = NiagaraFloat001_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord = Vector3f001_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDistance = NiagaraFloat002_SelectResult1;
Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor = LinearColor_SelectResult1;
float X;
float Y;
float Z;
X = In_VECTOR_VAR.x;
Y = In_VECTOR_VAR.y;
Z = In_VECTOR_VAR.z;
float Constant31 = (0.0);
float NiagaraFloat_SelectResult2 = Constant31;
NiagaraFloat_SelectResult2 = X;
NiagaraFloat_SelectResult2 = Y;
NiagaraFloat_SelectResult2 = Z;
Out_Float = NiagaraFloat_SelectResult2;
float NiagaraScript_2788_Particle_Func_Output_Float;
NiagaraScript_2788_Particle_Func_(Context.Map.MakeFloatFromVector.VECTOR_VAR, Context.Map.MakeFloatFromVector.Channel, NiagaraScript_2788_Particle_Func_Output_Float, Context);
Out_Float = NiagaraScript_2788_Particle_Func_Output_Float;
float NiagaraScript_2788_Particle_Func_Output_Float1;
NiagaraScript_2788_Particle_Func_(Context.Map.MakeFloatFromVector001.VECTOR_VAR, Context.Map.MakeFloatFromVector001.Channel, NiagaraScript_2788_Particle_Func_Output_Float1, Context);
Out_Float = NiagaraScript_2788_Particle_Func_Output_Float1;
float NiagaraScript_2788_Particle_Func_Output_Float2;
NiagaraScript_2788_Particle_Func_(Context.Map.MakeFloatFromVector002.VECTOR_VAR, Context.Map.MakeFloatFromVector002.Channel, NiagaraScript_2788_Particle_Func_Output_Float2, Context);
Out_Float = NiagaraScript_2788_Particle_Func_Output_Float2;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.Enable"
int Constant32 = 1;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.SetFromVector"
int Constant33 = 0;
float4 Output11;
Output11.r = Context.Map.Grid3D_SetRTValues.Red;
Output11.g = Context.Map.Grid3D_SetRTValues.Green;
Output11.b = Context.Map.Grid3D_SetRTValues.Blue;
Output11.a = Context.Map.Grid3D_SetRTValues.Alpha;
Context.Map.Local.Grid3D_SetRTValues.Value = Output11;
bool Constant34 = true;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.UseIterationGrid"
int Constant35 = 0;
int ExecToIndex_Emitter_SimRTOutput_IndexX1;
int ExecToIndex_Emitter_SimRTOutput_IndexY1;
int ExecToIndex_Emitter_SimRTOutput_IndexZ1;
ExecToIndex_Emitter_SimRT(0, ExecToIndex_Emitter_SimRTOutput_IndexX1, ExecToIndex_Emitter_SimRTOutput_IndexY1, ExecToIndex_Emitter_SimRTOutput_IndexZ1);
SetRenderTargetValue_Emitter_SimRT_UEImpureCall(0, Constant34, ExecToIndex_Emitter_SimRTOutput_IndexX1, ExecToIndex_Emitter_SimRTOutput_IndexY1, ExecToIndex_Emitter_SimRTOutput_IndexZ1, Context.Map.Local.Grid3D_SetRTValues.Value);
float X1;
float Y1;
float Z1;
float W;
X1 = In_FLOAT4_VAR.x;
Y1 = In_FLOAT4_VAR.y;
Z1 = In_FLOAT4_VAR.z;
W = In_FLOAT4_VAR.w;
float Constant40 = (0.0);
float NiagaraFloat_SelectResult3 = Constant40;
NiagaraFloat_SelectResult3 = X1;
NiagaraFloat_SelectResult3 = Y1;
NiagaraFloat_SelectResult3 = Z1;
NiagaraFloat_SelectResult3 = W;
Out_NewOutput = NiagaraFloat_SelectResult3;
int ENiagaraVector4_Channels;
ENiagaraVector4_Channels = Context.Map.MakeFloatFromLinearColor.Channel;
float NiagaraScript_2790_Particle_Func_Output_NewOutput;
NiagaraScript_2790_Particle_Func_(Context.Map.MakeFloatFromLinearColor.LinearColor, ENiagaraVector4_Channels, NiagaraScript_2790_Particle_Func_Output_NewOutput, Context);
Out_NewOutput = NiagaraScript_2790_Particle_Func_Output_NewOutput;
int ENiagaraVector4_Channels1;
ENiagaraVector4_Channels1 = Context.Map.MakeFloatFromLinearColor001.Channel;
float NiagaraScript_2790_Particle_Func_Output_NewOutput1;
NiagaraScript_2790_Particle_Func_(Context.Map.MakeFloatFromLinearColor001.LinearColor, ENiagaraVector4_Channels1, NiagaraScript_2790_Particle_Func_Output_NewOutput1, Context);
Out_NewOutput = NiagaraScript_2790_Particle_Func_Output_NewOutput1;
int ENiagaraVector4_Channels2;
ENiagaraVector4_Channels2 = Context.Map.MakeFloatFromLinearColor002.Channel;
float NiagaraScript_2790_Particle_Func_Output_NewOutput2;
NiagaraScript_2790_Particle_Func_(Context.Map.MakeFloatFromLinearColor002.LinearColor, ENiagaraVector4_Channels2, NiagaraScript_2790_Particle_Func_Output_NewOutput2, Context);
Out_NewOutput = NiagaraScript_2790_Particle_Func_Output_NewOutput2;
int ENiagaraVector4_Channels3;
ENiagaraVector4_Channels3 = Context.Map.MakeFloatFromLinearColor003.Channel;
float NiagaraScript_2790_Particle_Func_Output_NewOutput3;
NiagaraScript_2790_Particle_Func_(Context.Map.MakeFloatFromLinearColor003.LinearColor, ENiagaraVector4_Channels3, NiagaraScript_2790_Particle_Func_Output_NewOutput3, Context);
Out_NewOutput = NiagaraScript_2790_Particle_Func_Output_NewOutput3;
//SetConstantByStaticVariable "/Grid 3D Set RTValues 001/Map Get/Map Get->Module.Enable"
int Constant41 = 1;
//SetConstantByStaticVariable "/Grid 3D Set RTValues 001/Map Get/Map Get->Module.SetFromVector"
int Constant42 = 0;
float4 Output12;
Output12.r = Context.Map.Grid3D_SetRTValues001.Red;
Output12.g = Context.Map.Grid3D_SetRTValues001.Green;
Output12.b = Context.Map.Grid3D_SetRTValues001.Blue;
Output12.a = Context.Map.Grid3D_SetRTValues001.Alpha;
Context.Map.Local.Grid3D_SetRTValues001.Value = Output12;
bool Constant43 = true;
//SetConstantByStaticVariable "/Grid 3D Set RTValues 001/Map Get/Map Get->Module.UseIterationGrid"
int Constant44 = 0;
int ExecToIndex_Emitter_AttrRTOutput_IndexX;
int ExecToIndex_Emitter_AttrRTOutput_IndexY;
int ExecToIndex_Emitter_AttrRTOutput_IndexZ;
ExecToIndex_Emitter_AttrRT(3, ExecToIndex_Emitter_AttrRTOutput_IndexX, ExecToIndex_Emitter_AttrRTOutput_IndexY, ExecToIndex_Emitter_AttrRTOutput_IndexZ);
SetRenderTargetValue_Emitter_AttrRT_UEImpureCall(3, Constant43, ExecToIndex_Emitter_AttrRTOutput_IndexX, ExecToIndex_Emitter_AttrRTOutput_IndexY, ExecToIndex_Emitter_AttrRTOutput_IndexZ, Context.Map.Local.Grid3D_SetRTValues001.Value);
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**SimulationStage_0*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
int Constant = 1;
Context.Map.Grid3D_Gas_GatherParticleSource.UnitToLocal = Context.Map.Emitter.UnitToLocal;
Context.Map.Grid3D_Gas_GatherParticleSource.WorldToLocal = Context.Map.Emitter.WorldToLocal;
Context.Map.Grid3D_Gas_GatherParticleSource.IsLocalSpace = Context.Map.Emitter.IsLocalSpace;
Context.Map.Grid3D_Gas_GatherParticleSource.LocalToUnit = Context.Map.Emitter.LocalToUnit;
Context.Map.Grid3D_Gas_GatherParticleSource.dx = Context.Map.Emitter.dx;
Context.Map.Grid3D_Gas_GatherParticleSource.CompositingMethod = Constant;
float Constant1 = 1;
float Constant2 = 1;
float Constant3 = 1;
float Constant4 = 1;
float Constant5 = 1;
EnterStatScope(1 /**Grid3D_Gas_GatherParticleSource_Emitter_Func_*/);
Grid3D_Gas_GatherParticleSource_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_Gas_GatherParticleSource_Emitter_Func_*/);
int Constant28 = 1;
int Constant29 = 2;
Context.Map.MakeFloatFromVector.VECTOR_VAR = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.Map.MakeFloatFromVector001.VECTOR_VAR = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.Map.MakeFloatFromVector002.VECTOR_VAR = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedTextureCoord;
Context.Map.MakeFloatFromVector001.Channel = Constant28;
Context.Map.MakeFloatFromVector002.Channel = Constant29;
int Constant30 = 0;
Context.Map.MakeFloatFromVector.Channel = Constant30;
float MakeFloatFromVector_Emitter_Func_Output_Float;
MakeFloatFromVector_Emitter_Func_(MakeFloatFromVector_Emitter_Func_Output_Float, Context);
float MakeFloatFromVector001_Emitter_Func_Output_Float;
MakeFloatFromVector001_Emitter_Func_(MakeFloatFromVector001_Emitter_Func_Output_Float, Context);
float MakeFloatFromVector002_Emitter_Func_Output_Float;
MakeFloatFromVector002_Emitter_Func_(MakeFloatFromVector002_Emitter_Func_Output_Float, Context);
Context.Map.Grid3D_SetRTValues.Red = MakeFloatFromVector_Emitter_Func_Output_Float;
Context.Map.Grid3D_SetRTValues.Green = MakeFloatFromVector001_Emitter_Func_Output_Float;
Context.Map.Grid3D_SetRTValues.Blue = MakeFloatFromVector002_Emitter_Func_Output_Float;
Context.Map.Grid3D_SetRTValues.Alpha = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedDistance;
EnterStatScope(2 /**Grid3D_SetRTValues_Emitter_Func_*/);
Grid3D_SetRTValues_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_SetRTValues_Emitter_Func_*/);
int Constant36 = 1;
int Constant37 = 2;
int Constant38 = 3;
Context.Map.MakeFloatFromLinearColor.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor001.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor002.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor003.LinearColor = Context.Map.OUTPUT_VAR.Grid3D_Gas_GatherParticleSource.RasterizedColor;
Context.Map.MakeFloatFromLinearColor001.Channel = Constant36;
Context.Map.MakeFloatFromLinearColor002.Channel = Constant37;
Context.Map.MakeFloatFromLinearColor003.Channel = Constant38;
int Constant39 = 0;
Context.Map.MakeFloatFromLinearColor.Channel = Constant39;
float MakeFloatFromLinearColor_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor_Emitter_Func_(MakeFloatFromLinearColor_Emitter_Func_Output_NewOutput, Context);
float MakeFloatFromLinearColor001_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor001_Emitter_Func_(MakeFloatFromLinearColor001_Emitter_Func_Output_NewOutput, Context);
float MakeFloatFromLinearColor002_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor002_Emitter_Func_(MakeFloatFromLinearColor002_Emitter_Func_Output_NewOutput, Context);
float MakeFloatFromLinearColor003_Emitter_Func_Output_NewOutput;
MakeFloatFromLinearColor003_Emitter_Func_(MakeFloatFromLinearColor003_Emitter_Func_Output_NewOutput, Context);
Context.Map.Grid3D_SetRTValues001.Red = MakeFloatFromLinearColor_Emitter_Func_Output_NewOutput;
Context.Map.Grid3D_SetRTValues001.Green = MakeFloatFromLinearColor001_Emitter_Func_Output_NewOutput;
Context.Map.Grid3D_SetRTValues001.Blue = MakeFloatFromLinearColor002_Emitter_Func_Output_NewOutput;
Context.Map.Grid3D_SetRTValues001.Alpha = MakeFloatFromLinearColor003_Emitter_Func_Output_NewOutput;
EnterStatScope(3 /**Grid3D_SetRTValues001_Emitter_Func_*/);
Grid3D_SetRTValues001_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_SetRTValues001_Emitter_Func_*/);
ExitStatScope(/**SimulationStage_0*/);
EnterStatScope(4 /**SimulationStage_0_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Emitter.UnitToLocal = Emitter_UnitToLocal;
Context.Map.Emitter.WorldToLocal = Emitter_WorldToLocal;
Context.Map.Emitter.IsLocalSpace = Emitter_IsLocalSpace;
Context.Map.Emitter.LocalToUnit = Emitter_LocalToUnit;
Context.Map.Emitter.dx = Emitter_dx;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = 0;
EnterStatScope(5 /**SimulationStage_0_MapMain*/);
Simulate(Context);
ExitStatScope(/**SimulationStage_0_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Particles.UniqueID);
ExitStatScope(/**SimulationStage_0_Main*/);
EnterStatScope(0 /**SpawnScript_0*/);
// Begin HandleMissingDefaultValues
// End HandleMissingDefaultValues
ExitStatScope(/**SpawnScript_0*/);
EnterStatScope(1 /**SpawnScript_0_Main*/);
Context.Map.Particles.UniqueID = 0;
Context.Map.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + ExecIndex();
EnterStatScope(2 /**SpawnScript_0_MapMain*/);
ExitStatScope(/**SpawnScript_0_MapMain*/);
ExitStatScope(/**SpawnScript_0_Main*/);
EnterStatScope(0 /**UpdateScript_1*/);
ExitStatScope(/**UpdateScript_1*/);
EnterStatScope(1 /**UpdateScript_1_Main*/);
Context.Map.Particles.UniqueID = InputDataInt(0, 0);
Context.Map.Array.UniqueID = 0;
EnterStatScope(2 /**UpdateScript_1_MapMain*/);
ExitStatScope(/**UpdateScript_1_MapMain*/);
ExitStatScope(/**UpdateScript_1_Main*/);
ˇ¶Z;JäéÉ’˙sæ∂*
E¥ÌOüEÎí;*
¡É*ûóˆ•Ä.;ƒ—

