m;P\MÐQ@è( Ô(¢Š
›®¦²n;
Texture3D VolumeTexture;
SamplerState VolumeTextureSampler;
float Albedo;
float3 SunColor;
float3 FillColor;
float ConstantExtinction;
    float DensityOffset;
    float DensityRange;
    Texture2D DensityRamp;
SamplerState DensityRampSampler;
    float DensityGain;
    float TemperatureOffset;
    float TemperatureRange;
    Texture2D TemperatureRamp;
SamplerState TemperatureRampSampler;
Texture3D AlbedoRampParam;
SamplerState AlbedoRampParamSampler;
Texture2D AlbedoRamp;
SamplerState AlbedoRampSampler;
// Computes volume extinction coefficient and luminance for a given point in the volume
    float4 VolumeSample = VolumeTexture.SampleLevel(VolumeTextureSampler, Position, 0);
    float Density = DensityRange > 1e-8 ? saturate((VolumeSample.r - DensityOffset) / DensityRange) : 0.0;
float DensityCurve = DensityRamp.SampleLevel(DensityRampSampler, Density, 0 ).r;
    OutExtinction = DensityCurve * DensityGain;
OutExtinction += ConstantExtinction * (OutExtinction > 1e-5);
    OutScattering = OutExtinction * Albedo;
    OutLuminance = SunColor * VolumeSample.g;
OutLuminance += FillColor * VolumeSample.a;
float AlbedoParam = AlbedoRampParam.SampleLevel(AlbedoRampParamSampler, Position, 0).r;
float3 AlbedoCurve = AlbedoRamp.SampleLevel(AlbedoRampSampler, AlbedoParam, 0).rgb;
OutLuminance *= AlbedoCurve;
float remap = TemperatureRange > 1e-8 ? saturate((VolumeSample.b - TemperatureOffset) / TemperatureRange) : 0;
float3 TemperatureCurve = TemperatureRamp.SampleLevel(TemperatureRampSampler, remap, 0 ).rgb;
OutLuminance += TemperatureCurve;
FireRampsRenderVolume Volume;
Volume.VolumeTexture = VolumeTexture;
Volume.VolumeTextureSampler = VolumeTextureSampler;
Volume.Albedo = Albedo;
Volume.SunColor = SunColor;
Volume.FillColor = FillColor;
Volume.ConstantExtinction = ConstantExtinction.r;
Volume.DensityOffset = DensityOffset;
Volume.DensityRange = DensityRange;
Volume.DensityRamp = DensityRamp;
Volume.DensityRampSampler = DensityRampSampler;
Volume.DensityGain = DensityGain;
Volume.TemperatureOffset = TemperatureOffset;
Volume.TemperatureRange = TemperatureRange;
Volume.TemperatureRamp = TemperatureRamp;
Volume.TemperatureRampSampler = TemperatureRampSampler;
Volume.AlbedoRampParam = AlbedoRampParam;
Volume.AlbedoRampParamSampler = AlbedoRampParamSampler;
Volume.AlbedoRamp = AlbedoRamp;
Volume.AlbedoRampSampler = AlbedoRampSampler;
float4 ret;
MARCH_SINGLE_RAY(RayStart, RayDir, UnitStepSize, LocalStepSize, NumSteps, Volume, ret);
return ret;
    Texture3D NoiseTexture;
    SamplerState NoiseTextureSampler;
    Texture3D TexCoord1;
    SamplerState TexCoord1Sampler;
    Texture3D TexCoord2;
    SamplerState TexCoord2Sampler;
    float TexBlend;
    float TexScale;
    float TexFit_0;
    float TexFit_1;
    float TextureScale;
    float FitMin;
    float FitRange;
    float4 uvwa1 = TexCoord1.SampleLevel(TexCoord1Sampler, Position, 0);
float3 uvw1  = frac(uvwa1.rgb * TextureScale);
float Noise1 = NoiseTexture.SampleLevel(NoiseTextureSampler, uvw1, 0).r;
    float4 uvwa2 = TexCoord2.SampleLevel(TexCoord2Sampler, Position, 0);
float3 uvw2  = frac(uvwa2.rgb * TextureScale);
float Noise2 = Texture3DSample(NoiseTexture, NoiseTextureSampler, uvw2).r;
float Noise = lerp(Noise1, Noise2, TexBlend);
Noise = saturate((Noise - FitMin) / FitRange);
    OutExtinction = DensityCurve * DensityGain * lerp(1.0, Noise, max(uvwa1.a, uvwa2.a));
OutExtinction += ConstantExtinction;
Volume.NoiseTexture = NoiseTexture;
Volume.NoiseTextureSampler = NoiseTextureSampler;
Volume.TexCoord1 = TexCoord1;
Volume.TexCoord1Sampler = TexCoord1Sampler;
Volume.TexCoord2 = TexCoord2;
Volume.TexCoord2Sampler = TexCoord2Sampler;
Volume.TexBlend = TexBlend;
Volume.TexScale = TexScale;
Volume.TexFit_0 = TexFit_0;
Volume.TexFit_1 = TexFit_1;
Volume.TextureScale = 1.0/TexScale;
Volume.FitMin   = TexFit_0;
Volume.FitRange = TexFit_1 - TexFit_0;
š;Ÿ¡KK§˜ó>
j´Í;O“¢
Áƒ*ž—ö¥€.;ÄÑ

