Aº;ÍàÁ
ÞJ½u&„kUã;@
ÞJ½u&„kUã;Æ
ÞJ½u&„kUã;
ÞJ½u&„kUã;ü
=PH¬rÐ;ˆ
J¶¡3¿û3dñÀ(ôCHŒõ·Œû~ÿœ;'”O
uõ¬FL¾²m›%ÁÜ5Oƒ^Cˆz;ëi,W
æÄ;+Eª‰³BÑIý
²m›%ÁÜ5Oƒ^Cˆz;ëi
// Shader generated by Niagara HLSL Translator
// Compile Data> PinToConstantValues Input: 
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
int Engine_System_PaddingInt32_2;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
int NumSteps;
float WaterHeight;
float3 WorldGridExtents;
float WorldScale;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int PaddingInt32_2;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
int InstanceSeed;
int NumParticles;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
float dx;
float NumSteps;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Module Module;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void GetNumCells_Module_Grid(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY, out int Out_NumCellsZ);
float GetSpawnInterpolation();
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**NiagaraScript_114*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
//SetConstantByStaticVariable "/Map Get->Module.Local Space Water Height"
int Constant = 0;
float X;
float Y;
float Z;
X = Context.Map.Module.WorldGridExtents.x;
Y = Context.Map.Module.WorldGridExtents.y;
Z = Context.Map.Module.WorldGridExtents.z;
int GetNumCells_Module_GridOutput_NumCellsX;
int GetNumCells_Module_GridOutput_NumCellsY;
int GetNumCells_Module_GridOutput_NumCellsZ;
GetNumCells_Module_Grid(0, GetNumCells_Module_GridOutput_NumCellsX, GetNumCells_Module_GridOutput_NumCellsY, GetNumCells_Module_GridOutput_NumCellsZ);
float Result = X / GetNumCells_Module_GridOutput_NumCellsX;
float Result1 = Result * Context.Map.Module.WorldScale;
Context.Map.Emitter.dx = Result1;
Context.Map.Emitter.WaterHeight = Context.Map.Module.WaterHeight;
Context.Map.Emitter.NumSteps = Context.Map.Module.NumSteps;
ExitStatScope(/**NiagaraScript_114*/);
EnterStatScope(1 /**NiagaraScript_114_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
EnterStatScope(2 /**NiagaraScript_114_MapMain*/);
Simulate(Context);
ExitStatScope(/**NiagaraScript_114_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Module.NumSteps);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Module.WaterHeight);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Module.WorldGridExtents.x);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Module.WorldGridExtents.y);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Module.WorldGridExtents.z);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Module.WorldScale);
ExitStatScope(/**NiagaraScript_114_Main*/);
| enter_stat_scope(C[640]);
| enter_stat_scope(C[644]);
| enter_stat_scope(C[648]);
| exit_stat_scope();
| [R][0] = AcquireIndex(0, [C][652]);
| OutputDataInt(0, 0, [R][0], [C][648]);
| OutputDataFloat(0, 0, [R][0], [C][656]);
| OutputDataFloat(0, 1, [R][0], [C][656]);
| OutputDataFloat(0, 2, [R][0], [C][656]);
| OutputDataFloat(0, 3, [R][0], [C][656]);
| OutputDataFloat(0, 4, [R][0], [C][656]);
Áƒ*ž—ö¥€.;ÄÑ

