´ŸšUC…€˜¢Œ;7Tˆ
´ŸšUC…€˜¢Œ;7T‡
h;"eŒş
@¢ì;"İ
¯&?Gµm;³õ%
Ú1qH€ Ş;Stİ}
Ú1qH€ Ş;Stİ}î
Iªvÿbˆ;H¸Pt¬.X
v!rœÓVJ ‡;hÒõ®Ö
I6J‡oy ;-^_Ç
òlWÅ;2K¯ÚÍ)æ7Ä#Ê
–‘;ÏËd6V'I£=uäN1„8åı‹œT1èA‡Á_8´UµN
ìßÁÛdX;@ 
¸t¡ƒ{ËNª[;•é´ÓÇ
UÇ @»;?§(À®
 ÒğíqS;Nµ¦±
s¡F«N‡½‚¡+ˆèÎ;
ånJ%×ìJ¥Ó!;ö
// Shader generated by Niagara HLSL Translator
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float4 fluids_source_color;
float fluids_source_density;
float fluids_source_divergence;
float fluids_source_previous_radius;
float fluids_source_radius;
float fluids_source_temperature;
float3 fluids_source_velocity;
float4 Color;
float3 DataChannelPosition;
float Density;
float Divergence;
float Radius;
float Temperature;
float3 Velocity;
float VelocityScale;
float3 WorldPosition;
float3 WorldVelocity;
FParamMap0_Local_Module Module;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
int fluids_source_color;
int fluids_source_density;
int fluids_source_divergence;
int fluids_source_previous_radius;
int fluids_source_radius;
int fluids_source_temperature;
int fluids_source_velocity;
FParamMap0_Array Array;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Local Local;
FParamMap0_Module Module;
FParamMap0_Particles Particles;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
float GetSpawnInterpolation();
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**SetFluidSourceAttributes*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
float Constant = 0;
Context.Map.Particles.fluids_source_radius = Constant;
Context.Map.Particles.fluids_source_previous_radius = Context.Map.Particles.fluids_source_radius;
float3 Result = Context.Map.Module.Velocity * Context.Map.Module.VelocityScale;
Context.Map.Particles.fluids_source_velocity = Result;
Context.Map.Particles.fluids_source_radius = Context.Map.Module.Radius;
Context.Map.Particles.fluids_source_density = Context.Map.Module.Density;
Context.Map.Particles.fluids_source_temperature = Context.Map.Module.Temperature;
Context.Map.Particles.fluids_source_divergence = Context.Map.Module.Divergence;
Context.Map.Particles.fluids_source_color = Context.Map.Module.Color;
Context.Map.Local.Module.WorldPosition = Context.Map.Module.DataChannelPosition;
Context.Map.Local.Module.WorldVelocity = Context.Map.Particles.fluids_source_velocity;
ExitStatScope(/**SetFluidSourceAttributes*/);
EnterStatScope(1 /**SetFluidSourceAttributes_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = -1;
EnterStatScope(2 /**SetFluidSourceAttributes_MapMain*/);
Simulate(Context);
ExitStatScope(/**SetFluidSourceAttributes_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Module.Color.r);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Module.Color.g);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Module.Color.b);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Module.Color.a);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Module.DataChannelPosition.x);
OutputDataFloat(0, 5, TmpWriteIndex, Context.Map.Module.DataChannelPosition.y);
OutputDataFloat(0, 6, TmpWriteIndex, Context.Map.Module.DataChannelPosition.z);
OutputDataFloat(0, 7, TmpWriteIndex, Context.Map.Module.Density);
OutputDataFloat(0, 8, TmpWriteIndex, Context.Map.Module.Divergence);
OutputDataFloat(0, 9, TmpWriteIndex, Context.Map.Module.Radius);
OutputDataFloat(0, 10, TmpWriteIndex, Context.Map.Module.Temperature);
OutputDataFloat(0, 11, TmpWriteIndex, Context.Map.Module.Velocity.x);
OutputDataFloat(0, 12, TmpWriteIndex, Context.Map.Module.Velocity.y);
OutputDataFloat(0, 13, TmpWriteIndex, Context.Map.Module.Velocity.z);
OutputDataFloat(0, 14, TmpWriteIndex, Context.Map.Module.VelocityScale);
ExitStatScope(/**SetFluidSourceAttributes_Main*/);
| enter_stat_scope(C[640]);
| [R][0] = AcquireIndex(0, [C][644]);
| OutputDataFloat(0, 0, [R][0], [C][648]);
| OutputDataFloat(0, 1, [R][0], [C][648]);
| OutputDataFloat(0, 2, [R][0], [C][648]);
| OutputDataFloat(0, 3, [R][0], [C][648]);
| OutputDataFloat(0, 4, [R][0], [C][648]);
| OutputDataFloat(0, 5, [R][0], [C][648]);
| OutputDataFloat(0, 6, [R][0], [C][648]);
| OutputDataFloat(0, 7, [R][0], [C][648]);
| OutputDataFloat(0, 8, [R][0], [C][648]);
| OutputDataFloat(0, 9, [R][0], [C][648]);
| OutputDataFloat(0, 10, [R][0], [C][648]);
| OutputDataFloat(0, 11, [R][0], [C][648]);
| OutputDataFloat(0, 12, [R][0], [C][648]);
| OutputDataFloat(0, 13, [R][0], [C][648]);
| OutputDataFloat(0, 14, [R][0], [C][648]);
| exit_stat_scope();
tğ‘1‚;FN¦9
KU;A°>Òıv<,ÁÊ
bïÇÙz—ÉI¤T¥•;
Áƒ*—ö¥€.;ÄÑ

