±k;Š~w
‚ ;Zş<
TurbulenceOut = float3(0, 0, 0);
  float scale = NoiseScale;
  float3 pos = World;
  float x = FastGradientPerlinNoise3D_TEX(pos*scale + Time*NoiseSpeed);
  pos += float3(123.45, 234.56, 345.67);
  float y = FastGradientPerlinNoise3D_TEX(pos*scale + Time*NoiseSpeed);
  pos += float3(-987.65, -876.54, -765.43);
  float z = FastGradientPerlinNoise3D_TEX(pos*scale + Time*NoiseSpeed);
  TurbulenceOut = (float3(x, y, z) + Bias) * Gain;
Œ#‹"à;H€¡Y
Gain = 0.0;
UseBand = false;
// Don't use the band if the min/max are the same.
     UseBand = true;
    if( Density >= DensityBand.x && Density <= DensityBand.y ) 
        Gain = DensityGain;      
    if( Temperature >= TemperatureBand.x && Temperature <= TemperatureBand.y ) 
        Gain = TemperatureGain;      
:U‡F¼;‹úìíû
    if( Mode > 0 ) // Ramp
        Gain = saturate((GridValue-ValueRange.x) / (ValueRange.y-ValueRange.x));  
    else if( GridValue >= ValueRange.x && GridValue <= ValueRange.y ) // Band
        Gain = 1.0;  
;´DíÁÛ
¯;ı9:áLŒcÔ×w-ğ
¯;ı9:áLŒcÔ×w-ğH
€;•Ÿ8û‡@Š©!aÌğ¡
¯;ı9:áLŒcÔ×w-ğ"
Hmœ™5-ÆAŠ;ÀRJ¹Å
Y\İL»úğ€Ü,";Õ
³+áéà;
0·‡:wO°L[;WÒQ¶Û
Š§\>;C¶
G,˜¤²;J–ªä/Y
ö‚8;8‹
Eíb~y@ºõö;@÷D"r
Eíb~y@ºõö;@÷D"
Eíb~y@ºõö;@÷D"u
Eíb~y@ºõö;@÷D"x
ÛFU\;6òH½
RßN¾;i|
Ÿ¯€;mç
Eíb~y@ºõö;@÷D"}
Eíb~y@ºõö;@÷D"†
«IºÊ;AEN™.$ñ
ô;h¡ˆ
÷;è#)À)@ªÛ[­6tf‹Õ
ê¥ò;æ6Bº
K•=õœ;6q—Õ
E³ËF‚`&“Ÿ>•;Õ
¢b>D‘û;Dz
ô;h¡ˆ3
ô;h¡ˆ7
ô;h¡ˆ;
­ìëH·$åİi³o¶;
ô;h¡ˆ?
;|(ƒKª`›7ÅVµâÛ
ô;h¡ˆD
h;w6Ğ0êB»ÏÔÚDÙ
ÿ LÏZ;çr
_\›=›):;lú<
<İU-a1\;
// Shader generated by Niagara HLSL Translator
// Compile Data> PinToConstantValues Input: 
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float3 Turbulence;
FParamMap0_OUTPUT_VAR_Module Module;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_OUTPUT_VAR OUTPUT_VAR;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
float GetSpawnInterpolation();
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**Grid3D_Turbulence*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
//SetConstantByStaticVariable "/Map Get/Map Get->Module.Calculate Turbulence"
int Constant = 0;
float3 Constant1 = float3(0,0,0);
Context.Map.OUTPUT_VAR.Module.Turbulence = Constant1;
ExitStatScope(/**Grid3D_Turbulence*/);
EnterStatScope(1 /**Grid3D_Turbulence_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
EnterStatScope(2 /**Grid3D_Turbulence_MapMain*/);
Simulate(Context);
ExitStatScope(/**Grid3D_Turbulence_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
ExitStatScope(/**Grid3D_Turbulence_Main*/);
p¯]¥t;WJ½¯9ü´ÈÑSÛ
Í1';0¨K°áW;{ë(
Áƒ*—ö¥€.;ÄÑ

