Ìc;µ:f∏
„Ñ˘C§åÖGò;≤¥¿¥
s;Á…n`=K§
ù;Oá)[yÓŒtµˇ
eLŒXïΩD$≥kaiô-Õ«‘Ÿ¿;∏
£es;¢+¸D≥üw:Uâ¶o
0ò«;5ﬁH¨MT¯çyJ
Uè›;‘]ÍO∂/ˇg
ÚŒ‚à;Ö•§e∏
‚L´‹:¢;mç1
óH∫úÏ;
 h[í|F®ó˜7¯M†8
ÊC—g;»
Æ◊;XBä∏≈
*;≥zf¡k
–_;Ü%P®Ë
íÊ";íQ
‘}(^;ñaHµì
˙-≠E;ë
º∫¸ñM©;fW
Bò %Ã#ÛÜé;
G¢^>i;I±
oG<eÛÏ;K©P<i£†ùÑµ
âBL∂π9Hæ£[!;
≤2xFî(B;˜NÔjµ
ﬁJΩu&ÑkU„;Ë
ﬁJΩu&ÑkU„;"
—Ì7;GΩ
ﬁJΩu&ÑkU„;π
ﬁJΩu&ÑkU„;5
‡gYßÖ¯Hê");rÆ◊\€
‡gYßÖ¯Hê");rÆ◊\"
‡gYßÖ¯Hê");rÆ◊\∫
‡gYßÖ¯Hê");rÆ◊\
ﬁJΩu&ÑkU„;ø
‡gYßÖ¯Hê");rÆ◊\¿
ﬁJΩu&ÑkU„;≈
‡gYßÖ¯Hê");rÆ◊\∆
int IGNORE = 0;
Grid.SetGridValue(IndexX, IndexY, IndexZ, AttributeIndex, Value.x, IGNORE);
Grid.SetGridValue(IndexX, IndexY, IndexZ, AttributeIndex+1, Value.y, IGNORE);
Grid.SetGridValue(IndexX, IndexY, IndexZ, AttributeIndex+2, Value.z, IGNORE);
BlurredValue = 0;
float Width = Radius * 2. + 1;
float Sigma = (Radius - 1.) / 6.;
float TwoSigmaSquared = 2. * Sigma * Sigma;
float Coeff = 1./(sqrt(2 * 3.141569) * Sigma);
float TotalKernel = 0;
int3 CurrCell = int3(IndexX, IndexY, IndexZ);
int3 MaxCells = int3(NumCellsX, NumCellsY, NumCellsZ)  - 1;
for (int xx = -Radius; xx <= Radius; ++xx) {
for (int yy = -Radius; yy <= Radius; ++yy) {
for (int zz = -Radius; zz <= Radius; ++zz) {
  int3 SampleVec = int3(xx,yy,zz);
  int3 SampelCell = clamp(CurrCell + SampleVec, int3(0,0,0), MaxCells);
  float Sample;
  Grid.GetFloatGridValue(SampelCell.x, SampelCell.y, SampelCell.z, Sample);
  float KernelValue = Coeff * exp(-1. * length2(SampleVec) / (TwoSigmaSquared)); 
  TotalKernel += KernelValue;
  BlurredValue += Sample * KernelValue;
BlurredValue /= TotalKernel;
;W/Ë¿]
float S_right;
Grid.GetFloatGridValue(IndexX+1, IndexY, IndexZ, S_right);
float S_left;
Grid.GetFloatGridValue(IndexX-1, IndexY, IndexZ, S_left);
float S_up;
Grid.GetFloatGridValue(IndexX, IndexY+1, IndexZ, S_up);
float S_down;
Grid.GetFloatGridValue(IndexX, IndexY-1, IndexZ, S_down);
float S_front;
Grid.GetFloatGridValue(IndexX, IndexY, IndexZ+1, S_front);
float S_back;
Grid.GetFloatGridValue(IndexX, IndexY, IndexZ-1, S_back);
Grad = float3(S_right - S_left, S_up - S_down, S_front - S_back) / (2.0 * dx);
Grad = float3(0.0, 0.0, 0.0);
float Total = 0;
for (int i = 0; i <= Radius; ++i)
    float Val = 1. - 1. * i/(Radius+1);
    Total += Val;
    KernelArray.SetArrayElem(false, i, .5*Val / Total);
ÔF´¯t)ê;0
float Total = 0.0;
    Total += Coeff * exp(-1. * (1.*i/Radius) / (TwoSigmaSquared)); 
    float Val = Coeff * exp(-1. * (1.*i/Radius) / (TwoSigmaSquared)); 
    KernelArray.SetArrayElem(false, i, .5*Val/Total);
float BoxVal = 1./(2.0 * Radius + 1.0);
    KernelArray.SetArrayElem(false, i, BoxVal);
£;n4‰EfC∞Ì
S~Îe≤Ï∫Aó;>h≠
±qú©#N7O™ª;eﬂ
nÂ¢q“qMâ;}tk
;W/Ë¿]Î
;W/Ë¿]ø
Â√˙»S;ÅD†ò
W`Äd˘å°B≥t¥÷;ƒk|µ
⁄9;›D∞Çy
ôF≠'|ì;
;W/Ë¿]@
‡H;˜*ı0
Ñq;dœDÿJë`†à]ÀÁÆF
;¶?Î@gãCâ$
x;ò@éAíáû5&6
⁄Tñ{¢åOØÆHZ;
¸¥gq‘ÚôOí;
j£;ﬁjØFÉ•4N^
âH;ñS„∞
\∏Aä;!ô-¬€¡∏
.ë3ev˝˝@ØŸ;˘˜‚b€c
.ë3ev˝˝@ØŸ;˘˜‚b€
pwh;'e
C¢äËG2›A´¡˙;
Ô∞ıyÆﬂ;Oºï°„Œ˜˝ıµ
∂ÙµO≥;3Yx‘(Çµ
æ=¿§;0-F≥
;aJΩzO ?∆+†¥
;aJΩzO ?∆+†
I¶dvÉ;
¶;ûwKçÛ∆
q$Û;‚ò∆Oñ
;aJΩzO ?∆+†À
‡ê;ªóX
.S.; Ná–=Åˇ∂Ã
;aJΩzO ?∆+†Ú
Áw;π5°
z;O∫kÉ^˝öËTµ
≤´;à‘ÿ
ˇ;u…‰∂
º NÄ;+
A¶∫†ÙÄ;≠ZãäEGê¿ÂN≤z
A¶∫†ÙÄ;≠Z
É;LßA^%Ÿ¸ª
Hd;}†#
4ùæò∞b;∫ÉÈm@ãõ
∞b;∫ÉÈm@ãõ
Rﬁı;M®
q‘ı;EûuCdﬁ&5
Ük˚Fã¢•æV;∑@j
Ük˚Fã¢•æV;∑@
DºÅïïÏ;
;§á!ôoıCñ
Aì;˝ˇ\∑Ç]√
Aì;˝ˇ\∑Ç]H
x´;Bé§í‡Òä`Ê
N´†;zXã
x;ò@éAíáû5&6Â
x;ò@éAíáû5&6÷
[;§¯Gçw≤Aí¶K
Û]¯;¨òïBá
U_√{€NÌFö*˛ú;Ì∂u
≥$Ñ;M†˜¨
Æ˝DüÁL¬C»Pµ;
éÉ∫SòzÅS)E¶sÀ;
MÆ/ÊÁ§ı(ïcµ|NÑc"ïì°wç;∂‘›1
8¢∂;ıDº
∫SòzÅS)E¶sÀ;
aÈOp;M
à;¯`>ˇ}HòÌﬁ_
0ÜÓú5;
‡ê;ªóX÷
r}@ΩÂÈ∆Cù^V>ˇ;
OT';ÂgÀDæ
Œ>6ÅKÜ;ª¢D
x;ò@éAíáû5&6+
;w0∞µM©0r
cöâItHÑ§;(è∑
[Òøæe∂ˇDÖ•BˆM¶·B;
K´NùÄ7∞Ò;
0Ü;±LD¢WMPúMfUΩ“
0Ü;±LD¢WMPúMfU
∫z;ÃI∑”∆?∏W‡E
ÍÄHµX;¨DºÿgìÔ{
'2¿ÿ;∑ïHàiøú63#&
Í2 …_,nG∫Û©ªf5;AD
Í2 …_,nG∫Û©ªf5;A∏
Ãiîk;Ÿ
ˆ6Éj)ö¥OÖÜ(∆«;⁄gJ
ˆ6Éj)ö¥OÖÜ(∆«;⁄g∏
Aì;˝ˇ\∑Ç]U
x;ò@éAíáû5&6Ö
;©†˚(ÊÂFêç
A¢;QÉ¢f
Aì;˝ˇ\∑Ç]
x´;Bé§í‡Òä`Êπ
´ÎF˚;∫ŸK≤‡ïëÖ_
;˙/¯X¬
;˙/¯XE
g‹I∏xü;Ü
U_√{€NÌFö*˛ú;Ì∂uƒ
U_√{€NÌFö*˛ú;Ì∂uØ
≠¥C%Ô&÷Jêï;
ÂkYóŸJö;ƒb’
UV¿¥AÑ+äª•z;ß
¨;M"D0
Â;À-ßî
ÙZ≤A;E
 t’(æMùühNw+Dë›
 t’(æMùühNw+Dë
Kû\;óﬂ
Kû\;óÏ
∫z;ÃI∑”∆?∏W‡E‡
∫z;ÃI∑”∆?∏W‡ET
'2¿ÿ;∑ïHàiøú63#&‡
'2¿ÿ;∑ïHàiøú63#&Q
;˙/¯X‰
U_√{€NÌFö*˛ú;Ì∂uÂ
x´;Bé§í‡Òä`ÊÛ
ˆeﬁmú1;Jºﬂˆ
;˚ÓÁÂH∏
{P3„},;c
‰;óHæe
ºf√qÎrJ]Ç…4Ê¯o;5˘öÈ∏
HdÓï;ÑÏÅz™z±
C;ÒGéñK
ˇ†LœZ;Ár
%∞2Çø;
Q;!ÎÙ2ÿ4CW{ÂkVƒ9∏›(∏
_\õ=õ):;l˙<
// Shader generated by Niagara HLSL Translator
// Compile Data> Static Variables Input: 
// Compile Data> PinToConstantValues Input: 
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float Emitter_RasterizationGrid3D_Initialize_dx;
int Emitter_RasterizationGrid3D_Initialize_HalfBandwidth;
float User_ParticleSizeMult;
bool Emitter_SourceIsLocalSpace;
float4x4 Emitter_WorldToUnit;
float ParticleSizeMult;
float dx;
int HalfBandwidth;
float RadiusMult;
bool SourceIsLocalSpace;
float4x4 WorldToUnit;
int UniqueID;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
FParamMap0_Emitter_RasterizationGrid3D_Initialize RasterizationGrid3D_Initialize;
FParamMap0_Array Array;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Particles Particles;
FParamMap0_RasterizationGrid_ParticleSource001 RasterizationGrid_ParticleSource001;
FParamMap0_User User;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColor(int In_InstanceData, int In_Index, out bool Out_Success, out float3 Out_Position, out float3 Out_Velocity, out float Out_Radius, out float Out_PreviousRadius, out float Out_Density, out float Out_Temperature, out float Out_Divergence, out float4 Out_Color);
void UnitToFloatIndex_Emitter_RasterizationGrid(int In_InstanceData, float3 In_Unit, out float3 Out_Index);
void GetNumCells_Emitter_RasterizationGrid(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY, out int Out_NumCellsZ);
void InterlockedMinFloatGridValue_Emitter_RasterizationGrid(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
void CustomHlsl78F770D85266C084E0FD0C10478A3968BD4B4890Emitter_RasterizationGrid_Func_(float3 In_Position, float2 In_SpriteSize, float3 In_Index, float In_dx, int In_HalfBandwidth, float In_RadiusMult, int In_NumCellsX, int In_NumCellsY, int In_NumCellsZ, inout FSimulationContext Context);
void RasterizationGrid_ParticleSource001_Emitter_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
int IGNORE;
// we never want a radius smaller than half of the cell size otherwise
// we can't rasterize an sdf
float Radius = max(In_SpriteSize.x * .5 * In_RadiusMult, In_dx * .5);
float IndexRadius = Radius / In_dx;
int size = ceil(IndexRadius) + In_HalfBandwidth;
int IndexX = round(In_Index.x);
int IndexY = round(In_Index.y);
int IndexZ = round(In_Index.z);
for (int xx = -size; xx <= size; ++xx) {
for (int yy = -size;  yy <= size; ++yy) {
for (int zz = -size; zz <= size; ++zz) {
    int3 CurrIndex = int3(IndexX+xx,IndexY+yy,IndexZ+zz);
    float IndexDist = length(In_Index - CurrIndex) - IndexRadius;
   if (abs(IndexDist) <= In_HalfBandwidth &&
        CurrIndex.x >= 0 && CurrIndex.x < In_NumCellsX &&
        CurrIndex.y >= 0 && CurrIndex.y < In_NumCellsY &&
        CurrIndex.z >= 0 && CurrIndex.z < In_NumCellsZ)
        InterlockedMinFloatGridValue_Emitter_RasterizationGrid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, 0, IndexDist * In_dx, IGNORE);
//SetConstantByStaticVariable "/Rasterization Grid Particle Source 001/Map Get/Map Get->Module.UseNDC"
int Constant = 1;
int Result = ExecIndex();
bool Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Success;
float3 Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Position;
float3 Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Velocity;
float Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Radius;
float Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_PreviousRadius;
float Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Density;
float Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Temperature;
float Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Divergence;
float4 Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Color;
Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColor(2, Result, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Success, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Position, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Velocity, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Radius, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_PreviousRadius, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Density, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Temperature, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Divergence, Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Color);
float Constant1 = 2;
float Result1 = Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Radius * Constant1;
float2 Output1;
Output1.x = Result1;
Output1.y = Result1;
float3 Result2 = mul(float4(Read_Emitter_NDCReader_PositionNiagaraPosition_VelocityVector3f_RadiusNiagaraFloat_PreviousRadiusNiagaraFloat_DensityNiagaraFloat_TemperatureNiagaraFloat_DivergenceNiagaraFloat_ColorLinearColorOutput_Position,1.0),Context.Map.RasterizationGrid_ParticleSource001.WorldToUnit).xyz;
float3 Output11;
Output11.x = Result2.x;
Output11.y = Result2.y;
Output11.z = Result2.z;
float3 UnitToFloatIndex_Emitter_RasterizationGridOutput_Index;
UnitToFloatIndex_Emitter_RasterizationGrid(0, Output11, UnitToFloatIndex_Emitter_RasterizationGridOutput_Index);
int GetNumCells_Emitter_RasterizationGridOutput_NumCellsX;
int GetNumCells_Emitter_RasterizationGridOutput_NumCellsY;
int GetNumCells_Emitter_RasterizationGridOutput_NumCellsZ;
GetNumCells_Emitter_RasterizationGrid(0, GetNumCells_Emitter_RasterizationGridOutput_NumCellsX, GetNumCells_Emitter_RasterizationGridOutput_NumCellsY, GetNumCells_Emitter_RasterizationGridOutput_NumCellsZ);
CustomHlsl78F770D85266C084E0FD0C10478A3968BD4B4890Emitter_RasterizationGrid_Func_(Output11, Output1, UnitToFloatIndex_Emitter_RasterizationGridOutput_Index, Context.Map.RasterizationGrid_ParticleSource001.dx, Context.Map.RasterizationGrid_ParticleSource001.HalfBandwidth, Context.Map.RasterizationGrid_ParticleSource001.RadiusMult, GetNumCells_Emitter_RasterizationGridOutput_NumCellsX, GetNumCells_Emitter_RasterizationGridOutput_NumCellsY, GetNumCells_Emitter_RasterizationGridOutput_NumCellsZ, Context);
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**SimulationStage_0*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
Context.Map.RasterizationGrid_ParticleSource001.dx = Context.Map.Emitter.RasterizationGrid3D_Initialize.dx;
Context.Map.RasterizationGrid_ParticleSource001.HalfBandwidth = Context.Map.Emitter.RasterizationGrid3D_Initialize.HalfBandwidth;
Context.Map.RasterizationGrid_ParticleSource001.RadiusMult = Context.Map.User.ParticleSizeMult;
Context.Map.RasterizationGrid_ParticleSource001.SourceIsLocalSpace = Context.Map.Emitter.SourceIsLocalSpace;
Context.Map.RasterizationGrid_ParticleSource001.WorldToUnit = Context.Map.Emitter.WorldToUnit;
EnterStatScope(1 /**RasterizationGrid_ParticleSource001_Emitter_Func_*/);
RasterizationGrid_ParticleSource001_Emitter_Func_(Context);
ExitStatScope(/**RasterizationGrid_ParticleSource001_Emitter_Func_*/);
ExitStatScope(/**SimulationStage_0*/);
EnterStatScope(2 /**SimulationStage_0_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Emitter.RasterizationGrid3D_Initialize.dx = Emitter_RasterizationGrid3D_Initialize_dx;
Context.Map.Emitter.RasterizationGrid3D_Initialize.HalfBandwidth = Emitter_RasterizationGrid3D_Initialize_HalfBandwidth;
Context.Map.User.ParticleSizeMult = User_ParticleSizeMult;
Context.Map.Emitter.SourceIsLocalSpace = Emitter_SourceIsLocalSpace;
Context.Map.Emitter.WorldToUnit = Emitter_WorldToUnit;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = 0;
EnterStatScope(3 /**SimulationStage_0_MapMain*/);
Simulate(Context);
ExitStatScope(/**SimulationStage_0_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Particles.UniqueID);
ExitStatScope(/**SimulationStage_0_Main*/);
int Emitter_Grid3D_InitializeConvolutionKernel_Radius;
int Radius;
FParamMap0_Emitter_Grid3D_InitializeConvolutionKernel Grid3D_InitializeConvolutionKernel;
FParamMap0_Grid3D_CreateConvolutionKernel Grid3D_CreateConvolutionKernel;
void SetFloatValue_Emitter_KernelGrid_UEImpureCall_Attributek(int In_InstanceData, int In_IndexX, int In_IndexY, float In_Value);
void CustomHlsl464C63258C036180550C613C993B0AAA411817DCEmitter_KernelGrid_Func_(int In_Radius, inout FSimulationContext Context);
void Grid3D_CreateConvolutionKernel_Emitter_Func_(inout FSimulationContext Context);
   SetFloatValue_Emitter_KernelGrid_UEImpureCall_Attributek(0, 0,0,1);
    float Sigma = In_Radius;
    float TwoSigmaSquared = 2. * Sigma * Sigma;
    float Coeff = 1./sqrt(3.141569 * TwoSigmaSquared);
    float Total = 0.0;
    for (int i = 0; i <= In_Radius; ++i)
        float Val = Coeff * exp(-1. * pow(i,2) / (TwoSigmaSquared));
        Total +=  Val;
        // add negative side to total
        if (i > 0)
            Total += Val;
        float Val = Coeff * exp(-1. * pow(i,2) / (TwoSigmaSquared)); 
        SetFloatValue_Emitter_KernelGrid_UEImpureCall_Attributek(0, i, 0, Val/Total);
//SetConstantByStaticVariable "/Grid 3D Create Convolution Kernel/Map Get/Map Get->Module.Smoothing Kernel"
int Constant = 0;
CustomHlsl464C63258C036180550C613C993B0AAA411817DCEmitter_KernelGrid_Func_(Context.Map.Grid3D_CreateConvolutionKernel.Radius, Context);
EnterStatScope(0 /**SimulationStage_2_0*/);
Context.Map.Grid3D_CreateConvolutionKernel.Radius = Context.Map.Emitter.Grid3D_InitializeConvolutionKernel.Radius;
EnterStatScope(1 /**Grid3D_CreateConvolutionKernel_Emitter_Func_*/);
Grid3D_CreateConvolutionKernel_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_CreateConvolutionKernel_Emitter_Func_*/);
ExitStatScope(/**SimulationStage_2_0*/);
EnterStatScope(2 /**SimulationStage_2_0_Main*/);
Context.Map.Emitter.Grid3D_InitializeConvolutionKernel.Radius = Emitter_Grid3D_InitializeConvolutionKernel_Radius;
EnterStatScope(3 /**SimulationStage_2_0_MapMain*/);
ExitStatScope(/**SimulationStage_2_0_MapMain*/);
ExitStatScope(/**SimulationStage_2_0_Main*/);
ád˘Ôn;…G¶ﬁ=m˙ÄD(º
FParamMap0_RasterizationGrid_ParticleSource RasterizationGrid_ParticleSource;
void GetPositionByIndex_Emitter_Reader_AttributePosition(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float3 Out_Value);
void NiagaraScript_565_Func_(int In_SourceSpace, int In_DestinationSpace, float4x4 In_LocalToWorldTransform, float4x4 In_WorldToLocalTransform, bool In_bLocalSpace, out bool Out_bUseOriginal, out float4x4 Out_OutTransform, out bool Out_LocalToWorld, inout FSimulationContext Context);
void NiagaraScript_564_Emitter_Localspace_false_Particle_Func_(float3 In_Position, int In_SourceSpace, int In_DestinationSpace, bool In_ApplyScale, float4x4 In_Engine_Owner_SystemLocalToWorld, float4x4 In_Engine_Owner_SystemWorldToLocal, float4x4 In_Engine_Owner_SystemLocalToWorldNoScale, float4x4 In_Engine_Owner_SystemWorldToLocalNoScale, out float3 Out_Position, inout FSimulationContext Context);
void GetVector2DByIndex_Emitter_Reader_AttributeSpriteSize(int In_InstanceData, int In_ParticleIndex, out bool Out_Valid, out float2 Out_Value);
void RasterizationGrid_ParticleSource_Emitter_Func_(inout FSimulationContext Context);
int Constant12 = 0;
bool Result1 = NiagaraAll(In_SourceSpace == Constant12);
int Constant13 = 0;
bool Result2 = NiagaraAll(In_DestinationSpace == Constant13);
bool Result3 = Result1 && Result2;
int Constant14 = 1;
bool Result4 = NiagaraAll(In_SourceSpace == Constant14);
int Constant15 = 1;
bool Result5 = NiagaraAll(In_DestinationSpace == Constant15);
bool Result6 = Result4 && Result5;
bool Result7 = Result3 || Result6;
int Constant16 = 2;
bool Result8 = NiagaraAll(In_SourceSpace == Constant16);
int Constant17 = 2;
bool Result9 = NiagaraAll(In_DestinationSpace == Constant17);
bool Result10 = Result8 && Result9;
bool Result11 = Result7 || Result10;
bool Result12 = Result1 && Result9;
bool Result13 = Result8 && Result2;
bool Result14 = Result12 || Result13;
bool Result15 = In_bLocalSpace && Result14;
bool Result16 = Result11 || Result15;
bool Result17 = !In_bLocalSpace;
bool Result18 = Result1 && Result5;
bool Result19 = Result4 && Result2;
bool Result20 = Result18 || Result19;
bool Result21 = Result17 && Result20;
bool Result22 = Result16 || Result21;
bool Result23 = In_bLocalSpace && Result18;
bool Result24 = Result8 && Result5;
bool Result25 = Result23 || Result24;
bool Result26 = Result17 && Result13;
bool Result27 = Result25 || Result26;
float4x4 Matrix_IfResult;
Matrix_IfResult = In_LocalToWorldTransform;
Matrix_IfResult = In_WorldToLocalTransform;
Out_bUseOriginal = Result22;
Out_OutTransform = Matrix_IfResult;
Out_LocalToWorld = Result27;
float4x4 Constant9 = (float4x4)0;
float4x4 LocalToWorld_SelectResult = Constant9;
float4x4 Constant10 = (float4x4)0;
float4x4 WorldToLocal_SelectResult = Constant10;
LocalToWorld_SelectResult = Context.Map.Engine.Owner.SystemLocalToWorld;
WorldToLocal_SelectResult = Context.Map.Engine.Owner.SystemWorldToLocal;
LocalToWorld_SelectResult = Context.Map.Engine.Owner.SystemLocalToWorldNoScale;
WorldToLocal_SelectResult = Context.Map.Engine.Owner.SystemWorldToLocalNoScale;
bool Constant11 = false;
bool NiagaraScript_565_Func_Output_bUseOriginal;
float4x4 NiagaraScript_565_Func_Output_OutTransform;
bool NiagaraScript_565_Func_Output_LocalToWorld;
NiagaraScript_565_Func_(In_SourceSpace, In_DestinationSpace, LocalToWorld_SelectResult, WorldToLocal_SelectResult, Constant11, NiagaraScript_565_Func_Output_bUseOriginal, NiagaraScript_565_Func_Output_OutTransform, NiagaraScript_565_Func_Output_LocalToWorld, Context);
float3 Result28 = mul(float4(In_Position,1.0),NiagaraScript_565_Func_Output_OutTransform).xyz;
float3 Constant18 = float3(0.0, 0.0, 0.0);
float3 NiagaraPosition_SelectResult1 = Constant18;
NiagaraPosition_SelectResult1 = In_Position;
NiagaraPosition_SelectResult1 = Result28;
Out_Position = NiagaraPosition_SelectResult1;
//SetConstantByStaticVariable "/Rasterization Grid Particle Source/Map Get/Map Get->Module.UseNDC"
bool GetPositionByIndex_Emitter_Reader_AttributePositionOutput_Valid;
float3 GetPositionByIndex_Emitter_Reader_AttributePositionOutput_Value;
GetPositionByIndex_Emitter_Reader_AttributePosition(1, Result, GetPositionByIndex_Emitter_Reader_AttributePositionOutput_Valid, GetPositionByIndex_Emitter_Reader_AttributePositionOutput_Value);
int Constant1 = 2;
int Constant2 = 1;
bool Constant3 = false;
float4x4 Constant4 = float4x4(1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1);
float4x4 Constant5 = float4x4(1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1);
float4x4 Constant6 = float4x4(1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1);
float4x4 Constant7 = float4x4(1,0,0,0, 0,1,0,0, 0,0,1,0, 0,0,0,1);
bool Constant8 = false;
float3 NiagaraScript_564_Emitter_Localspace_false_Particle_Func_Output_Position;
NiagaraScript_564_Emitter_Localspace_false_Particle_Func_(GetPositionByIndex_Emitter_Reader_AttributePositionOutput_Value, Constant1, Constant2, Constant3, Constant4, Constant5, Constant6, Constant7, NiagaraScript_564_Emitter_Localspace_false_Particle_Func_Output_Position, Context);
float3 Constant19 = float3(0.0, 0.0, 0.0);
float3 NiagaraPosition_SelectResult2 = Constant19;
NiagaraPosition_SelectResult2 = NiagaraScript_564_Emitter_Localspace_false_Particle_Func_Output_Position;
NiagaraPosition_SelectResult2 = GetPositionByIndex_Emitter_Reader_AttributePositionOutput_Value;
bool GetVector2DByIndex_Emitter_Reader_AttributeSpriteSizeOutput_Valid;
float2 GetVector2DByIndex_Emitter_Reader_AttributeSpriteSizeOutput_Value;
GetVector2DByIndex_Emitter_Reader_AttributeSpriteSize(1, Result, GetVector2DByIndex_Emitter_Reader_AttributeSpriteSizeOutput_Valid, GetVector2DByIndex_Emitter_Reader_AttributeSpriteSizeOutput_Value);
float3 Result29 = mul(float4(NiagaraPosition_SelectResult2,1.0),Context.Map.RasterizationGrid_ParticleSource.WorldToUnit).xyz;
float3 Output1;
Output1.x = Result29.x;
Output1.y = Result29.y;
Output1.z = Result29.z;
UnitToFloatIndex_Emitter_RasterizationGrid(0, Output1, UnitToFloatIndex_Emitter_RasterizationGridOutput_Index);
CustomHlsl78F770D85266C084E0FD0C10478A3968BD4B4890Emitter_RasterizationGrid_Func_(Output1, GetVector2DByIndex_Emitter_Reader_AttributeSpriteSizeOutput_Value, UnitToFloatIndex_Emitter_RasterizationGridOutput_Index, Context.Map.RasterizationGrid_ParticleSource.dx, Context.Map.RasterizationGrid_ParticleSource.HalfBandwidth, Context.Map.RasterizationGrid_ParticleSource.RadiusMult, GetNumCells_Emitter_RasterizationGridOutput_NumCellsX, GetNumCells_Emitter_RasterizationGridOutput_NumCellsY, GetNumCells_Emitter_RasterizationGridOutput_NumCellsZ, Context);
Context.Map.RasterizationGrid_ParticleSource.dx = Context.Map.Emitter.RasterizationGrid3D_Initialize.dx;
Context.Map.RasterizationGrid_ParticleSource.HalfBandwidth = Context.Map.Emitter.RasterizationGrid3D_Initialize.HalfBandwidth;
Context.Map.RasterizationGrid_ParticleSource.WorldToUnit = Context.Map.Emitter.WorldToUnit;
Context.Map.RasterizationGrid_ParticleSource.RadiusMult = Context.Map.User.ParticleSizeMult;
Context.Map.RasterizationGrid_ParticleSource.SourceIsLocalSpace = Context.Map.Emitter.SourceIsLocalSpace;
EnterStatScope(1 /**RasterizationGrid_ParticleSource_Emitter_Func_*/);
RasterizationGrid_ParticleSource_Emitter_Func_(Context);
ExitStatScope(/**RasterizationGrid_ParticleSource_Emitter_Func_*/);
Context.Map.Engine.Owner.SystemLocalToWorld = Engine_Owner_SystemLocalToWorld;
Context.Map.Engine.Owner.SystemWorldToLocal = Engine_Owner_SystemWorldToLocal;
Context.Map.Engine.Owner.SystemLocalToWorldNoScale = Engine_Owner_SystemLocalToWorldNoScale;
Context.Map.Engine.Owner.SystemWorldToLocalNoScale = Engine_Owner_SystemWorldToLocalNoScale;
float SDF;
FParamMap0_SetVariables_8F84CC084116DB1E24DAB3A11D37F716_Emitter_SDFGrid SDFGrid;
FParamMap0_SetVariables_8F84CC084116DB1E24DAB3A11D37F716_Emitter Emitter;
float ConvolvedValue;
FParamMap0_OUTPUT_VAR_Grid3D_ConvolveAxis Grid3D_ConvolveAxis;
FParamMap0_Emitter_SDFGrid SDFGrid;
FParamMap0_OUTPUT_VAR OUTPUT_VAR;
FParamMap0_SetVariables_8F84CC084116DB1E24DAB3A11D37F716 SetVariables_8F84CC084116DB1E24DAB3A11D37F716;
void GetNumCells_Emitter_KernelGrid(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY);
void ExecutionIndexToGridIndex_Emitter_RasterizationGrid(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void GetFloatGridValue_Emitter_RasterizationGrid(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, out float Out_Value);
void GetPreviousFloatValue_Emitter_KernelGrid_Attributek(int In_InstanceData, int In_IndexX, int In_IndexY, out float Out_Value);
void CustomHlslCDAEA50162DF4BFAC592DAF11F68B5633DDD25C6Emitter_RasterizationGridEmitter_KernelGrid_Func_(int In_Radius, int In_IndexX, int In_IndexY, int In_IndexZ, int In_NumCellsX, int In_NumCellsY, int In_NumCellsZ, float3 In_ConvAxis, int In_AttributeIndex, out float Out_ConvolvedValue);
void Grid3D_ConvolveAxis_Emitter_Func_(inout FSimulationContext Context);
void SetVariables_8F84CC084116DB1E24DAB3A11D37F716_Emitter_Func_(inout FSimulationContext Context);
Out_ConvolvedValue = 0;
int3 CurrCell = int3(In_IndexX, In_IndexY, In_IndexZ);
int3 MaxCells = int3(In_NumCellsX, In_NumCellsY, In_NumCellsZ)  - 1;
for (int uu = -In_Radius; uu <= In_Radius; ++uu) {
  int3 SampleVec = uu * In_ConvAxis;
  int3 CurrIndex = clamp(CurrCell + SampleVec, int3(0,0,0), MaxCells);
  GetFloatGridValue_Emitter_RasterizationGrid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, In_AttributeIndex, Sample);
  float KernelValue;
  GetPreviousFloatValue_Emitter_KernelGrid_Attributek(1, abs(uu), 0, KernelValue);
  Out_ConvolvedValue += Sample * KernelValue;
int Constant1 = 0;
//SetConstantByStaticVariable "/Grid 3D Convolve Axis/Map Get/Map Get->Module.Axis"
int Constant2 = 0;
int GetNumCells_Emitter_KernelGridOutput_NumCellsX;
int GetNumCells_Emitter_KernelGridOutput_NumCellsY;
GetNumCells_Emitter_KernelGrid(1, GetNumCells_Emitter_KernelGridOutput_NumCellsX, GetNumCells_Emitter_KernelGridOutput_NumCellsY);
int Constant3 = 1;
int Result = GetNumCells_Emitter_KernelGridOutput_NumCellsX - Constant3;
int ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexX;
int ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexY;
int ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexZ;
ExecutionIndexToGridIndex_Emitter_RasterizationGrid(0, ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexX, ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexY, ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexZ);
float3 Constant4 = float3(1,0,0);
float CustomHlslCDAEA50162DF4BFAC592DAF11F68B5633DDD25C6Emitter_RasterizationGridEmitter_KernelGrid_Func_Output_ConvolvedValue;
CustomHlslCDAEA50162DF4BFAC592DAF11F68B5633DDD25C6Emitter_RasterizationGridEmitter_KernelGrid_Func_(Result, ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexX, ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexY, ExecutionIndexToGridIndex_Emitter_RasterizationGridOutput_IndexZ, GetNumCells_Emitter_RasterizationGridOutput_NumCellsX, GetNumCells_Emitter_RasterizationGridOutput_NumCellsY, GetNumCells_Emitter_RasterizationGridOutput_NumCellsZ, Constant4, Constant1, CustomHlslCDAEA50162DF4BFAC592DAF11F68B5633DDD25C6Emitter_RasterizationGridEmitter_KernelGrid_Func_Output_ConvolvedValue);
Context.Map.OUTPUT_VAR.Grid3D_ConvolveAxis.ConvolvedValue = CustomHlslCDAEA50162DF4BFAC592DAF11F68B5633DDD25C6Emitter_RasterizationGridEmitter_KernelGrid_Func_Output_ConvolvedValue;
Context.Map.Emitter.SDFGrid.SDF = Context.Map.SetVariables_8F84CC084116DB1E24DAB3A11D37F716.Emitter.SDFGrid.SDF;
EnterStatScope(1 /**Grid3D_ConvolveAxis_Emitter_Func_*/);
Grid3D_ConvolveAxis_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_ConvolveAxis_Emitter_Func_*/);
Context.Map.SetVariables_8F84CC084116DB1E24DAB3A11D37F716.Emitter.SDFGrid.SDF = Context.Map.OUTPUT_VAR.Grid3D_ConvolveAxis.ConvolvedValue;
EnterStatScope(2 /**SetVariables_8F84CC084116DB1E24DAB3A11D37F716_Emitter_Func_*/);
SetVariables_8F84CC084116DB1E24DAB3A11D37F716_Emitter_Func_(Context);
ExitStatScope(/**SetVariables_8F84CC084116DB1E24DAB3A11D37F716_Emitter_Func_*/);
EnterStatScope(3 /**SimulationStage_2_0_Main*/);
EnterStatScope(4 /**SimulationStage_2_0_MapMain*/);
FParamMap0_SetVariables_53E1127D4C9E34492A8683A360C3CF0F_Emitter_SDFGrid SDFGrid;
FParamMap0_SetVariables_53E1127D4C9E34492A8683A360C3CF0F_Emitter Emitter;
FParamMap0_OUTPUT_VAR_Grid3D_ConvolveAxis001 Grid3D_ConvolveAxis001;
FParamMap0_SetVariables_53E1127D4C9E34492A8683A360C3CF0F SetVariables_53E1127D4C9E34492A8683A360C3CF0F;
void ExecutionIndexToGridIndex_Emitter_SDFGrid(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void GetNumCells_Emitter_SDFGrid(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY, out int Out_NumCellsZ);
void GetPreviousFloatValueAtIndex_Emitter_SDFGrid(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, out float Out_Value);
void CustomHlslADADBB1F3B882C6272944C03CB449973CF973165Emitter_SDFGridEmitter_KernelGrid_Func_(int In_Radius, int In_IndexX, int In_IndexY, int In_IndexZ, int In_NumCellsX, int In_NumCellsY, int In_NumCellsZ, float3 In_ConvAxis, int In_AttributeIndex, out float Out_ConvolvedValue);
void Grid3D_ConvolveAxis001_Emitter_Func_(inout FSimulationContext Context);
void SetVariables_53E1127D4C9E34492A8683A360C3CF0F_Emitter_Func_(inout FSimulationContext Context);
  GetPreviousFloatValueAtIndex_Emitter_SDFGrid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, In_AttributeIndex, Sample);
//SetConstantByStaticVariable "/Grid 3D Convolve Axis 001/Map Get/Map Get->Module.Axis"
int ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexX;
int ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexY;
int ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexZ;
ExecutionIndexToGridIndex_Emitter_SDFGrid(0, ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexX, ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexY, ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexZ);
int GetNumCells_Emitter_SDFGridOutput_NumCellsX;
int GetNumCells_Emitter_SDFGridOutput_NumCellsY;
int GetNumCells_Emitter_SDFGridOutput_NumCellsZ;
GetNumCells_Emitter_SDFGrid(0, GetNumCells_Emitter_SDFGridOutput_NumCellsX, GetNumCells_Emitter_SDFGridOutput_NumCellsY, GetNumCells_Emitter_SDFGridOutput_NumCellsZ);
float3 Constant4 = float3(0,1,0);
float CustomHlslADADBB1F3B882C6272944C03CB449973CF973165Emitter_SDFGridEmitter_KernelGrid_Func_Output_ConvolvedValue;
CustomHlslADADBB1F3B882C6272944C03CB449973CF973165Emitter_SDFGridEmitter_KernelGrid_Func_(Result, ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexX, ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexY, ExecutionIndexToGridIndex_Emitter_SDFGridOutput_IndexZ, GetNumCells_Emitter_SDFGridOutput_NumCellsX, GetNumCells_Emitter_SDFGridOutput_NumCellsY, GetNumCells_Emitter_SDFGridOutput_NumCellsZ, Constant4, Constant1, CustomHlslADADBB1F3B882C6272944C03CB449973CF973165Emitter_SDFGridEmitter_KernelGrid_Func_Output_ConvolvedValue);
Context.Map.OUTPUT_VAR.Grid3D_ConvolveAxis001.ConvolvedValue = CustomHlslADADBB1F3B882C6272944C03CB449973CF973165Emitter_SDFGridEmitter_KernelGrid_Func_Output_ConvolvedValue;
Context.Map.Emitter.SDFGrid.SDF = Context.Map.SetVariables_53E1127D4C9E34492A8683A360C3CF0F.Emitter.SDFGrid.SDF;
EnterStatScope(1 /**Grid3D_ConvolveAxis001_Emitter_Func_*/);
Grid3D_ConvolveAxis001_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_ConvolveAxis001_Emitter_Func_*/);
Context.Map.SetVariables_53E1127D4C9E34492A8683A360C3CF0F.Emitter.SDFGrid.SDF = Context.Map.OUTPUT_VAR.Grid3D_ConvolveAxis001.ConvolvedValue;
EnterStatScope(2 /**SetVariables_53E1127D4C9E34492A8683A360C3CF0F_Emitter_Func_*/);
SetVariables_53E1127D4C9E34492A8683A360C3CF0F_Emitter_Func_(Context);
ExitStatScope(/**SetVariables_53E1127D4C9E34492A8683A360C3CF0F_Emitter_Func_*/);
ád˘Ôn;…G¶ﬁ=m˙ÄD(§
‰S∫Ì=M9O†<ù.Ü;mî°
FParamMap0_OUTPUT_VAR_Grid3D_ConvolveAxis002 Grid3D_ConvolveAxis002;
float Red;
FParamMap0_Grid3D_SetRTValues Grid3D_SetRTValues;
void Grid3D_ConvolveAxis002_Emitter_Func_(inout FSimulationContext Context);
void ExecToIndex_Emitter_SimRT(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void SetRenderTargetValue_Emitter_SimRT_UEImpureCall(int In_InstanceData, bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
void Grid3D_SetRTValues_Emitter_Func_(inout FSimulationContext Context);
//SetConstantByStaticVariable "/Grid 3D Convolve Axis 002/Map Get/Map Get->Module.Axis"
int Constant2 = 2;
float3 Constant4 = float3(0,0,1);
Context.Map.OUTPUT_VAR.Grid3D_ConvolveAxis002.ConvolvedValue = CustomHlslADADBB1F3B882C6272944C03CB449973CF973165Emitter_SDFGridEmitter_KernelGrid_Func_Output_ConvolvedValue;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.SetFromVector"
int Constant8 = 0;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.UseIterationGrid"
int Constant9 = 0;
bool Constant10 = true;
int ExecToIndex_Emitter_SimRTOutput_IndexX;
int ExecToIndex_Emitter_SimRTOutput_IndexY;
int ExecToIndex_Emitter_SimRTOutput_IndexZ;
ExecToIndex_Emitter_SimRT(2, ExecToIndex_Emitter_SimRTOutput_IndexX, ExecToIndex_Emitter_SimRTOutput_IndexY, ExecToIndex_Emitter_SimRTOutput_IndexZ);
float Constant11 = 0;
float Constant12 = 0;
float Constant13 = 0;
float4 Output1;
Output1.r = Context.Map.Grid3D_SetRTValues.Red;
Output1.g = Constant11;
Output1.b = Constant12;
Output1.a = Constant13;
SetRenderTargetValue_Emitter_SimRT_UEImpureCall(2, Constant10, ExecToIndex_Emitter_SimRTOutput_IndexX, ExecToIndex_Emitter_SimRTOutput_IndexY, ExecToIndex_Emitter_SimRTOutput_IndexZ, Output1);
EnterStatScope(1 /**Grid3D_ConvolveAxis002_Emitter_Func_*/);
Grid3D_ConvolveAxis002_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_ConvolveAxis002_Emitter_Func_*/);
Context.Map.Grid3D_SetRTValues.Red = Context.Map.OUTPUT_VAR.Grid3D_ConvolveAxis002.ConvolvedValue;
float Constant5 = 0;
float Constant6 = 0;
float Constant7 = 0;
EnterStatScope(2 /**Grid3D_SetRTValues_Emitter_Func_*/);
Grid3D_SetRTValues_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_SetRTValues_Emitter_Func_*/);
EnterStatScope(0 /**SpawnScript_2_0*/);
// Begin HandleMissingDefaultValues
// End HandleMissingDefaultValues
ExitStatScope(/**SpawnScript_2_0*/);
EnterStatScope(1 /**SpawnScript_2_0_Main*/);
Context.Map.Particles.UniqueID = 0;
Context.Map.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + ExecIndex();
EnterStatScope(2 /**SpawnScript_2_0_MapMain*/);
ExitStatScope(/**SpawnScript_2_0_MapMain*/);
ExitStatScope(/**SpawnScript_2_0_Main*/);
EnterStatScope(0 /**UpdateScript_2_3*/);
ExitStatScope(/**UpdateScript_2_3*/);
EnterStatScope(1 /**UpdateScript_2_3_Main*/);
Context.Map.Particles.UniqueID = InputDataInt(0, 0);
Context.Map.Array.UniqueID = 0;
EnterStatScope(2 /**UpdateScript_2_3_MapMain*/);
ExitStatScope(/**UpdateScript_2_3_MapMain*/);
ExitStatScope(/**UpdateScript_2_3_Main*/);
dl7dJ ﬂ@ù5íé;pgP∏
 i≠•⁄VHÅ
‡;‹Oå˙RF
;höÄL∞ú(TX
lµ=nJàN˚;sî„E∏
zÄ˙E¶Sy;7=
∫3~ÂË)tOÆ+;g"Ò
.B7qU5˚I∏Ü;qX
*BÏ€Ï;∏
 yè˜w∫I¨Í{qˆmì^∏
¡É*ûóˆ•Ä.;ƒ—

