M¥;≥„s•
wFª:na^;Zâ
§≠DìúÌ;˚´J,î
§≠DìúÌ;˚´J,ì
[Ü˙;…ﬂ
,≤N˚y;≥DáôôÜ∫±⁄zÒ
Û}õ+m.Ä%ÿ;>
i32Mµû$LéóX;]ññÒ
¨;p}´£
{dLe;Ò
F°>:;)ÎBÄW^è˛'aß
?W;dàUtJÜ^Â
!v≈_K¡QBå¡"4◊;Wæ›
#ìJÆ≤@¿;^,"F
#ìJÆ≤@¿;^,"ä
¬›Aâƒ;>CŸ÷⁄
A\π;‚ì
float BoundingSphereRadius = length(.5 * Scale);
SpriteWidth = 2. * BoundingSphereRadius;
float3 CameraToGridCenter = GridCenterPos - CameraPos;
float DistToGridCenter = length(CameraToGridCenter);
    SpritePos = GridCenterPos;
    float3 RayDir = CameraToGridCenter / DistToGridCenter;
    //SpritePos = GridCenterPos - BoundingSphereRadius * RayDir;
+å;∑c0XGô
)ó´„æ·ï@°x;0Ìu{Ω/
≠—Bà;â>ÈGÈ¨/
•;Œ—ÂÌ≈Bõ‚N5Éó\ÜB
Ì;˙Îdq∑M´õ‰‡%∞T
2[ü©MÜ¨A≤j<r;4£B
õ;˜∫·Oúö˝
BªsÕXßzﬁ;B
Möˆ%Ùf¸;ËB
Ü§rŒ÷;¥N∑ï
McéBåI±;Ùë
;FäVøX¶!‰
ﬂ%x‰˛;)Lë°™‡‡Qô
ˆ&óŸ ;ÛOä
ÁúwÿFeÚMåZ5;:ñQ˚T
ÁúwÿFeÚMåZ5;:ñQ˚ä
!»qÌ;âi@ø£†ˆ{
ıÈ˘1;æçIå±Ï≤hÕH0Ä
≥yöõQjuN®±j.≤≈K;
–vN≤;^»?
≠ßü;Ì0NNú
é_;¿⁄ƒˆAôYøm$
¸¥gq‘ÚôOí;
∂ÙµO≥;3Yx‘(Ç
;P¸îAê1ñRŒ u
_◊;Sv˘ıMÄA
∂gmZÁ; D¨™€W˜
ˇÏ#Nf;uN£⁄ıoï#Ÿg
T;¢aœœ<HûMÖ†ø]ñS
K;^ZN(<Må
~æ£O;ˆ∑B∞ÿqvK≤âm
™™‘jÂ8±Iñy=;JP·S
&3rˇPT≈;»Cã¯
2©˚Qù°Ì;L∞®·Ïπ[^
©˚Qù°Ì;L∞®·Ïπ[^
+^%Q´;•
+^%Q´;
tB´;F1h˜T˜È—–9
tB´;F1h˜T˜
=ÌO∏ãT;Úi:®
;1lLúO©)&SHn
%é∞eO¶;Ûﬂ
d£¥Â%ÈWNèËaBtg;≈
 v$µO∂˝˚
;êÒ6Fˇ F´ï7|
1äOπÍ∂2;#(≈Z
1äOπÍ∂2;#(≈
;DßFô&Z2RqLW∏
;DßFô&Z2RqLW»
(nJè–f;π
^;]∏î‰Díâ°ûÊ…9
“Lä;'Nï
uu¨∏;#Dã
#º≤e{U;.
ÉEû;Ì[œ$
ïÎb;√p
 rÇò+›˝Kè
C¶;xií
óXJ˝ê‹,BôÌ;
H~;πãœcHú¿
πy;$-S
@≠¢á!Dçi;ÿ∆ËèÔ
™™‘jÂ8±Iñy=;JP·S‡
™™‘jÂ8±Iñy=;JP·Sõ
GÜ;ã>˚î∆8
;DßFô&Z2RqLW
#ìJÆ≤@¿;^,"
ì€r;‘O‹Hñê˙
ÁúwÿFeÚMåZ5;:ñQ˚
;øA8iËYJçíêÑ·f3ÿ
T;¢aœœ<HûMÖ†ø]ñSÏ
T;¢aœœ<HûMÖ†ø]ñSº
˜;˜TI≠È
ÌeòÇ™È„Gè[ÓÓ3Ê™;
gPÅ"êx;D®é§ì$R0çÓ
gPÅ"êx;D®é§ì$R0ç
ﬂ;ä˜]†«DèW;
Bà;r‚=µç¶e
ÂŸ@"Ón;OÖWñAD1ë…
ÂŸ@"Ón;OÖWñAD1ë…2
// Shader generated by Niagara HLSL Translator
// Compile Data> Static Variables Input: 
// Compile Data> PinToConstantValues Input: 
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
int UniqueID;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
float Density;
FParamMap0_Emitter_SimGrid SimGrid;
FParamMap0_Array Array;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Particles Particles;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void SetVariables_65B652054C5FE9AA0F58D999226DC052_Emitter_Func_(inout FSimulationContext Context);
void SetVariables_A5326F1C41DDC2193E3BC489DAD6D943_Emitter_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
float Constant1 = 0.1;
Context.Map.Emitter.SimGrid.Density = Constant1;
float3 Constant3 = float3(0,0,0);
Context.Map.Emitter.SimGrid.Velocity = Constant3;
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**SimulationStage_0*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
float Constant = 0.1;
EnterStatScope(1 /**SetVariables_65B652054C5FE9AA0F58D999226DC052_Emitter_Func_*/);
SetVariables_65B652054C5FE9AA0F58D999226DC052_Emitter_Func_(Context);
ExitStatScope(/**SetVariables_65B652054C5FE9AA0F58D999226DC052_Emitter_Func_*/);
float3 Constant2 = float3(0,0,0);
EnterStatScope(2 /**SetVariables_A5326F1C41DDC2193E3BC489DAD6D943_Emitter_Func_*/);
SetVariables_A5326F1C41DDC2193E3BC489DAD6D943_Emitter_Func_(Context);
ExitStatScope(/**SetVariables_A5326F1C41DDC2193E3BC489DAD6D943_Emitter_Func_*/);
ExitStatScope(/**SimulationStage_0*/);
EnterStatScope(3 /**SimulationStage_0_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = 0;
EnterStatScope(4 /**SimulationStage_0_MapMain*/);
Simulate(Context);
ExitStatScope(/**SimulationStage_0_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Particles.UniqueID);
ExitStatScope(/**SimulationStage_0_Main*/);
EnterStatScope(1 /**SimulationStage_0_Main*/);
EnterStatScope(2 /**SimulationStage_0_MapMain*/);
‰S∫Ì=M9O†<ù.Ü;mîx
float Emitter_SimGrid_Density;
float4 Value;
FParamMap0_Local_Grid3D_SetRTValues Grid3D_SetRTValues;
float Red;
FParamMap0_Grid3D_SetRTValues Grid3D_SetRTValues;
FParamMap0_Local Local;
void ExecutionIndexToGridIndex_Emitter_SimGrid(int In_InstanceData, out int Out_IndexX, out int Out_IndexY, out int Out_IndexZ);
void SetRenderTargetValue_Emitter_SimRT_UEImpureCall(int In_InstanceData, bool In_Enabled, int In_IndexX, int In_IndexY, int In_IndexZ, float4 In_Value);
void Grid3D_SetRTValues_Emitter_Func_(inout FSimulationContext Context);
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.Enable"
int Constant3 = 1;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.SetFromVector"
int Constant4 = 0;
float Constant5 = 0;
float Constant6 = 0;
float Constant7 = 0;
float4 Output1;
Output1.r = Context.Map.Grid3D_SetRTValues.Red;
Output1.g = Constant5;
Output1.b = Constant6;
Output1.a = Constant7;
Context.Map.Local.Grid3D_SetRTValues.Value = Output1;
bool Constant8 = true;
//SetConstantByStaticVariable "/Grid 3D Set RTValues/Map Get/Map Get->Module.UseIterationGrid"
int Constant9 = 1;
int ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexX;
int ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexY;
int ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexZ;
ExecutionIndexToGridIndex_Emitter_SimGrid(1, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexX, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexY, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexZ);
SetRenderTargetValue_Emitter_SimRT_UEImpureCall(0, Constant8, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexX, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexY, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexZ, Context.Map.Local.Grid3D_SetRTValues.Value);
Context.Map.Grid3D_SetRTValues.Red = Context.Map.Emitter.SimGrid.Density;
float Constant = 0;
float Constant1 = 0;
float Constant2 = 0;
EnterStatScope(1 /**Grid3D_SetRTValues_Emitter_Func_*/);
Grid3D_SetRTValues_Emitter_Func_(Context);
ExitStatScope(/**Grid3D_SetRTValues_Emitter_Func_*/);
EnterStatScope(2 /**SimulationStage_0_Main*/);
Context.Map.Emitter.SimGrid.Density = Emitter_SimGrid_Density;
EnterStatScope(3 /**SimulationStage_0_MapMain*/);
FParamMap0_SetVariables_89CBE36044D8609DC64416941C3C9573_Emitter_SimGrid SimGrid;
FParamMap0_SetVariables_89CBE36044D8609DC64416941C3C9573_Emitter Emitter;
FParamMap0_SetVariables_89CBE36044D8609DC64416941C3C9573 SetVariables_89CBE36044D8609DC64416941C3C9573;
void ScratchDynamicInput_Emitter_Func_(out float Out_Output, inout FSimulationContext Context);
void SetVariables_89CBE36044D8609DC64416941C3C9573_Emitter_Func_(inout FSimulationContext Context);
ExecutionIndexToGridIndex_Emitter_SimGrid(0, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexX, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexY, ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexZ);
float3 Output1;
Output1.x = ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexX;
Output1.y = ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexY;
Output1.z = ExecutionIndexToGridIndex_Emitter_SimGridOutput_IndexZ;
int Constant = 32;
float3 Result = Output1 - Constant;
float Result1 = length(Result);
float Constant1 = 22;
bool Result2 = NiagaraAll(Result1 < Constant1);
float Constant2 = 0.1;
float Constant3 = 0;
float Constant4 = (0.0);
float NiagaraFloat_SelectResult = Constant4;
NiagaraFloat_SelectResult = Constant2;
NiagaraFloat_SelectResult = Constant3;
Out_Output = NiagaraFloat_SelectResult;
Context.Map.Emitter.SimGrid.Density = Context.Map.SetVariables_89CBE36044D8609DC64416941C3C9573.Emitter.SimGrid.Density;
float ScratchDynamicInput_Emitter_Func_Output_Output;
ScratchDynamicInput_Emitter_Func_(ScratchDynamicInput_Emitter_Func_Output_Output, Context);
Context.Map.SetVariables_89CBE36044D8609DC64416941C3C9573.Emitter.SimGrid.Density = ScratchDynamicInput_Emitter_Func_Output_Output;
EnterStatScope(1 /**SetVariables_89CBE36044D8609DC64416941C3C9573_Emitter_Func_*/);
SetVariables_89CBE36044D8609DC64416941C3C9573_Emitter_Func_(Context);
ExitStatScope(/**SetVariables_89CBE36044D8609DC64416941C3C9573_Emitter_Func_*/);
EnterStatScope(0 /**SpawnScript_0*/);
// Begin HandleMissingDefaultValues
// End HandleMissingDefaultValues
ExitStatScope(/**SpawnScript_0*/);
EnterStatScope(1 /**SpawnScript_0_Main*/);
Context.Map.Particles.UniqueID = 0;
Context.Map.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + ExecIndex();
EnterStatScope(2 /**SpawnScript_0_MapMain*/);
ExitStatScope(/**SpawnScript_0_MapMain*/);
ExitStatScope(/**SpawnScript_0_Main*/);
EnterStatScope(0 /**UpdateScript_1*/);
ExitStatScope(/**UpdateScript_1*/);
EnterStatScope(1 /**UpdateScript_1_Main*/);
Context.Map.Particles.UniqueID = InputDataInt(0, 0);
Context.Map.Array.UniqueID = 0;
EnterStatScope(2 /**UpdateScript_1_MapMain*/);
ExitStatScope(/**UpdateScript_1_MapMain*/);
ExitStatScope(/**UpdateScript_1_Main*/);
ˇ¶Z;JäéÉ’˙sæ∂
E¥ÌOüEÎí;
Ë∫Á`n;Có
¡É*ûóˆ•Ä.;ƒ—

