;÷6[î­L¶p&i 
fM²;Ê=dp'
kå$;Ê`
-gð;,«
¹´[ö/;æE·0”ÓçÔã9`
»7ÉQô~I®æ¸p;b–¼]
ðsžWuÏNN«Ž‡;ÄÊqû`
wrÈ;z,mE‹fö
ÏB†;ýª
&d;yrÏ÷
xÉ@1A±;N-R²BÒ
v½}¢I­BÆ;xHø>é
¤1ÑK;;ÔF™}É6
M¶®ú‚é;·
S;A€rÂOâÄHš
Ê;éF‡+ãõ
 Mâb b¾F„
;Á½°÷P
‰ã;]’ŸÍM½¦-?DBX
ªè;ÕA¿Z«
¿ö£u‹ñ;N·HÔfÛT¼z^
êNÙ;©â¼@®ÍcˆÃÂiMX
êNÙ;©â¼@®ÍcˆÃÂiM`
G¨b$be; ^
G¨b$be; `
lêMLè;cM¤
‚±[µ;øJ€!ô¤ùÕJ `
A?Kš«ÝJ°ï†Õ;*xq‚
ÀEé M3ÇB¬ù§ÇÙ;®
A?Kš«ÝJ°ï†Õ;*xq
uN;C­’A·Ñl
¼ZHšPP[N;”Ú
EÖoÁ:–;L¹
S;A€rÂOâÄHšv
S;A€rÂOâÄHš
Q¡¿nNª;EŽ1óu‚d
C;¦lB™é5}ì
¢Õa§£&~A™Lž¥ñÒ; x
¢Õa§£&~A™Lž¥ñÒ; 
2ûK ¹÷ªÉ^l;]
M¶®ú‚é;·}
M¶®ú‚é;·²
NŸÑn;G
ï›>Ö;±`
uD;‰ˆ<
Bˆ;râ=µ¦Y
¸ãÈ.òõNL¥:øÄ;!@û
¸ãÈ.òõNL¥:øÄ;!@.
// Shader generated by Niagara HLSL Translator
int ID;
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
float Emitter_SimDt;
float Emitter_FoamDx;
int UniqueID;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
NiagaraEmitterID ID;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
int ExecIndex;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
float Foam;
float FoamDx;
FParamMap0_Emitter_FoamGridCollection FoamGridCollection;
float SimDt;
FParamMap0_AdvectFoam AdvectFoam;
FParamMap0_Array Array;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Particles Particles;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void ExecutionIndexToGridIndex_Emitter_FoamGridCollection(int In_InstanceData, out int Out_IndexX, out int Out_IndexY);
void IndexToUnit_Emitter_FoamGridCollection(int In_InstanceData, float In_IndexX, float In_IndexY, out float3 Out_Unit);
void SampleGrid_Emitter_FoamGridCollection(int In_InstanceData, float In_UnitX, float In_UnitY, int In_AttributeIndex, out float Out_Value);
void SampleGrid_Emitter_SimGridReader(int In_InstanceData, float In_UnitX, float In_UnitY, int In_AttributeIndex, out float Out_Value);
void CustomHlsl001B19195CF45AC6367CB6FC4A34E61C90EEmitter_FoamGridCollectionEmitter_SimGridReader_Func_(float In_GridSample, int In_IndexX, int In_IndexY, float In_FoamDx, float In_SimDt, float In_AdvectionVelocityMult, float3 In_CurrUnit, int In_VelocityIndex, out float Out_OutGridVal);
void AdvectFoam_Emitter_Func_(inout FSimulationContext Context);
float GetSpawnInterpolation();
int d = 0;
Out_OutGridVal = In_GridSample;
float Scale = In_SimDt / In_FoamDx * In_AdvectionVelocityMult;
float2 Index = float2(In_IndexX, In_IndexY);
float TmpVal;
// sample velocity grid at current grid cell in unit space
float2 Velocity;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_VelocityIndex, TmpVal);
Velocity.x = TmpVal;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_VelocityIndex+1, TmpVal);
Velocity.y = TmpVal;
float2 SampleIndex = Index - Scale * Velocity;
float3 SampleUnit;
IndexToUnit_Emitter_FoamGridCollection(0, SampleIndex.x, SampleIndex.y, SampleUnit);
SampleGrid_Emitter_FoamGridCollection(0, SampleUnit.x, SampleUnit.y, 0, Out_OutGridVal);
float Constant2 = 1;
int Constant3 = 0;
int ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexX;
int ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexY;
ExecutionIndexToGridIndex_Emitter_FoamGridCollection(0, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexX, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexY);
float3 IndexToUnit_Emitter_FoamGridCollectionOutput_Unit;
IndexToUnit_Emitter_FoamGridCollection(0, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexX, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexY, IndexToUnit_Emitter_FoamGridCollectionOutput_Unit);
float CustomHlsl001B19195CF45AC6367CB6FC4A34E61C90EEmitter_FoamGridCollectionEmitter_SimGridReader_Func_Output_OutGridVal;
CustomHlsl001B19195CF45AC6367CB6FC4A34E61C90EEmitter_FoamGridCollectionEmitter_SimGridReader_Func_(Context.Map.Emitter.FoamGridCollection.Foam, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexX, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexY, Context.Map.Emitter.FoamDx, Context.Map.AdvectFoam.SimDt, Constant2, IndexToUnit_Emitter_FoamGridCollectionOutput_Unit, Constant3, CustomHlsl001B19195CF45AC6367CB6FC4A34E61C90EEmitter_FoamGridCollectionEmitter_SimGridReader_Func_Output_OutGridVal);
Context.Map.Emitter.FoamGridCollection.Foam = CustomHlsl001B19195CF45AC6367CB6FC4A34E61C90EEmitter_FoamGridCollectionEmitter_SimGridReader_Func_Output_OutGridVal;
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**SimulationStage_0*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
Context.Map.AdvectFoam.SimDt = Context.Map.Emitter.SimDt;
float Constant = 1;
int Constant1 = 0;
EnterStatScope(1 /**AdvectFoam_Emitter_Func_*/);
AdvectFoam_Emitter_Func_(Context);
ExitStatScope(/**AdvectFoam_Emitter_Func_*/);
ExitStatScope(/**SimulationStage_0*/);
EnterStatScope(2 /**SimulationStage_0_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Emitter.SimDt = Emitter_SimDt;
Context.Map.Emitter.FoamDx = Emitter_FoamDx;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
Context.Map.Engine.ExecIndex = ExecIndex();
Context.Map.Engine.Emitter.ID.ID = 0;
EnterStatScope(3 /**SimulationStage_0_MapMain*/);
Simulate(Context);
ExitStatScope(/**SimulationStage_0_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Particles.UniqueID);
ExitStatScope(/**SimulationStage_0_Main*/);
¨Ô;9ÃB”èÒ=iÀ
float Emitter_dx;
float4x4 Emitter_Grid2D_CreateUnitToWorldTransform_UnitToWorld;
float dx;
float4x4 UnitToSimulation;
float4x4 UnitToWorld;
FParamMap0_Emitter_Grid2D_CreateUnitToWorldTransform Grid2D_CreateUnitToWorldTransform;
FParamMap0_UpdateFoam UpdateFoam;
void GetNumCells_Emitter_SimGridReader(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY);
void CustomHlslB8C221B1497D2EBFFB357C974F052AD4Emitter_SimGridReader_Func_(float In_GridSample, int In_IndexX, int In_IndexY, float In_FoamDx, float In_SimDt, float In_SimDx, float In_MinEmitVorticity, float In_MaxEmitVorticity, float In_EmissionMult, float3 In_SimPos, float In_NoiseScale, float In_a, float3 In_CurrUnit, int In_NumCellsX, int In_NumCellsY, float In_MinEmitCurvature, float In_MaxEmitCurvature, float In_Time, float In_NoiseSpeed, float In_MinCurvatureEmitAngle, float In_MinEmitAcceleration, float In_MaxEmitAcceleration, int In_VelocityIndex, int In_NormalIndex, int In_WaterDepthIndex, int In_PrevVelocityIndex, int In_HeightIndex, out float Out_OutGridVal);
void UpdateFoam_Emitter_Func_(inout FSimulationContext Context);
float OneOverSimUnitDxX = 1./In_NumCellsX;
float OneOverSimUnitDxY = 1./In_NumCellsY;
// Dissipate existing value
Out_OutGridVal -= In_a * In_SimDt;
Out_OutGridVal = max(Out_OutGridVal, 0.0);
// vorticity
float vx_1;
float vx_m1;
float vy_1;
float vy_m1;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y+OneOverSimUnitDxY, In_VelocityIndex, vx_1);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y-OneOverSimUnitDxY, In_VelocityIndex, vx_m1);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x+OneOverSimUnitDxX, In_CurrUnit.y, In_VelocityIndex+1, vy_1);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x-OneOverSimUnitDxX, In_CurrUnit.y, In_VelocityIndex+1, vy_m1);
float curl = abs(((vx_1-vx_m1) - (vy_1-vy_m1)) / (2. * In_SimDx));
// velocity
float vx;
float vy;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_VelocityIndex, vx);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_VelocityIndex+1, vy);
Velocity = float2(vx,vy);
// acceleration
float prev_vx;
float prev_vy;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_PrevVelocityIndex, prev_vx);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_PrevVelocityIndex+1, prev_vy);
float2 Acceleration = (Velocity - float2(prev_vx, prev_vy)) / In_SimDt;
float AccelerationMag = length(Acceleration);
// curvature
float Height;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_HeightIndex, Height);
float3 World = In_SimPos;
World.z += Height;
float3 Normal;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_NormalIndex, Normal.x);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_NormalIndex+1, Normal.y);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_NormalIndex+2, Normal.z);
float3 Normal_right;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x+OneOverSimUnitDxX, In_CurrUnit.y, In_NormalIndex, Normal_right.x);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x+OneOverSimUnitDxX, In_CurrUnit.y, In_NormalIndex+1, Normal_right.y);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x+OneOverSimUnitDxX, In_CurrUnit.y, In_NormalIndex+2, Normal_right.z);
float3 World_right = In_SimPos;
World_right.x += In_SimDx;
float TmpH;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x+OneOverSimUnitDxX, In_CurrUnit.y, In_HeightIndex, TmpH);
World_right.z += TmpH;
float3 DiffTmp = World - World_right;
float Curvature_right = dot(Normal - Normal_right, DiffTmp) / dot(DiffTmp, DiffTmp);
float3 Normal_up;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y+OneOverSimUnitDxY, In_NormalIndex, Normal_up.x);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y+OneOverSimUnitDxY, In_NormalIndex+1, Normal_up.y);
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y+OneOverSimUnitDxY, In_NormalIndex+2, Normal_up.z);
float3 World_up = In_SimPos;
World_up.y += In_SimDx;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y+OneOverSimUnitDxY, 3, TmpH);
World_up.z += TmpH;
DiffTmp = World - World_up;
float Curvature_up = dot(Normal - Normal_up, DiffTmp) / dot(DiffTmp, DiffTmp);
float Curvature = abs((Curvature_right + Curvature_up) * .5);
// facing ratio of normal and velocity
float CurvatureMult = 1;//smoothstep(MinCurvatureEmitAngle, 1, dot(normalize(Velocity), Normal));
// Noise
float NoiseVal = (FastGradientPerlinNoise3D_TEX(World*In_NoiseScale+In_Time * In_NoiseSpeed)+1)*.5;
NoiseVal = smoothstep(.5, 1, NoiseVal);
// Emit
float EmitVal = 0;
EmitVal += smoothstep(In_MinEmitVorticity, In_MaxEmitVorticity, curl);
EmitVal += smoothstep(In_MinEmitAcceleration, In_MaxEmitAcceleration, AccelerationMag);
EmitVal += smoothstep(In_MinEmitCurvature, In_MaxEmitCurvature, Curvature) * CurvatureMult;
Out_OutGridVal += EmitVal  * In_EmissionMult * NoiseVal;
// OutGridVal = VelocityMag;
// OutGridVal = curl;
// OutGridVal = AccelerationMag*.001;
// OutGridVal = Curvature*10;
Out_OutGridVal = saturate(Out_OutGridVal);
// only emit foam where we have water depth
float WaterDepth;
SampleGrid_Emitter_SimGridReader(1, In_CurrUnit.x, In_CurrUnit.y, In_WaterDepthIndex, WaterDepth);
Out_OutGridVal *= WaterDepth > 1e-5;
//OutGridVal = NoiseVal;
float Constant16 = 500;
float Constant17 = 1000;
float Constant18 = 1;
float Constant19 = 0.01;
float Constant20 = 0.3;
float Constant21 = 2134;
float Constant22 = 111111;
float Constant23 = 0;
float Constant24 = 1234;
float Constant25 = 1234;
float Constant26 = 111111;
int Constant27 = 0;
int Constant28 = 0;
int Constant29 = 0;
int Constant30 = 0;
int Constant31 = 0;
float3 Result = mul(float4(IndexToUnit_Emitter_FoamGridCollectionOutput_Unit,1.0),Context.Map.UpdateFoam.UnitToSimulation).xyz;
int GetNumCells_Emitter_SimGridReaderOutput_NumCellsX;
int GetNumCells_Emitter_SimGridReaderOutput_NumCellsY;
GetNumCells_Emitter_SimGridReader(1, GetNumCells_Emitter_SimGridReaderOutput_NumCellsX, GetNumCells_Emitter_SimGridReaderOutput_NumCellsY);
float CustomHlslB8C221B1497D2EBFFB357C974F052AD4Emitter_SimGridReader_Func_Output_OutGridVal;
CustomHlslB8C221B1497D2EBFFB357C974F052AD4Emitter_SimGridReader_Func_(Context.Map.Emitter.FoamGridCollection.Foam, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexX, ExecutionIndexToGridIndex_Emitter_FoamGridCollectionOutput_IndexY, Context.Map.Emitter.FoamDx, Context.Map.UpdateFoam.SimDt, Context.Map.UpdateFoam.dx, Constant25, Constant26, Constant18, Result, Constant19, Constant20, IndexToUnit_Emitter_FoamGridCollectionOutput_Unit, GetNumCells_Emitter_SimGridReaderOutput_NumCellsX, GetNumCells_Emitter_SimGridReaderOutput_NumCellsY, Constant21, Constant22, Context.Map.Engine.Time, Constant23, Constant24, Constant16, Constant17, Constant27, Constant28, Constant29, Constant30, Constant31, CustomHlslB8C221B1497D2EBFFB357C974F052AD4Emitter_SimGridReader_Func_Output_OutGridVal);
Context.Map.Emitter.FoamGridCollection.Foam = CustomHlslB8C221B1497D2EBFFB357C974F052AD4Emitter_SimGridReader_Func_Output_OutGridVal;
Context.Map.UpdateFoam.dx = Context.Map.Emitter.dx;
Context.Map.UpdateFoam.SimDt = Context.Map.Emitter.SimDt;
Context.Map.UpdateFoam.UnitToSimulation = Context.Map.Emitter.Grid2D_CreateUnitToWorldTransform.UnitToWorld;
float Constant = 500;
float Constant1 = 1000;
float Constant3 = 0.01;
float Constant4 = 0.3;
float Constant5 = 2134;
float Constant6 = 111111;
float Constant7 = 0;
float Constant8 = 1234;
float Constant9 = 1234;
float Constant10 = 111111;
int Constant11 = 0;
int Constant12 = 0;
int Constant13 = 0;
int Constant14 = 0;
int Constant15 = 0;
EnterStatScope(1 /**UpdateFoam_Emitter_Func_*/);
UpdateFoam_Emitter_Func_(Context);
ExitStatScope(/**UpdateFoam_Emitter_Func_*/);
Context.Map.Emitter.dx = Emitter_dx;
Context.Map.Emitter.Grid2D_CreateUnitToWorldTransform.UnitToWorld = Emitter_Grid2D_CreateUnitToWorldTransform_UnitToWorld;
Context.Map.Engine.Time = Engine_Time;
EnterStatScope(0 /**SpawnScript*/);
// Begin HandleMissingDefaultValues
// End HandleMissingDefaultValues
ExitStatScope(/**SpawnScript*/);
EnterStatScope(1 /**SpawnScript_Main*/);
Context.Map.Particles.UniqueID = 0;
Context.Map.Particles.UniqueID = Engine_Emitter_TotalSpawnedParticles + ExecIndex();
EnterStatScope(2 /**SpawnScript_MapMain*/);
ExitStatScope(/**SpawnScript_MapMain*/);
ExitStatScope(/**SpawnScript_Main*/);
EnterStatScope(0 /**UpdateScript*/);
ExitStatScope(/**UpdateScript*/);
EnterStatScope(1 /**UpdateScript_Main*/);
Context.Map.Particles.UniqueID = InputDataInt(0, 0);
Context.Map.Array.UniqueID = 0;
EnterStatScope(2 /**UpdateScript_MapMain*/);
ExitStatScope(/**UpdateScript_MapMain*/);
ExitStatScope(/**UpdateScript_Main*/);
³í;¡G‘îè5u2¾ù`
Áƒ*ž—ö¥€.;ÄÑ

