int IGNORE;
const int IntParticleRadius = round(ParticleIndexRadius);
for (int xx = -IntParticleRadius; xx <= IntParticleRadius; ++xx) {
for (int yy = -IntParticleRadius; yy <= IntParticleRadius; ++yy) {
for (int zz = -IntParticleRadius; zz <= IntParticleRadius; ++zz) {
    const int3 Offset = int3(xx,yy,zz);
    const int3 CurrIndex = FloatIndex + Offset;
    if (CurrIndex.x >= 0 && CurrIndex.x < NumCellsX && 
        CurrIndex.y >= 0 && CurrIndex.y < NumCellsY &&
        CurrIndex.z >= 0 && CurrIndex.z < NumCellsZ) 
        const float Falloff = 1. - smoothstep(ParticleIndexRadius-1.41421, ParticleIndexRadius+1, length(FloatIndex - CurrIndex));
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+0, VectorValue.x * Falloff, IGNORE);
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+1, VectorValue.y * Falloff, IGNORE);
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+2, VectorValue.z * Falloff, IGNORE);
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+3, Falloff, IGNORE);
    if (length(Offset) <= ParticleIndexRadius && 
        CurrIndex.x >= 0 && CurrIndex.x < NumCellsX && 
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+0, VectorValue.x, IGNORE);
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+1, VectorValue.y, IGNORE);
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+2, VectorValue.z, IGNORE);
        Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+3, 1.0, IGNORE);
int NumStreakParticles = 1;
    NumStreakParticles = min(MaxStreakSamples, max(1, StreakDensity * IndexVelocityMagnitude / (2. * ParticleIndexRadius)));
// Don't normalize for vector4s for now
float3 ValueToUse = VectorValue;// / NumStreakParticles;
for (int ww = 0; ww < NumStreakParticles; ++ww)
    float StreakPosition = 1.0 * ww / NumStreakParticles;
    float3 FloatIndexToUse = FloatIndex - StreakPosition * IndexVelocity;
    float ParticleIndexRadiusToUse = lerp(ParticleIndexRadius, PreviousParticleIndexRadius, StreakPosition);
    int IntParticleRadius = ceil(ParticleIndexRadiusToUse);
    for (int xx = -IntParticleRadius; xx <= IntParticleRadius; ++xx) {
    for (int yy = -IntParticleRadius; yy <= IntParticleRadius; ++yy) {
    for (int zz = -IntParticleRadius; zz <= IntParticleRadius; ++zz) {
        const int3 Offset = int3(xx,yy,zz);
        const int3 CurrIndex = FloatIndexToUse + Offset;
        if (length(Offset) <= ParticleIndexRadiusToUse && 
            CurrIndex.x >= 0 && CurrIndex.x < NumCellsX && 
            CurrIndex.y >= 0 && CurrIndex.y < NumCellsY &&
            CurrIndex.z >= 0 && CurrIndex.z < NumCellsZ) 
            float Falloff = 1.0;
            if (UseFalloff)
                 Falloff = 1. - smoothstep(max(0,ParticleIndexRadiusToUse-2.41421), ParticleIndexRadiusToUse, length(FloatIndexToUse - CurrIndex));
            if (Split)
                GridXY.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, 0, ValueToUse.x * Falloff, IGNORE);
                GridXY.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, 1, ValueToUse.y * Falloff, IGNORE);
                GridZW.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, 0, ValueToUse.z * Falloff, IGNORE);
                GridZW.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, 1, 1.0, IGNORE);
            else
                Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+0, ValueToUse.x * Falloff, IGNORE);
                Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+1, ValueToUse.y * Falloff, IGNORE);
                Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+2, ValueToUse.z * Falloff, IGNORE);
                Grid.InterlockedAddFloatGridValue(CurrIndex.x, CurrIndex.y, CurrIndex.z, GridAttributeIndex+3, 1.0, IGNORE);
                // Required an extra grid so the average value can be calculated. Max operations will not work for vectors with negative values.
// Shader generated by Niagara HLSL Translator
int Index;
int AcquireTag;
float Engine_WorldDeltaTime;
float Engine_DeltaTime;
float Engine_InverseDeltaTime;
float Engine_Time;
float Engine_RealTime;
int Engine_QualityLevel;
int Engine_PaddingInt32_0;
int Engine_PaddingInt32_1;
float Engine_Owner_TimeSinceRendered;
float Engine_Owner_LODDistance;
float Engine_Owner_LODDistanceFraction;
float Engine_System_Age;
int Engine_Owner_ExecutionState;
int Engine_System_TickCount;
int Engine_System_NumEmitters;
int Engine_System_NumEmittersAlive;
int Engine_System_SignificanceIndex;
int Engine_System_RandomSeed;
int Engine_System_CurrentTimeStep;
int Engine_System_NumTimeSteps;
float Engine_System_TimeStepFraction;
int Engine_System_NumParticles;
int Engine_System_PaddingInt32_0;
int Engine_System_PaddingInt32_1;
float4x4 Engine_Owner_SystemLocalToWorld;
float4x4 Engine_Owner_SystemWorldToLocal;
float4x4 Engine_Owner_SystemLocalToWorldTransposed;
float4x4 Engine_Owner_SystemWorldToLocalTransposed;
float4x4 Engine_Owner_SystemLocalToWorldNoScale;
float4x4 Engine_Owner_SystemWorldToLocalNoScale;
float4 Engine_Owner_Rotation;
float3 Engine_Owner_Position;
int Engine_Owner_PaddingInt32_0;
float3 Engine_Owner_Velocity;
int Engine_Owner_PaddingInt32_1;
float3 Engine_Owner_SystemXAxis;
int Engine_Owner_PaddingInt32_2;
float3 Engine_Owner_SystemYAxis;
int Engine_Owner_PaddingInt32_3;
float3 Engine_Owner_SystemZAxis;
int Engine_Owner_PaddingInt32_4;
float3 Engine_Owner_Scale;
int Engine_Owner_PaddingInt32_5;
float4 Engine_Owner_LWCTile;
int Engine_Emitter_NumParticles;
int Engine_Emitter_TotalSpawnedParticles;
float Engine_Emitter_SpawnCountScale;
float Emitter_Age;
int Emitter_RandomSeed;
int Engine_Emitter_InstanceSeed;
int Engine_Emitter_PaddingInt32_0;
int Engine_Emitter_PaddingInt32_1;
int Module_GridAttributeIndex;
float3 Module_GridFloatIndex;
float Module_ParticleIndexRadius;
float3 Module_Value;
float3 Module_IndexVelocity;
float Module_IndexVelocityMagnitude;
float Module_StreakDensity;
float Module_PreviousParticleIndexRadius;
int Module_MaxStreakSamples;
int GridAttributeIndex;
float3 GridFloatIndex;
float3 IndexVelocity;
float IndexVelocityMagnitude;
int MaxStreakSamples;
float ParticleIndexRadius;
float PreviousParticleIndexRadius;
float StreakDensity;
float3 Value;
float Age;
int CurrentTimeStep;
int NumEmitters;
int NumEmittersAlive;
int NumParticles;
int NumTimeSteps;
int PaddingInt32_0;
int PaddingInt32_1;
int RandomSeed;
int SignificanceIndex;
int TickCount;
float TimeStepFraction;
int ExecutionState;
float LODDistance;
float LODDistanceFraction;
float4 LWCTile;
int PaddingInt32_2;
int PaddingInt32_3;
int PaddingInt32_4;
int PaddingInt32_5;
float3 Position;
float4 Rotation;
float3 Scale;
float4x4 SystemLocalToWorld;
float4x4 SystemLocalToWorldNoScale;
float4x4 SystemLocalToWorldTransposed;
float4x4 SystemWorldToLocal;
float4x4 SystemWorldToLocalNoScale;
float4x4 SystemWorldToLocalTransposed;
float3 SystemXAxis;
float3 SystemYAxis;
float3 SystemZAxis;
float TimeSinceRendered;
float3 Velocity;
int InstanceSeed;
float SpawnCountScale;
int TotalSpawnedParticles;
float DeltaTime;
FParamMap0_Engine_Emitter Emitter;
float InverseDeltaTime;
FParamMap0_Engine_Owner Owner;
int QualityLevel;
float RealTime;
FParamMap0_Engine_System System;
float Time;
float WorldDeltaTime;
FParamMap0_Emitter Emitter;
FParamMap0_Engine Engine;
FParamMap0_Module Module;
FParamMap0 Map;
static float HackSpawnInterp = 1.0;
void GetNumCells_Emitter_Grid(int In_InstanceData, out int Out_NumCellsX, out int Out_NumCellsY, out int Out_NumCellsZ);
void InterlockedAddFloatGridValue_Emitter_Grid(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
void InterlockedAddFloatGridValue_Emitter_GridXY(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
void InterlockedAddFloatGridValue_Emitter_GridZW(int In_InstanceData, int In_IndexX, int In_IndexY, int In_IndexZ, int In_AttributeIndex, float In_Value, out int Out_IGNORE);
void CustomHlsl0020B2366C2497371BCDE36EF97B8099B63Emitter_GridEmitter_GridXYEmitter_GridZW_FuncASC95ASC95GridXYNiagaraDataInterfaceRasterizationGrid3D_GridZWNiagaraDataInterfaceRasterizationGrid3D(int In_GridAttributeIndex, float3 In_FloatIndex, float In_ParticleIndexRadius, float3 In_VectorValue, int In_NumCellsX, int In_NumCellsY, int In_NumCellsZ, bool In_UseFalloff, float3 In_IndexVelocity, float In_IndexVelocityMagnitude, float In_StreakDensity, float In_PreviousParticleIndexRadius, int In_MaxStreakSamples, bool In_UseStreaking, bool In_Split, inout FSimulationContext Context);
float GetSpawnInterpolation();
    NumStreakParticles = min(In_MaxStreakSamples, max(1, In_StreakDensity * In_IndexVelocityMagnitude / (2. * In_ParticleIndexRadius)));
float3 ValueToUse = In_VectorValue;// / NumStreakParticles;
    float3 FloatIndexToUse = In_FloatIndex - StreakPosition * In_IndexVelocity;
    float ParticleIndexRadiusToUse = lerp(In_ParticleIndexRadius, In_PreviousParticleIndexRadius, StreakPosition);
            CurrIndex.x >= 0 && CurrIndex.x < In_NumCellsX && 
            CurrIndex.y >= 0 && CurrIndex.y < In_NumCellsY &&
            CurrIndex.z >= 0 && CurrIndex.z < In_NumCellsZ) 
            if (In_UseFalloff)
            if (In_Split)
                InterlockedAddFloatGridValue_Emitter_GridXY(1, CurrIndex.x, CurrIndex.y, CurrIndex.z, 0, ValueToUse.x * Falloff, IGNORE);
                InterlockedAddFloatGridValue_Emitter_GridXY(1, CurrIndex.x, CurrIndex.y, CurrIndex.z, 1, ValueToUse.y * Falloff, IGNORE);
                InterlockedAddFloatGridValue_Emitter_GridZW(2, CurrIndex.x, CurrIndex.y, CurrIndex.z, 0, ValueToUse.z * Falloff, IGNORE);
                InterlockedAddFloatGridValue_Emitter_GridZW(2, CurrIndex.x, CurrIndex.y, CurrIndex.z, 1, 1.0, IGNORE);
                InterlockedAddFloatGridValue_Emitter_Grid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, In_GridAttributeIndex+0, ValueToUse.x * Falloff, IGNORE);
                InterlockedAddFloatGridValue_Emitter_Grid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, In_GridAttributeIndex+1, ValueToUse.y * Falloff, IGNORE);
                InterlockedAddFloatGridValue_Emitter_Grid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, In_GridAttributeIndex+2, ValueToUse.z * Falloff, IGNORE);
                InterlockedAddFloatGridValue_Emitter_Grid(0, CurrIndex.x, CurrIndex.y, CurrIndex.z, In_GridAttributeIndex+3, 1.0, IGNORE);
return 1.0f;}
#if (SimulationStageIndex == 0) // MapSpawn
EnterStatScope(0 /**Grid3D_RasterizationSplatVector*/);
//Begin Initialize Parameter Map Defaults
//End Initialize Parameter Map Defaults
int GetNumCells_Emitter_GridOutput_NumCellsX;
int GetNumCells_Emitter_GridOutput_NumCellsY;
int GetNumCells_Emitter_GridOutput_NumCellsZ;
GetNumCells_Emitter_Grid(0, GetNumCells_Emitter_GridOutput_NumCellsX, GetNumCells_Emitter_GridOutput_NumCellsY, GetNumCells_Emitter_GridOutput_NumCellsZ);
bool Constant = false;
bool Constant1 = false;
bool Constant2 = false;
CustomHlsl0020B2366C2497371BCDE36EF97B8099B63Emitter_GridEmitter_GridXYEmitter_GridZW_FuncASC95ASC95GridXYNiagaraDataInterfaceRasterizationGrid3D_GridZWNiagaraDataInterfaceRasterizationGrid3D(Context.Map.Module.GridAttributeIndex, Context.Map.Module.GridFloatIndex, Context.Map.Module.ParticleIndexRadius, Context.Map.Module.Value, GetNumCells_Emitter_GridOutput_NumCellsX, GetNumCells_Emitter_GridOutput_NumCellsY, GetNumCells_Emitter_GridOutput_NumCellsZ, Constant, Context.Map.Module.IndexVelocity, Context.Map.Module.IndexVelocityMagnitude, Context.Map.Module.StreakDensity, Context.Map.Module.PreviousParticleIndexRadius, Context.Map.Module.MaxStreakSamples, Constant1, Constant2, Context);
ExitStatScope(/**Grid3D_RasterizationSplatVector*/);
EnterStatScope(1 /**Grid3D_RasterizationSplatVector_Main*/);
FSimulationContext Context = (FSimulationContext)0;
Context.Map.Module.GridAttributeIndex = Module_GridAttributeIndex;
Context.Map.Module.GridFloatIndex = Module_GridFloatIndex;
Context.Map.Module.ParticleIndexRadius = Module_ParticleIndexRadius;
Context.Map.Module.Value = Module_Value;
Context.Map.Module.IndexVelocity = Module_IndexVelocity;
Context.Map.Module.IndexVelocityMagnitude = Module_IndexVelocityMagnitude;
Context.Map.Module.StreakDensity = Module_StreakDensity;
Context.Map.Module.PreviousParticleIndexRadius = Module_PreviousParticleIndexRadius;
Context.Map.Module.MaxStreakSamples = Module_MaxStreakSamples;
Context.Map.Engine.Emitter.TotalSpawnedParticles = Engine_Emitter_TotalSpawnedParticles;
Context.Map.Emitter.RandomSeed = Emitter_RandomSeed;
Context.Map.Engine.Emitter.InstanceSeed = Engine_Emitter_InstanceSeed;
Context.Map.Engine.System.RandomSeed = Engine_System_RandomSeed;
ReadDataSets(Context);
EnterStatScope(2 /**Grid3D_RasterizationSplatVector_MapMain*/);
Simulate(Context);
ExitStatScope(/**Grid3D_RasterizationSplatVector_MapMain*/);
WriteDataSets(Context);
int TmpWriteIndex = OutputIndex(0, false, true);
OutputDataInt(0, 0, TmpWriteIndex, Context.Map.Module.GridAttributeIndex);
OutputDataFloat(0, 0, TmpWriteIndex, Context.Map.Module.GridFloatIndex.x);
OutputDataFloat(0, 1, TmpWriteIndex, Context.Map.Module.GridFloatIndex.y);
OutputDataFloat(0, 2, TmpWriteIndex, Context.Map.Module.GridFloatIndex.z);
OutputDataFloat(0, 3, TmpWriteIndex, Context.Map.Module.IndexVelocity.x);
OutputDataFloat(0, 4, TmpWriteIndex, Context.Map.Module.IndexVelocity.y);
OutputDataFloat(0, 5, TmpWriteIndex, Context.Map.Module.IndexVelocity.z);
OutputDataFloat(0, 6, TmpWriteIndex, Context.Map.Module.IndexVelocityMagnitude);
OutputDataInt(0, 1, TmpWriteIndex, Context.Map.Module.MaxStreakSamples);
OutputDataFloat(0, 7, TmpWriteIndex, Context.Map.Module.ParticleIndexRadius);
OutputDataFloat(0, 8, TmpWriteIndex, Context.Map.Module.PreviousParticleIndexRadius);
OutputDataFloat(0, 9, TmpWriteIndex, Context.Map.Module.StreakDensity);
OutputDataFloat(0, 10, TmpWriteIndex, Context.Map.Module.Value.x);
OutputDataFloat(0, 11, TmpWriteIndex, Context.Map.Module.Value.y);
OutputDataFloat(0, 12, TmpWriteIndex, Context.Map.Module.Value.z);
ExitStatScope(/**Grid3D_RasterizationSplatVector_Main*/);

