float2 Velocity = float2(Input_VelocityX, Input_VelocityY);
float Scale = DtOverDx * Gravity;
float LeftDepth;
float LeftHeight;
float2 LeftCollisionVelocity;
float LeftCollisionVelocityX;
float LeftCollisionMask;
float LeftBottomContour;
GridCollection.GetPreviousFloatValue<Attribute = "WaterDepth">(IndexX - 1, IndexY, LeftDepth);
GridCollection.GetPreviousFloatValue<Attribute = "WaterHeight">(IndexX - 1, IndexY, LeftHeight);
GridCollection.GetPreviousVector2DValue<Attribute = "CollisionVelocity">(IndexX - 1, IndexY, LeftCollisionVelocity);
LeftCollisionVelocityX = LeftCollisionVelocity.x;
GridCollection.GetPreviousFloatValue<Attribute = "IsCollider">(IndexX - 1, IndexY, LeftCollisionMask);
GridCollection.GetPreviousFloatValue<Attribute = "BottomContour">(IndexX - 1, IndexY, LeftBottomContour);
float DownDepth;
float DownHeight;
float2 DownCollisionVelocity;
float DownCollisionVelocityY;
float DownCollisionMask;
float DownBottomContour;
GridCollection.GetPreviousFloatValue<Attribute = "WaterDepth">(IndexX, IndexY-1, DownDepth);
GridCollection.GetPreviousFloatValue<Attribute = "WaterHeight">(IndexX, IndexY-1, DownHeight);
GridCollection.GetPreviousVector2DValue<Attribute = "CollisionVelocity">(IndexX, IndexY-1, DownCollisionVelocity);
DownCollisionVelocityY = DownCollisionVelocity.y;
GridCollection.GetPreviousFloatValue<Attribute = "IsCollider">(IndexX, IndexY-1, DownCollisionMask);
GridCollection.GetPreviousFloatValue<Attribute = "BottomContour">(IndexX, IndexY-1, DownBottomContour);
float eps = 1;
        LeftCollisionVelocityX = 0;
        LeftCollisionMask = 1. - smoothstep(0, eps, LeftDepth);
        LeftCollisionMask = 1. - smoothstep(0, eps, Input_WaterDepth);
        LeftCollisionMask = 1. - smoothstep(0, eps, Input_WaterDepth * LeftDepth);
    float h_x = Input_WaterHeight;
    float h_x_left = LeftHeight;
    Velocity.x -= Scale * (h_x - h_x_left);
    Velocity.x = lerp(Velocity.x, LeftCollisionVelocityX, LeftCollisionMask);
        DownCollisionVelocityY = 0;
        DownCollisionMask = 1. - smoothstep(0, eps, DownDepth);
        DownCollisionMask = 1. - smoothstep(0, eps, Input_WaterDepth);
        DownCollisionMask = 1. - smoothstep(0, eps, Input_WaterDepth * DownDepth);
    float h_y = Input_WaterHeight;
    float h_y_down = DownHeight;
    Velocity.y -= Scale * (h_y - h_y_down);
    Velocity.y = lerp(Velocity.y, DownCollisionVelocityY, DownCollisionMask);
    Velocity = lerp(Velocity, float2(Input_CollisionVelocityX, Input_CollisionVelocityY), Input_IsCollider);
    float VelMag = length(Velocity);
    if (VelMag > eps)
       Velocity = clamp(VelMag, 0., MaxVelocityMagnitude) * Velocity / VelMag;
VelocityX = Velocity.x * VelocityDissipation;
VelocityY = Velocity.y * VelocityDissipation;
VelocityX = 0;
VelocityY = 0;
Velocity = float2(Input_VelocityX, Input_VelocityY);
WaterGrid.GetPreviousFloatValue<Attribute = "WaterDepth">(IndexX - 1, IndexY, LeftDepth);
WaterGrid.GetPreviousFloatValue<Attribute = "WaterHeight">(IndexX - 1, IndexY, LeftHeight);
WaterGrid.GetPreviousFloatValue<Attribute = "WaterDepth">(IndexX, IndexY-1, DownDepth);
WaterGrid.GetPreviousFloatValue<Attribute = "WaterHeight">(IndexX, IndexY-1, DownHeight);
float eps = 1e-8;
float h_x = Input_WaterHeight;
float h_x_left = LeftHeight;
Velocity.x -= Scale * (h_x - h_x_left);
Velocity.x = lerp(Velocity.x, LeftCollisionVelocityX, LeftCollisionMask);
float h_y = Input_WaterHeight;
float h_y_down = DownHeight;
Velocity.y -= Scale * (h_y - h_y_down);
Velocity.y = lerp(Velocity.y, DownCollisionVelocityY, DownCollisionMask);
Velocity = lerp(Velocity, float2(Input_CollisionVelocityX, Input_CollisionVelocityY), Input_IsCollider);
float VelMag = length(Velocity);
   Velocity = clamp(VelMag, 0., MaxVelocityMagnitude) * Velocity / VelMag;
Velocity *= VelocityDissipation;

