float Vz_up;
Grid.GetGridValue(IndexX, IndexY+1, IndexZ, VectorIndex+2, Vz_up);
float Vz_down;
Grid.GetGridValue(IndexX, IndexY-1, IndexZ, VectorIndex+2, Vz_down);
float Vy_front;
Grid.GetGridValue(IndexX, IndexY, IndexZ+1, VectorIndex+1, Vy_front);
float Vy_back;
Grid.GetGridValue(IndexX, IndexY, IndexZ-1, VectorIndex+1, Vy_back);
float Vx_front;
Grid.GetGridValue(IndexX, IndexY, IndexZ+1, VectorIndex, Vx_front);
float Vx_back;
Grid.GetGridValue(IndexX, IndexY, IndexZ-1, VectorIndex, Vx_back);
float Vz_right;
Grid.GetGridValue(IndexX+1, IndexY, IndexZ, VectorIndex+2, Vz_right);
float Vz_left;
Grid.GetGridValue(IndexX-1, IndexY, IndexZ, VectorIndex+2, Vz_left);
float Vy_right;
Grid.GetGridValue(IndexX+1, IndexY, IndexZ, VectorIndex+1, Vy_right);
float Vy_left;
Grid.GetGridValue(IndexX+1, IndexY, IndexZ, VectorIndex+1, Vy_left);
float Vx_up;
Grid.GetGridValue(IndexX, IndexY+1, IndexZ, VectorIndex, Vx_up);
float Vx_down;
Grid.GetGridValue(IndexX, IndexY-1, IndexZ, VectorIndex, Vx_down);
) / (2. * dx);

