VelocityOut = float3(0,0,0);
const  int FLUID_CELL = 0;
const  int SOLID_CELL = 1;
const  int EMPTY_CELL = 2;
int CellType = round(B_center);
float B_right;
TransientGrid.GetGridValue(IndexX+1, IndexY, IndexZ, SimGrid_BoundaryIndex, B_right);
int CellType_right = round(B_right);
float B_left;
TransientGrid.GetGridValue(IndexX-1, IndexY, IndexZ, SimGrid_BoundaryIndex, B_left);
int CellType_left = round(B_left);
    VelocityOut.x = SV_x_left;
    VelocityOut.x = SV_x_right;
    VelocityOut.x = Velocity.x;
float B_up;
TransientGrid.GetGridValue(IndexX, IndexY+1, IndexZ, SimGrid_BoundaryIndex, B_up);
int CellType_up  = round(B_up);
float B_down;
TransientGrid.GetGridValue(IndexX, IndexY-1, IndexZ, SimGrid_BoundaryIndex, B_down);
int CellType_down  = round(B_down);
    VelocityOut.y = SV_y_down;
    VelocityOut.y = SV_y_up;
    VelocityOut.y = Velocity.y;
float B_front;
TransientGrid.GetGridValue(IndexX, IndexY, IndexZ+1, SimGrid_BoundaryIndex, B_front);
int CellType_front  = round(B_front);
float B_back;
TransientGrid.GetGridValue(IndexX, IndexY, IndexZ-1, SimGrid_BoundaryIndex, B_back);
int CellType_back  = round(B_back);
    VelocityOut.z = SV_z_front;
    VelocityOut.z = SV_z_back;
    VelocityOut.z = Velocity.z;
    VelocityOut.x = SV_x_center;
    VelocityOut.y = SV_y_center;
    VelocityOut.z = SV_z_center;
SV_x_right = 0;
SV_x_left = 0;
SV_y_up = 0;
SV_y_down = 0;
SV_z_front = 0;
SV_z_back = 0;
SolidVelocityGrid.GetGridValue(IndexX+1, IndexY, IndexZ, SolidVelocityIndex, SV_x_right);
SolidVelocityGrid.GetGridValue(IndexX-1, IndexY, IndexZ, SolidVelocityIndex, SV_x_left);
SolidVelocityGrid.GetGridValue(IndexX, IndexY+1, IndexZ, SolidVelocityIndex+1, SV_y_up);
SolidVelocityGrid.GetGridValue(IndexX, IndexY-1, IndexZ, SolidVelocityIndex+1, SV_y_down);
SolidVelocityGrid.GetGridValue(IndexX, IndexY, IndexZ+1, SolidVelocityIndex+2, SV_z_front);
SolidVelocityGrid.GetGridValue(IndexX, IndexY, IndexZ-1, SolidVelocityIndex+2, SV_z_back);
SolidVelocityGrid.GetGridValue(IndexX, IndexY, IndexZ, SolidVelocityIndex, SV_x_center);
SolidVelocityGrid.GetGridValue(IndexX, IndexY, IndexZ, SolidVelocityIndex+1, SV_y_center);
SolidVelocityGrid.GetGridValue(IndexX, IndexY, IndexZ, SolidVelocityIndex+2, SV_z_center);
float B_center;
TransientGrid.GetGridValue(IndexX, IndexY, IndexZ, SimGrid_BoundaryIndex, B_center);
VelocityOut = Velocity;
float4 B_center;
BoundaryGrid.GetPreviousVector4Value<Attribute="SolidVelocity_Boundary">(IndexX, IndexY, IndexZ, B_center);
int CellType = round(B_center.w);
float4 B_right;
BoundaryGrid.GetPreviousVector4Value<Attribute="SolidVelocity_Boundary">(IndexX+1, IndexY, IndexZ, B_right);
int CellType_right = round(B_right.w);
float4 B_left;
BoundaryGrid.GetPreviousVector4Value<Attribute="SolidVelocity_Boundary">(IndexX-1, IndexY, IndexZ, B_left);
int CellType_left = round(B_left.w);
    VelocityOut.x = B_left.x;
    VelocityOut.x = B_right.x;
float4 B_up;
BoundaryGrid.GetPreviousVector4Value<Attribute="SolidVelocity_Boundary">(IndexX, IndexY+1, IndexZ, B_up);
int CellType_up  = round(B_up.w);
float4 B_down;
BoundaryGrid.GetPreviousVector4Value<Attribute="SolidVelocity_Boundary">(IndexX, IndexY-1, IndexZ, B_down);
int CellType_down  = round(B_down.w);
    VelocityOut.y = B_down.y;
    VelocityOut.y = B_up.y;
float4 B_front;
BoundaryGrid.GetPreviousVector4Value<Attribute="SolidVelocity_Boundary">(IndexX, IndexY, IndexZ+1, B_front);
int CellType_front  = round(B_front.w);
float4 B_back;
BoundaryGrid.GetPreviousVector4Value<Attribute="SolidVelocity_Boundary">(IndexX, IndexY, IndexZ-1, B_back);
int CellType_back  = round(B_back.w);
    VelocityOut.z = B_front.z;
    VelocityOut.z = B_back.z;
    VelocityOut = B_center.xyz;
const int FLUID_CELL = 0;
const int SOLID_CELL = 1;
const int EMPTY_CELL = 2;
float3 TmpFraction;
Grid.GetPreviousVectorValue<Attribute="FaceFraction">(IndexX, IndexY, IndexZ, TmpFraction);
F_right = TmpFraction.x;
F_up = TmpFraction.y;
F_front = TmpFraction.z;
Grid.GetPreviousVectorValue<Attribute="FaceFraction">(IndexX-1, IndexY, IndexZ, TmpFraction);
F_left = TmpFraction.x;
F_down = TmpFraction.y;
Grid.GetPreviousVectorValue<Attribute="FaceFraction">(IndexX, IndexY, IndexZ - 1, TmpFraction);
F_back = TmpFraction.z;
F_right = round(B_right.w) == SOLID_CELL ? 1 : F_right;
F_left = round(B_left.w) == SOLID_CELL ? 1 : F_left;
F_up = round(B_up.w) == SOLID_CELL ? 1 : F_up;
F_down = round(B_down.w) == SOLID_CELL ? 1 : F_down;
F_front = round(B_front.w) == SOLID_CELL ? 1 : F_front;
F_back = round(B_back.w) == SOLID_CELL ? 1 : F_back;
VelocityOut.x = lerp(VelocityOut.x, B_left.x, F_left);
VelocityOut.x = lerp(VelocityOut.x, B_right.x, F_right);
VelocityOut.y = lerp(VelocityOut.y, B_down.y, F_down);
VelocityOut.y = lerp(VelocityOut.y, B_up.y, F_up);
VelocityOut.z = lerp(VelocityOut.z, B_front.z, F_front);
VelocityOut.z = lerp(VelocityOut.z, B_back.z, F_back);
F_right = round(B_right.w) == SOLID_CELL ? 1 : 0;
F_left = round(B_left.w) == SOLID_CELL ? 1 : 0;
F_up = round(B_up.w) == SOLID_CELL ? 1 : 0;
F_down = round(B_down.w) == SOLID_CELL ? 1 : 0;
F_front = round(B_front.w) == SOLID_CELL ? 1 : 0;
F_back = round(B_back.w) == SOLID_CELL ? 1 : 0;

